"""Batch 5A — R-033 to R-036 controls."""
from risk_controls import C

CONTROLS_5A = {

# ── R-033 — Money laundering, sanctions, terrorism financing ──
"R-033": {
    "universal": [
        C("AML/CTF programme aligned to FATF",
          "Directive", "Hybrid",
          "Documented AML/CTF programme covering risk assessment, customer due diligence, ongoing monitoring, suspicious activity reporting, and governance.",
          "Continuous + Annual programme review", "MLRO / Chief Compliance Officer",
          "Programme effectiveness review; risk assessment refresh; training completion",
          "FATF / AML/CTF Act"),
        C("Customer due diligence (CDD) and KYC",
          "Preventive", "Hybrid",
          "Risk-based CDD with identity verification, beneficial ownership, source of funds/wealth, and enhanced DD for high-risk customers and PEPs.",
          "Per onboarding + Periodic refresh", "Onboarding / KYC team",
          "CDD completion; enhanced DD coverage; refresh aging",
          "FATF Recs 10-12"),
        C("Sanctions screening — customers, transactions, payments",
          "Preventive", "Automated",
          "Automated sanctions screening of customers, counterparties, and transactions against current sanctions lists (UN, OFAC, AU/UK/EU) with alert investigation.",
          "Continuous", "Sanctions Officer / Compliance",
          "Screening coverage; alert volume; true-positive rate; investigation cycle time",
          "OFAC / UN / DFAT / OFSI"),
        C("Suspicious activity reporting and transaction monitoring",
          "Detective", "Automated",
          "Transaction monitoring with rules and analytics to detect suspicious patterns, with SAR/SMR filing process and quality review.",
          "Continuous + Per alert", "Financial Crime Operations",
          "Alert volume; SAR/SMR filings; alert closure cycle; quality review pass rate",
          "FATF Rec 20 / AUSTRAC"),
    ],
    "industry": {
        "PROF": [
            C("Tranche 2 designated services management",
              "Preventive", "Hybrid",
              "Identification of designated services (real estate, trust services, complex structures) with tailored CDD and ongoing monitoring per tranche 2 requirements.",
              "Per matter", "MLRO / Compliance Partner",
              "Designated service coverage; CDD on tranche 2 matters; SMR filings",
              "AML/CTF Act tranche 2"),
            C("Trust account and source of funds verification",
              "Preventive", "Hybrid",
              "Source of funds verification on trust account deposits with thresholds for additional documentation and SMR triggers.",
              "Per deposit", "Trust Account Controller / MLRO",
              "Verification completion; threshold breaches; SMR conversions", ""),
        ],
        "FINS": [
            C("Three lines of defence financial crime model",
              "Directive", "Hybrid",
              "Three lines of defence with first-line responsibility, second-line oversight (Financial Crime function), and Internal Audit assurance.",
              "Continuous", "Chief Compliance Officer / MLRO",
              "Coverage of three lines; assurance findings; remediation closure",
              "BCBS Sound Management of AML"),
            C("Correspondent banking and high-risk customer review",
              "Preventive", "Hybrid",
              "Enhanced due diligence on correspondent banking, high-risk geographies, and complex structures with senior management approval.",
              "Per relationship + Annual review", "Senior Management / MLRO",
              "Correspondent relationships; EDD currency; declined relationships",
              "FATF Rec 13 / Wolfsberg"),
        ],
        "TECH": [
            C("Platform onboarding KYC/KYB and risk scoring",
              "Preventive", "Automated",
              "Automated KYC/KYB on platform users / merchants with risk scoring, document verification, and ongoing monitoring as risk evolves.",
              "Continuous + Per onboarding", "Trust & Safety / Compliance",
              "Onboarding completion; risk score distribution; declined applications",
              ""),
            C("Crypto / payment rail-specific monitoring",
              "Detective", "Automated",
              "Specialised monitoring for crypto, instant payments, and cross-border with chain analytics, structuring detection, and emerging typologies.",
              "Continuous", "Head of Financial Crime",
              "Typology coverage; chain analytics findings; new pattern detection",
              "FATF VA Recs"),
        ],
        "HCAR": [
            C("High-value supplier and provider AML screening",
              "Preventive", "Hybrid",
              "AML screening of high-value suppliers, locum agencies, and providers with enhanced due diligence on overseas relationships.",
              "Per onboarding + Annual",
              "Procurement / Finance",
              "Supplier screening completion; high-risk supplier %; refresh cycle", ""),
            C("Patient billing pattern monitoring for laundering indicators",
              "Detective", "Hybrid",
              "Monitoring of patient billing patterns for laundering indicators (unusual cash, structured payments, suspicious self-pay).",
              "Continuous", "Revenue Cycle / Compliance",
              "Pattern alerts; investigation outcomes; SMR filings", ""),
        ],
        "RETL": [
            C("Cash transaction reporting (TTR) and structuring detection",
              "Detective", "Hybrid",
              "Detection and reporting of large cash transactions and structuring patterns per regulatory thresholds (e.g. AUD 10k AUSTRAC TTR).",
              "Continuous + Per transaction", "Finance / Compliance",
              "TTR filings on time; structuring detection; staff awareness",
              "AUSTRAC TTR"),
            C("Gift card and high-value goods controls",
              "Preventive", "Hybrid",
              "Controls on gift card sales, high-value goods (jewellery, luxury), and bulk purchases with limits and identification requirements.",
              "Continuous", "Loss Prevention / Compliance",
              "Limit compliance; identification capture; suspicious purchase escalation", ""),
        ],
        "INDU": [
            C("Trade finance and customs sanctions compliance",
              "Preventive", "Hybrid",
              "Trade finance compliance covering sanctioned countries, controlled goods, and dual-use items with export licence management.",
              "Per shipment + Continuous", "Trade Compliance / GC",
              "Licence compliance; sanctions screening; controlled goods management",
              "OFAC / EU dual-use / DFAT"),
            C("Counterparty screening for project finance and JVs",
              "Preventive", "Hybrid",
              "Enhanced screening of project finance partners, JV counterparties, and equity participants for sanctions, PEP, and corruption risk.",
              "Per relationship + Periodic refresh", "GC / Risk",
              "Screening completion; PEP relationships; declined counterparties", ""),
        ],
        "PUBL": [
            C("Charity sector ML/TF risk assessment",
              "Preventive", "Manual",
              "Charity-sector ML/TF risk assessment focused on diversion of funds, beneficiary exploitation, and overseas program risk.",
              "Annually + Per program", "MLRO / CFO",
              "Risk assessment refresh; high-risk programs; mitigation actions",
              "FATF Rec 8"),
            C("Donor and beneficiary screening for sanctions",
              "Preventive", "Hybrid",
              "Sanctions screening of major donors, partner organisations, and beneficiary lists especially for international programs.",
              "Per donation/program + Continuous", "Compliance / Programs",
              "Screening coverage; alerts investigated; declined relationships", ""),
        ],
    },
},

# ── R-034 — Bribery, corruption, and improper payments ──
"R-034": {
    "universal": [
        C("Anti-bribery and corruption (ABC) policy and code of conduct",
          "Directive", "Manual",
          "Board-approved ABC policy and code of conduct covering bribery, kickbacks, gifts, hospitality, and political contributions, with attestation.",
          "Annually + On joining", "GC / Compliance",
          "Policy attestation; awareness scores; code violations",
          "ISO 37001 / FCPA / UK Bribery Act"),
        C("Risk-based anti-bribery due diligence on third parties",
          "Preventive", "Hybrid",
          "Risk-based ABC due diligence on agents, intermediaries, JV partners, and high-risk vendors with enhanced screening for high-risk geographies.",
          "Per onboarding + Periodic refresh", "Compliance / Procurement",
          "DD completion; high-risk DD %; declined relationships",
          "ISO 37001 / TI Guidance"),
        C("Gift, hospitality, and conflict of interest register",
          "Detective", "Hybrid",
          "Centralised register of gifts, hospitality, and conflicts with thresholds for declaration, approval workflows, and periodic review.",
          "Per event + Quarterly review", "Compliance / HR",
          "Register completeness; threshold compliance; pattern review", ""),
        C("Anti-bribery training and certification",
          "Preventive", "Hybrid",
          "Mandatory ABC training with role-specific scenarios for higher-risk roles, refresher cycles, and certification requirements.",
          "Annually + Onboarding", "Compliance / L&D",
          "Training completion; assessment scores; high-risk role certification", ""),
    ],
    "industry": {
        "PROF": [
            C("Lateral partner ABC due diligence",
              "Preventive", "Manual",
              "ABC due diligence on lateral partner candidates including reference checks, regulatory history, and current matter portfolio.",
              "Per lateral", "Managing Partner / Compliance",
              "DD completion; declinations; post-hire issue rate", ""),
            C("Foreign government / SOE matter acceptance",
              "Preventive", "Manual",
              "Heightened acceptance review for matters involving foreign governments or SOEs with FCPA/UKBA risk assessment.",
              "Per matter", "Acceptance Committee / GC",
              "FCPA-relevant matters; acceptance decisions; flagged issues",
              "FCPA / UKBA / DFA"),
        ],
        "FINS": [
            C("Politically Exposed Person (PEP) management",
              "Preventive", "Hybrid",
              "Identification, EDD, and ongoing monitoring of PEPs with senior management approval and source of wealth verification.",
              "Per relationship + Continuous", "Compliance / Senior Management",
              "PEP relationships; EDD currency; SMR conversions",
              "FATF Recs 12, 22"),
            C("Inducement, gift, and event hospitality controls",
              "Preventive", "Hybrid",
              "Strict controls on client / counterparty inducements, gifts, and event hospitality with conduct rules-aligned thresholds.",
              "Per event", "Conduct / Compliance",
              "Hospitality register; threshold compliance; conduct breach incidents",
              "FCA / MiFID II / SMCR"),
        ],
        "TECH": [
            C("Government contracting and procurement integrity",
              "Preventive", "Hybrid",
              "Procurement integrity controls for government contracts including anti-corruption certifications, gift restrictions, and disclosure obligations.",
              "Per government engagement", "GC / Sales Compliance",
              "Government engagement disclosures; certification compliance; flagged events",
              "FAR / GovProc"),
            C("Channel partner and reseller compliance",
              "Preventive", "Hybrid",
              "Compliance programme for channel partners and resellers with ABC certification, audit rights, and termination triggers.",
              "Per partner + Annual", "Channel Compliance",
              "Partner certification; audits performed; termination events", ""),
        ],
        "HCAR": [
            C("Pharma / medical device interaction transparency",
              "Preventive", "Hybrid",
              "Transparency in pharma and medical device industry interactions with payment disclosure, hospitality limits, and clinical decision protection.",
              "Continuous + Annual disclosure", "Director of Clinical Governance / Compliance",
              "Disclosed interactions; hospitality limits; clinical influence concerns",
              "Sunshine Acts / Medicines Australia Code"),
            C("Procurement integrity for clinical supplies",
              "Preventive", "Hybrid",
              "Procurement controls for clinical supplies and equipment with conflict of interest declarations from clinical decision-makers.",
              "Per major procurement", "Procurement / CMO",
              "CoI declarations; procurement audit findings; vendor rotation", ""),
        ],
        "RETL": [
            C("Buyer and merchandising integrity controls",
              "Preventive", "Hybrid",
              "Controls on buyer relationships with suppliers including gift policies, supplier contact rules, and relationship rotation.",
              "Continuous + Annual rotation", "Procurement / HR",
              "Gift register; rotation completion; integrity incidents", ""),
            C("Overseas sourcing anti-bribery due diligence",
              "Preventive", "Manual",
              "Enhanced ABC due diligence on overseas suppliers and sourcing agents in high-corruption geographies.",
              "Per supplier onboarding + Annual", "Sourcing / Compliance",
              "DD completion; high-risk supplier %; declined sourcing",
              "TI CPI / UK Bribery Act"),
        ],
        "INDU": [
            C("Facilitation payments policy and tracking",
              "Preventive", "Manual",
              "Clear facilitation payments policy (typically prohibition) with exceptional approval, documentation, and disclosure for any payments made.",
              "Per event", "GC / Compliance",
              "Facilitation payment events; approvals; disclosure compliance",
              "FCPA / UK Bribery Act"),
            C("Permit, licensing, and government interaction controls",
              "Preventive", "Hybrid",
              "Controls on permitting and licensing interactions including approval, disclosure, and prohibition of inducements.",
              "Continuous + Per interaction", "GC / Government Relations",
              "Interaction disclosures; flagged events; approval compliance", ""),
        ],
        "PUBL": [
            C("Procurement probity and tender integrity",
              "Preventive", "Hybrid",
              "Probity framework for procurement including independent probity advisors on major tenders, conflict declarations, and disclosure.",
              "Per major tender", "Probity Officer / Procurement",
              "Probity advisor engagement; CoI declarations; tender complaints",
              "AU Procurement Rules"),
            C("ICAC-compliant integrity framework",
              "Preventive", "Hybrid",
              "Integrity framework aligned to ICAC / corruption commission expectations with reporting, investigation, and consequences.",
              "Continuous", "Integrity Officer / CEO",
              "Reports received; investigations; ICAC referrals",
              "ICAC / NSW Commission"),
        ],
    },
},

# ── R-035 — External fraud (against the organisation) ──
"R-035": {
    "universal": [
        C("Fraud risk assessment and control framework",
          "Preventive", "Hybrid",
          "Comprehensive external fraud risk assessment with control framework covering payment fraud, identity fraud, application fraud, and emerging threats.",
          "Annually + Continuous monitoring", "Head of Fraud / Risk",
          "Risk assessment refresh; control gaps; emerging threat coverage",
          "ACFE / COSO Fraud Risk"),
        C("Fraud detection rules and analytics",
          "Detective", "Automated",
          "Real-time fraud detection rules and behavioural analytics on transactions, applications, and accounts with continuous tuning.",
          "Continuous", "Fraud Operations",
          "Detection rate; false positive rate; loss prevented vs incurred", ""),
        C("Customer / employee fraud awareness programme",
          "Preventive", "Hybrid",
          "Customer and employee fraud awareness with scams education, BEC training, and reporting mechanisms.",
          "Continuous + Annual training", "Communications / L&D",
          "Awareness reach; reported scams; loss avoided through reporting", ""),
        C("Fraud investigation and recovery capability",
          "Corrective", "Hybrid",
          "Investigation capability with documented procedures, law enforcement liaison, recovery actions, and learning loop into prevention.",
          "Continuous + Per case", "Fraud Investigation",
          "Case closure cycle; recovery rate; prevention learning closure", ""),
    ],
    "industry": {
        "PROF": [
            C("Business email compromise (BEC) prevention",
              "Preventive", "Hybrid",
              "BEC prevention with email authentication (SPF/DKIM/DMARC), out-of-band payment verification, and partner-level training on impersonation.",
              "Continuous", "CISO / Finance",
              "DMARC enforcement; verification compliance; BEC attempts blocked",
              "M3AAWG / NCSC BEC"),
            C("Trust account and client fund protection",
              "Preventive", "Hybrid",
              "Enhanced controls on trust account transactions with dual approval, callback verification on changes, and rapid response on suspected fraud.",
              "Per transaction + Continuous", "Trust Account Controller",
              "Verification compliance; suspicious transaction holds; recovery rate", ""),
        ],
        "FINS": [
            C("Real-time payment fraud and scam protection",
              "Detective", "Automated",
              "Real-time fraud and scam detection on payments with behavioural risk scoring, customer warnings, and rapid response capability.",
              "Continuous", "Head of Fraud",
              "Fraud detection rate; scam losses; customer warnings issued",
              "AU eAML scam codes / UK CRM Code"),
            C("Identity fraud and synthetic identity detection",
              "Preventive", "Automated",
              "Multi-layered identity verification with document verification, biometrics, behavioural signals, and synthetic identity detection.",
              "Per onboarding + Continuous", "Identity / Fraud",
              "Identity fraud rate; synthetic detection; first-party fraud", ""),
        ],
        "TECH": [
            C("Account takeover protection",
              "Preventive", "Automated",
              "Account takeover prevention with MFA, anomaly detection, device fingerprinting, and step-up authentication on suspicious activity.",
              "Continuous", "Trust & Safety / CISO",
              "ATO incidents; MFA coverage; step-up activation rate", ""),
            C("Marketplace and platform abuse detection",
              "Detective", "Automated",
              "Detection of platform abuse including fraudulent applications, scam listings, payment fraud, and bot-driven activity.",
              "Continuous", "Trust & Safety",
              "Abuse detection rate; account suspensions; user reports", ""),
        ],
        "HCAR": [
            C("Identity fraud at registration and verification",
              "Preventive", "Hybrid",
              "Identity verification at patient registration with document checks, photo verification, and detection of identity sharing or fraud.",
              "Per registration", "Patient Services / Compliance",
              "Identity verification completion; identity fraud detected; insurance fraud", ""),
            C("Prescription and billing fraud monitoring",
              "Detective", "Hybrid",
              "Monitoring of prescription patterns and billing anomalies for indicators of prescription fraud, insurance fraud, and elder targeting.",
              "Continuous", "Pharmacy / Compliance",
              "Prescription anomalies; billing fraud cases; vulnerable patient protection", ""),
        ],
        "RETL": [
            C("Return and refund fraud detection",
              "Detective", "Hybrid",
              "Return / refund fraud detection with policy enforcement, identity verification on high-value returns, and pattern analytics.",
              "Continuous", "Loss Prevention / Customer Service",
              "Return fraud rate; pattern alerts; loss prevented", ""),
            C("Organised retail crime intelligence",
              "Detective", "Hybrid",
              "Organised retail crime intelligence with partner sharing, pattern detection, and law enforcement liaison.",
              "Continuous", "Loss Prevention",
              "ORC incidents; intelligence shared; recoveries", ""),
        ],
        "INDU": [
            C("Vendor master file and BEC controls",
              "Preventive", "Hybrid",
              "Vendor master file controls with dual approval on changes, callback verification, and BEC awareness in finance teams.",
              "Per change", "Finance / IT Security",
              "Master file changes; verification compliance; BEC events", ""),
            C("Cargo theft and supply chain fraud prevention",
              "Preventive", "Hybrid",
              "Cargo theft and supply chain fraud prevention with carrier vetting, GPS tracking, and seal verification.",
              "Continuous", "Logistics / Security",
              "Theft incidents; carrier compliance; recovery rate", ""),
        ],
        "PUBL": [
            C("Grant and benefit fraud prevention",
              "Preventive", "Hybrid",
              "Grant and benefit fraud prevention with eligibility verification, identity checks, and ongoing entitlement reviews.",
              "Per application + Continuous", "Compliance / Programs",
              "Eligibility verification; fraud detected; recovery rate", ""),
            C("BEC and impersonation fraud awareness",
              "Preventive", "Hybrid",
              "BEC and impersonation fraud awareness for staff handling payments and grant disbursements with verification protocols.",
              "Continuous + Annual training", "Finance / IT Security",
              "BEC attempts; verification compliance; loss avoided", ""),
        ],
    },
},

# ── R-036 — Business continuity / operational resilience failure ──
"R-036": {
    "universal": [
        C("Business continuity management system (BCMS)",
          "Directive", "Hybrid",
          "Documented BCMS aligned to ISO 22301 covering policy, business impact analysis, plans, exercises, and continuous improvement.",
          "Continuous + Annual review", "BCM Lead / COO",
          "BCMS audit findings; certification status; plan currency", "ISO 22301"),
        C("Business impact analysis and recovery objectives",
          "Detective", "Hybrid",
          "Business impact analysis identifying critical processes with RTO, RPO, and recovery resources required, refreshed annually.",
          "Annually", "BCM Lead",
          "BIA coverage; RTO/RPO defined; resource gaps", ""),
        C("Continuity plans and tested recovery procedures",
          "Corrective", "Hybrid",
          "Documented continuity plans for critical processes with tested recovery procedures, alternate work arrangements, and supply chain alternatives.",
          "Continuous + Annual testing", "BCM Lead / Process Owners",
          "Plan currency; test outcomes; gap closure", ""),
        C("Crisis management and incident response integration",
          "Corrective", "Manual",
          "Integrated crisis management with incident response, communications, and decision authority for major disruptions.",
          "Continuous + Quarterly exercises", "Crisis Management Lead / CEO",
          "Exercise participation; activation cycle time; lessons learned closure",
          "ISO 22361"),
    ],
    "industry": {
        "PROF": [
            C("Remote working and dispersed operation continuity",
              "Preventive", "Hybrid",
              "Remote working capability across full firm with bandwidth, security, and collaboration tools tested for full-firm activation.",
              "Quarterly testing", "CIO / BCM Lead",
              "Remote capacity; activation time; productivity during disruption", ""),
            C("Client commitment continuity protocols",
              "Corrective", "Manual",
              "Protocols for client commitment continuity during disruption including matter handover, deadline management, and communication.",
              "Continuous", "Practice Group Leaders / Risk",
              "Deadline misses during disruption; client communication; matter continuity", ""),
        ],
        "FINS": [
            C("Important Business Services (IBS) and impact tolerances",
              "Directive", "Hybrid",
              "Identified Important Business Services with set impact tolerances, mapping of critical resources, and tested recovery to tolerance.",
              "Annually + Continuous", "COO / Resilience Lead",
              "IBS coverage; tolerance breaches; recovery to tolerance",
              "APRA CPS 230 / FCA / DORA"),
            C("Severe-but-plausible scenario testing",
              "Detective", "Hybrid",
              "Severe-but-plausible scenario stress testing of IBS recovery with multi-component failure, third-party failure, and prolonged disruption.",
              "Annually", "Resilience Lead / CRO",
              "Scenarios tested; tolerance achievement; remediation actions",
              "APRA CPS 230 / FCA Op Res"),
        ],
        "TECH": [
            C("Multi-region and multi-cloud resilience",
              "Preventive", "Automated",
              "Multi-region and multi-cloud architecture for tier-1 services with automated failover, regular failover exercises, and customer transparency.",
              "Continuous + Quarterly drills", "Chief Architect / SRE",
              "Multi-region availability; failover time; drill outcomes", ""),
            C("Customer communication during outages",
              "Corrective", "Hybrid",
              "Customer communication during outages with status pages, proactive notifications, and post-incident reporting.",
              "Per incident", "Head of Customer Communications / SRE",
              "Status page accuracy; communication timeliness; customer satisfaction post-incident", ""),
        ],
        "HCAR": [
            C("Pandemic and surge capacity planning",
              "Preventive", "Hybrid",
              "Pandemic and surge capacity planning with PPE, workforce, bed, and supply chain provisions tested through exercises.",
              "Annually + Per event", "BCM / CMO",
              "Surge plan currency; PPE stockpile; exercise outcomes", ""),
            C("Clinical service continuity through disruption",
              "Corrective", "Hybrid",
              "Clinical service continuity protocols including downtime procedures, patient transfer, and life-critical service prioritisation.",
              "Continuous + Quarterly drills", "CMO / Director of Operations",
              "Downtime drill outcomes; clinical impact during disruption; transfer protocols", ""),
        ],
        "RETL": [
            C("Peak trading continuity and contingency",
              "Preventive", "Hybrid",
              "Peak trading continuity with redundant systems, alternative supply, additional workforce, and rehearsed contingency activation.",
              "Annually + Pre-peak", "COO / Trading Lead",
              "Peak readiness; contingency activations; lost trading time",
              ""),
            C("Supply chain disruption response",
              "Corrective", "Hybrid",
              "Supply chain disruption response with alternative sourcing, inventory positioning, and customer communication protocols.",
              "Continuous + Per disruption", "Chief Supply Chain Officer",
              "Alternative sourcing %; inventory days; OOS rate during disruption", ""),
        ],
        "INDU": [
            C("Critical infrastructure resilience and emergency response",
              "Preventive", "Hybrid",
              "Critical infrastructure resilience covering process safety, emergency response, environmental containment, and community protection.",
              "Continuous + Quarterly exercises", "HSE Director / Operations",
              "Emergency exercise outcomes; response readiness; community drills", ""),
            C("Climate / weather event preparation and recovery",
              "Preventive", "Hybrid",
              "Climate and weather event preparation including cyclone, flood, fire, and heat with operational shutdown protocols and recovery plans.",
              "Per season + Per event", "Site Managers / HSE",
              "Event preparation; shutdown effectiveness; recovery time", ""),
        ],
        "PUBL": [
            C("Emergency response and community service continuity",
              "Corrective", "Hybrid",
              "Emergency response and community service continuity with surge capacity, partner agreements, and prioritised vulnerable beneficiary support.",
              "Continuous + Per event", "BCM / CEO",
              "Service continuity; surge capacity; vulnerable beneficiary contact", ""),
            C("Inter-agency coordination during major incidents",
              "Corrective", "Manual",
              "Inter-agency coordination protocols for major incidents with defined roles, communication, and escalation.",
              "Per incident + Annual exercise", "Emergency Coordinator",
              "Coordination effectiveness; escalation timeliness; lessons learned", ""),
        ],
    },
},
}
