"""Batch 5B — R-037 to R-040 controls."""
from risk_controls import C

CONTROLS_5B = {

# ── R-037 — Conduct: mis-selling, customer detriment, market integrity ──
"R-037": {
    "universal": [
        C("Conduct risk framework with clear standards",
          "Directive", "Hybrid",
          "Conduct risk framework with documented standards, customer outcomes, and behavioural expectations across the customer journey.",
          "Continuous + Annual review", "Chief Risk Officer / Conduct Lead",
          "Framework currency; conduct dashboard; customer outcomes", ""),
        C("Product governance and customer outcome testing",
          "Preventive", "Hybrid",
          "Product governance covering target market, value, and customer outcomes with periodic testing of actual outcomes vs intended.",
          "Per product + Annual review", "Product Governance / Conduct",
          "Outcome testing completion; products with adverse outcomes; remediation",
          "FCA Consumer Duty / RG 274"),
        C("Vulnerable customer / consumer framework",
          "Preventive", "Hybrid",
          "Vulnerable customer framework with identification, tailored support, and protection across products and services.",
          "Continuous", "Customer Vulnerability Lead",
          "Vulnerable customer identification; tailored journeys; complaints from vulnerable",
          "FCA Vulnerable / ASIC RG 271"),
        C("Conduct surveillance and behavioural metrics",
          "Detective", "Hybrid",
          "Conduct surveillance covering communications, sales, and trading with behavioural risk indicators and follow-up investigation.",
          "Continuous", "Conduct Surveillance",
          "Surveillance coverage; alerts; substantiated cases", ""),
    ],
    "industry": {
        "PROF": [
            C("Engagement letter and scope clarity",
              "Preventive", "Hybrid",
              "Engagement letters with clear scope, fees, and deliverables; scope variations documented and approved with client.",
              "Per engagement", "Risk Partner",
              "Engagement letter completion; scope variation documentation; fee disputes", ""),
            C("Independence and conflicts management",
              "Preventive", "Hybrid",
              "Independence and conflicts management throughout client lifecycle with ethical walls, declined work register, and partner sign-off.",
              "Per matter", "Conflicts Partner / Ethics",
              "Conflicts cleared; declined matters; ethical wall integrity", ""),
        ],
        "FINS": [
            C("Sales practices and incentive compensation governance",
              "Preventive", "Hybrid",
              "Governance of sales practices and incentive compensation with conduct-aligned metrics, claw-back, and behavioural performance.",
              "Continuous + Annual review", "CHRO / Conduct",
              "Conduct-aligned metrics; claw-back events; behaviour-related performance",
              "FCA SMCR / APRA BEAR"),
            C("Customer remediation framework",
              "Corrective", "Hybrid",
              "Customer remediation framework with root cause analysis, scope definition, customer contact, and regulator engagement.",
              "Per programme", "Head of Remediation / GC",
              "Remediation programmes; customer reach; regulator engagement", ""),
        ],
        "TECH": [
            C("Dark pattern and design ethics review",
              "Preventive", "Manual",
              "Design ethics review identifying dark patterns, addictive design, and harm to vulnerable users with mandatory remediation.",
              "Per significant feature", "Chief Trust Officer / CPO",
              "Reviews completed; remediation; dark pattern incidents",
              "DSA / Online Safety"),
            C("Marketing claims and pricing fairness",
              "Preventive", "Hybrid",
              "Review of marketing claims for accuracy and pricing for fairness, particularly for AI-driven personalisation.",
              "Per campaign + Continuous", "GC / CMO",
              "Marketing reviews; pricing fairness flags; complaints", ""),
        ],
        "HCAR": [
            C("Clinical decision-making and overservicing prevention",
              "Preventive", "Hybrid",
              "Clinical pathway adherence and review processes preventing overservicing or undertreatment with transparent decision-making.",
              "Continuous + Periodic audit", "CMO / Clinical Directors",
              "Pathway adherence; intervention rate review; clinical audit findings", ""),
            C("Vulnerable patient consent and capacity",
              "Preventive", "Hybrid",
              "Consent and capacity assessment for vulnerable patients including aged care, mental health, and disability with advocacy involvement.",
              "Per intervention", "CMO / Director of Quality",
              "Consent documentation; capacity assessments; advocacy engagement",
              ""),
        ],
        "RETL": [
            C("Marketing claims, pricing, and unit pricing compliance",
              "Preventive", "Hybrid",
              "Marketing claim review, pricing accuracy, and unit pricing compliance with consumer regulator expectations.",
              "Continuous", "Compliance / CMO",
              "Marketing review completion; pricing accuracy audits; unit pricing compliance",
              "ACL / ACCC"),
            C("BNPL and credit responsible practice",
              "Preventive", "Hybrid",
              "Responsible practice on BNPL and credit including affordability, vulnerable consumer protection, and disclosure.",
              "Continuous", "Compliance / Chief Customer Officer",
              "Affordability checks; vulnerable consumer outcomes; complaints",
              "ASIC RG / FCA"),
        ],
        "INDU": [
            C("Cartel and anti-competitive behaviour prevention",
              "Preventive", "Hybrid",
              "Cartel and anti-competitive behaviour prevention with training for commercial teams, communication monitoring, and bid-rigging awareness.",
              "Continuous + Annual training", "GC / Compliance",
              "Training completion; communications monitoring; flagged events",
              "ACCC / EU Competition / DOJ Antitrust"),
            C("Greenwashing and product claims integrity",
              "Preventive", "Hybrid",
              "Sustainability and product claims integrity with substantiation, third-party verification, and ASIC/ACCC alignment.",
              "Per claim", "Sustainability / Marketing / Compliance",
              "Claims verified; substantiation quality; greenwashing complaints",
              "ASIC INFO 271 / ACCC"),
        ],
        "PUBL": [
            C("Beneficiary safeguarding and trauma-informed practice",
              "Preventive", "Hybrid",
              "Safeguarding and trauma-informed practice including vulnerable beneficiary protection, cultural safety, and transparent decisions.",
              "Continuous + Annual training", "Safeguarding Lead",
              "Training completion; safeguarding incidents; trauma-informed practice scores", ""),
            C("Communications integrity and accessible information",
              "Preventive", "Hybrid",
              "Communications integrity covering accessible language, accuracy, and respect for beneficiaries' decision-making capacity.",
              "Continuous", "Communications / Inclusion",
              "Plain language compliance; accessibility; complaints on communications", ""),
        ],
    },
},

# ── R-038 — Statutory reporting and tax compliance failure ──
"R-038": {
    "universal": [
        C("Reporting calendar and obligation register",
          "Preventive", "Hybrid",
          "Comprehensive reporting calendar covering financial, regulatory, tax, and disclosure obligations with owners and lead times.",
          "Continuous + Annual refresh", "CFO / Compliance",
          "Calendar completeness; on-time delivery; obligation coverage", ""),
        C("Reporting controls and reconciliation framework",
          "Preventive", "Hybrid",
          "Reporting controls including reconciliations, review hierarchies, and sign-off authorities with documented evidence.",
          "Per cycle", "Financial Controller / CFO",
          "Reconciliation completion; review sign-off; control failures",
          "SOX / ASA 315"),
        C("Tax compliance framework",
          "Preventive", "Hybrid",
          "Tax compliance framework covering income tax, GST/VAT, payroll, and emerging digital taxes with specialist input on complex matters.",
          "Continuous + Per filing", "Head of Tax",
          "Filing timeliness; positions documented; ATO/HMRC interactions",
          "OECD BEPS / ATO Tax Risk"),
        C("External reporting governance and assurance",
          "Detective", "Hybrid",
          "Governance of external reporting with audit committee oversight, external assurance, and management certification.",
          "Per cycle + Annual", "Audit Committee / CFO",
          "Audit findings; certification compliance; restatements",
          "ASX listing rules / SOX"),
    ],
    "industry": {
        "PROF": [
            C("Trust account and regulatory reporting",
              "Preventive", "Hybrid",
              "Specialised trust account reporting with regulator filings, external audits, and exception reporting.",
              "Per regulator cycle", "Trust Account Controller",
              "Reporting timeliness; exception reports; audit findings", ""),
            C("Practice management financial reporting integrity",
              "Detective", "Hybrid",
              "Practice management financial reporting with WIP, lock-up, and partner-level reporting integrity controls.",
              "Monthly", "CFO",
              "Reconciliation breaks; WIP integrity; partner reporting accuracy", ""),
        ],
        "FINS": [
            C("Prudential and statistical reporting",
              "Preventive", "Hybrid",
              "Prudential and statistical reporting with data quality controls, tolerance checks, and regulator query response.",
              "Per cycle (often weekly/monthly)", "Head of Regulatory Reporting",
              "Filing timeliness; data quality scores; resubmissions",
              "BCBS 239 / APRA Reporting"),
            C("Financial Crime and conduct reporting",
              "Preventive", "Hybrid",
              "Financial crime and conduct reporting (SAR, breach reports, customer outcomes) with quality assurance.",
              "Per cycle + Per event", "MLRO / CCO",
              "Filing timeliness; quality findings; thematic patterns", ""),
        ],
        "TECH": [
            C("Revenue recognition and SaaS metrics integrity",
              "Preventive", "Hybrid",
              "Revenue recognition controls per ASC 606/IFRS 15 with SaaS metrics integrity (ARR, NRR, deferred revenue) and audit trail.",
              "Per cycle", "Financial Controller",
              "Revenue recognition findings; SaaS metric reconciliation; restatements",
              "ASC 606 / IFRS 15"),
            C("Multi-jurisdiction tax compliance",
              "Preventive", "Hybrid",
              "Multi-jurisdiction tax compliance covering income tax, sales tax/VAT, transfer pricing, and Pillar Two readiness.",
              "Per filing + Annual", "Head of Tax",
              "Jurisdictions covered; filing timeliness; transfer pricing documentation",
              "OECD BEPS Pillar Two"),
        ],
        "HCAR": [
            C("Clinical coding accuracy and casemix reporting",
              "Detective", "Hybrid",
              "Clinical coding accuracy programme with audit, education, and casemix reporting integrity.",
              "Continuous + Quarterly audit", "Director of Clinical Coding",
              "Coding accuracy; audit findings; casemix variance", ""),
            C("Activity and outcomes reporting to funders",
              "Preventive", "Hybrid",
              "Activity and outcomes reporting to funders with data quality controls, audit trail, and timely submission.",
              "Per funder cycle", "CFO / Funding Officer",
              "Submission timeliness; data quality; funder findings", ""),
        ],
        "RETL": [
            C("Inventory and revenue cut-off accuracy",
              "Preventive", "Hybrid",
              "Inventory and revenue cut-off controls particularly at period end with stocktake, sales recognition, and gift card/loyalty accruals.",
              "Per cycle + Annual stocktake", "Financial Controller",
              "Cut-off accuracy; stocktake variance; restatements", ""),
            C("Modern slavery and sustainability disclosure",
              "Preventive", "Hybrid",
              "Modern slavery, sustainability, and emerging mandatory disclosures with data quality, governance, and assurance.",
              "Annual + Continuous", "Chief Sustainability Officer / GC",
              "Statement completeness; supplier data quality; assurance findings",
              "Modern Slavery Acts / ISSB / ASRS"),
        ],
        "INDU": [
            C("Mandatory climate and ESG disclosure",
              "Preventive", "Hybrid",
              "Mandatory climate and ESG disclosure programme with Scope 1/2/3 data, scenario analysis, and assurance readiness.",
              "Annual + Continuous", "Chief Sustainability Officer / CFO",
              "Disclosure completeness; data quality; assurance findings",
              "TCFD / ISSB / ASRS S1/S2"),
            C("Resource sector reporting (royalties, EPBC, water)",
              "Preventive", "Hybrid",
              "Sector-specific reporting on royalties, environmental obligations (EPBC), and water with regulator-aligned data integrity.",
              "Per cycle", "GM Government Relations / HSE",
              "Reporting timeliness; data integrity; regulator findings", ""),
        ],
        "PUBL": [
            C("Funder acquittal and outcomes reporting",
              "Preventive", "Hybrid",
              "Funder acquittal and outcomes reporting with documentary evidence, expenditure traceability, and outcomes measurement integrity.",
              "Per acquittal cycle", "CFO / Programs",
              "Acquittal accuracy; funder findings; recovery actions", ""),
            C("Statutory reporting (charity, ACNC, sector regulator)",
              "Preventive", "Hybrid",
              "Statutory reporting to charity regulator (ACNC), sector regulators (NDIS, aged care), and ATO with governance oversight.",
              "Per cycle", "Company Secretary / CFO",
              "Filing timeliness; data quality; regulator findings", ""),
        ],
    },
},

# ── R-039 — Data quality, integrity, and management failure ──
"R-039": {
    "universal": [
        C("Data governance framework with stewardship",
          "Directive", "Manual",
          "Data governance framework with data ownership, stewardship roles, quality standards, and policy framework.",
          "Continuous + Annual review", "Chief Data Officer",
          "Governance maturity; stewardship coverage; policy compliance",
          "DAMA-DMBOK / DCAM"),
        C("Data quality monitoring and remediation",
          "Detective", "Hybrid",
          "Data quality monitoring on critical data elements with quality metrics, root cause analysis, and remediation tracking.",
          "Continuous", "Data Quality Lead",
          "Quality metrics; CDE coverage; remediation closure", ""),
        C("Master data management (MDM)",
          "Preventive", "Hybrid",
          "Master data management for key entities (customer, product, vendor) with single source of truth and reconciliation across systems.",
          "Continuous", "MDM Lead",
          "MDM coverage; cross-system reconciliation; duplicate rate", ""),
        C("Data lineage and metadata management",
          "Preventive", "Hybrid",
          "Data lineage documentation with metadata catalogue supporting impact analysis, regulatory reporting, and AI/ML governance.",
          "Continuous", "Data Architect",
          "Lineage coverage; metadata completeness; impact analysis support",
          "BCBS 239"),
    ],
    "industry": {
        "PROF": [
            C("Matter and client master data integrity",
              "Preventive", "Hybrid",
              "Matter and client master data integrity controls including conflicts data, contact data, and matter classification.",
              "Continuous", "Practice Management Lead",
              "Master data quality; conflicts data accuracy; matter classification consistency", ""),
            C("KM and precedent quality controls",
              "Preventive", "Hybrid",
              "Knowledge management and precedent data quality with currency checks, expert validation, and feedback integration.",
              "Continuous + Quarterly review", "Knowledge Manager",
              "Precedent currency; expert validation; usage feedback", ""),
        ],
        "FINS": [
            C("Risk data aggregation and reporting (BCBS 239)",
              "Preventive", "Hybrid",
              "Risk data aggregation capability with data lineage, quality controls, and timeliness supporting regulatory and internal risk reporting.",
              "Continuous", "Chief Data Officer / CRO",
              "BCBS 239 maturity; aggregation timeliness; data quality scores",
              "BCBS 239"),
            C("Customer data integrity and golden record",
              "Preventive", "Hybrid",
              "Customer data integrity with golden record across products, accurate customer view, and cross-system consistency.",
              "Continuous", "Chief Data Officer / Customer",
              "Golden record coverage; cross-system match rate; data quality complaints", ""),
        ],
        "TECH": [
            C("Data quality SLAs for AI/ML training data",
              "Preventive", "Hybrid",
              "Data quality SLAs and validation for AI/ML training data with bias testing and provenance tracking.",
              "Per dataset / Continuous", "Data Engineering / ML Lead",
              "Training data quality; bias metrics; provenance completeness", ""),
            C("Customer telemetry and product analytics integrity",
              "Detective", "Automated",
              "Customer telemetry and product analytics integrity with event tracking standards, anomaly detection, and dashboard reconciliation.",
              "Continuous", "Head of Analytics",
              "Telemetry coverage; anomaly events; dashboard accuracy", ""),
        ],
        "HCAR": [
            C("Patient identification and matching",
              "Preventive", "Hybrid",
              "Patient identification and matching across systems with identifier standards, matching algorithms, and duplicate resolution.",
              "Continuous", "CMIO / Patient Master Index",
              "Match rate; duplicate rate; misidentification incidents", ""),
            C("Clinical data quality and coding accuracy",
              "Detective", "Hybrid",
              "Clinical data quality controls covering documentation completeness, coding accuracy, and outcomes data integrity.",
              "Continuous + Audit", "CMIO / Director of Quality",
              "Documentation completeness; coding accuracy; outcomes data quality", ""),
        ],
        "RETL": [
            C("Product master data and SKU management",
              "Preventive", "Hybrid",
              "Product master data and SKU management with attribute completeness, supplier-driven updates, and merchandising consistency.",
              "Continuous", "Master Data / Buying",
              "Attribute completeness; SKU duplicates; supplier data quality", ""),
            C("Customer data integration across channels",
              "Preventive", "Hybrid",
              "Customer data integration across loyalty, e-commerce, and stores with single customer view and consent integrity.",
              "Continuous", "Chief Data Officer / Customer",
              "Single customer view coverage; cross-channel match; consent integrity", ""),
        ],
        "INDU": [
            C("Asset master data and IoT data quality",
              "Preventive", "Hybrid",
              "Asset master data and IoT/operational data quality with sensor calibration, data validation, and lineage to decisions.",
              "Continuous", "Asset Manager / OT",
              "Sensor health; data validation; decision support quality", ""),
            C("ESG data quality and assurance readiness",
              "Preventive", "Hybrid",
              "ESG data quality controls supporting mandatory disclosure with assurance readiness and methodological consistency.",
              "Continuous + Annual", "Chief Sustainability Officer",
              "Data quality; assurance findings; methodology documentation",
              "ISSB / ASRS / GHG Protocol"),
        ],
        "PUBL": [
            C("Beneficiary identification and case data integrity",
              "Preventive", "Hybrid",
              "Beneficiary identification and case data integrity with consent management, history continuity, and cross-program views.",
              "Continuous", "Director of Service / CDO",
              "Identification accuracy; case data completeness; consent integrity", ""),
            C("Outcomes measurement data quality",
              "Detective", "Hybrid",
              "Outcomes measurement data quality with collection consistency, attribution clarity, and longitudinal integrity.",
              "Continuous", "Outcomes / CDO",
              "Collection consistency; attribution clarity; longitudinal completeness", ""),
        ],
    },
},

# ── R-040 — Model risk and AI / ML governance failure ──
"R-040": {
    "universal": [
        C("Model risk management framework",
          "Directive", "Hybrid",
          "Model risk management framework covering model inventory, risk tiering, validation, monitoring, and governance with second-line oversight.",
          "Continuous + Annual review", "Head of Model Risk / CRO",
          "Inventory completeness; tier coverage; validation cycle; governance maturity",
          "SR 11-7 / SS1/23 / OCC 2011-12"),
        C("Model inventory and risk tiering",
          "Preventive", "Hybrid",
          "Comprehensive model inventory with risk tiering driving validation depth, monitoring frequency, and governance attention.",
          "Continuous + Annual refresh", "Model Risk Lead",
          "Inventory currency; tiering consistency; new-model registration", ""),
        C("Independent model validation",
          "Detective", "Manual",
          "Independent validation of models prior to use and periodically thereafter, covering conceptual soundness, implementation, and ongoing monitoring.",
          "Per model + Periodic", "Model Validation Team",
          "Validation coverage; findings closure; cycle time", ""),
        C("Model monitoring and performance tracking",
          "Detective", "Hybrid",
          "Ongoing model performance monitoring with benchmarks, drift detection, and recalibration triggers.",
          "Continuous", "Model Owners / MR",
          "Performance metrics; drift detection; recalibration timeliness", ""),
    ],
    "industry": {
        "PROF": [
            C("Generative AI usage policy and matter safeguards",
              "Directive", "Hybrid",
              "Generative AI usage policy for matter work covering confidentiality, accuracy verification, and disclosure to clients.",
              "Continuous + Annual review", "Innovation / Risk Partner",
              "Policy attestation; matter incidents; client disclosure compliance", ""),
            C("AI tool evaluation and provider due diligence",
              "Preventive", "Manual",
              "Evaluation of AI tools for legal use including data handling, accuracy, hallucination risk, and provider DD.",
              "Per tool + Annual review", "Innovation / IT Security",
              "Tools evaluated; due diligence completion; tool-related incidents", ""),
        ],
        "FINS": [
            C("Capital and credit model governance",
              "Preventive", "Hybrid",
              "Specific governance for capital, credit, and conduct models with regulator engagement and approval where required.",
              "Per model + Annual", "Head of Capital Models / Credit",
              "Approved models; validation cycle; regulator findings",
              "PRA SS1/23 / APRA APS 113 / Basel"),
            C("AI fairness and explainability for customer-impacting models",
              "Preventive", "Hybrid",
              "Fairness and explainability requirements for customer-impacting AI/ML with bias testing, documentation, and adverse outcome remediation.",
              "Per model + Continuous monitoring", "Model Risk / Conduct",
              "Bias testing; explainability artefacts; adverse outcome incidents",
              "FCA / EU AI Act"),
        ],
        "TECH": [
            C("ML lifecycle governance (MLOps)",
              "Preventive", "Automated",
              "ML lifecycle governance with version control, reproducibility, deployment governance, and monitoring through MLOps tooling.",
              "Continuous", "Head of ML / Platform",
              "Version control compliance; reproducibility tests; deployment gates",
              "MLOps best practice"),
            C("AI safety, red-teaming, and responsible deployment",
              "Detective", "Hybrid",
              "AI safety practices including red-teaming, safety evaluations, harm scenarios, and responsible deployment criteria for high-risk AI.",
              "Per major AI release", "AI Safety / Trust",
              "Red-team coverage; safety evals; harm scenario testing",
              "NIST AI RMF / EU AI Act"),
        ],
        "HCAR": [
            C("Clinical AI/CDS validation and oversight",
              "Preventive", "Hybrid",
              "Clinical AI and decision support validation with clinical evidence, ongoing monitoring, override tracking, and clinician oversight.",
              "Per AI + Continuous", "CMIO / Clinical Governance",
              "Clinical evidence; monitoring; override patterns; outcome correlation",
              "TGA / FDA AI/ML SaMD"),
            C("Patient-facing AI consent and explainability",
              "Preventive", "Manual",
              "Patient consent and explainability for AI use in care decisions with documentation, alternatives offered, and appeal rights.",
              "Per AI use", "CMO / Privacy",
              "Consent documented; alternatives offered; appeals processed", ""),
        ],
        "RETL": [
            C("Pricing and personalisation algorithm fairness",
              "Preventive", "Hybrid",
              "Fairness review of pricing and personalisation algorithms covering vulnerable consumer protection and discrimination prevention.",
              "Per algorithm + Continuous", "Compliance / Data Science",
              "Fairness reviews; vulnerable consumer outcomes; complaints", ""),
            C("Demand forecasting and inventory model monitoring",
              "Detective", "Hybrid",
              "Monitoring of demand forecasting and inventory optimisation models with drift detection and bias on edge cases.",
              "Continuous", "Data Science / Supply Chain",
              "Forecast accuracy; drift detection; edge case performance", ""),
        ],
        "INDU": [
            C("Predictive maintenance and asset model governance",
              "Preventive", "Hybrid",
              "Governance of predictive maintenance and asset performance models with engineer review, false positive/negative balance, and safety integration.",
              "Per model + Continuous", "Reliability / Data Science",
              "Model accuracy; false negative tracking; safety integration", ""),
            C("Process control and digital twin model integrity",
              "Preventive", "Hybrid",
              "Process control model and digital twin integrity with calibration, validation, and OT safety integration.",
              "Continuous", "Process Engineer / OT",
              "Calibration currency; validation findings; control loop integrity", ""),
        ],
        "PUBL": [
            C("Algorithmic decision-making accountability",
              "Preventive", "Hybrid",
              "Accountability framework for algorithmic decisions affecting beneficiaries with explainability, appeal rights, and human review.",
              "Per algorithm + Continuous", "CDO / Director of Service",
              "Explainability artefacts; appeal volume; human override rate",
              "AU Model AI Governance / Robodebt learnings"),
            C("Bias and equity testing in service-design AI",
              "Detective", "Hybrid",
              "Bias and equity testing in service-design AI covering vulnerable beneficiary groups with regular monitoring and remediation.",
              "Per algorithm + Annual", "Equity / Data Science",
              "Bias testing; equity outcomes; remediation actions", ""),
        ],
    },
},
}
