"""
Batch 7 — Missing operational controls flagged from professional framework review.
Added as universal controls to relevant themes.
"""
from risk_controls import C

OPS_CONTROLS = {

# ── R-006 Internal fraud — Three-way match (PO/Receipt/Invoice) ──
"R-006": [
    C("Three-way match — purchase order, goods receipt, and invoice",
      "Preventive", "Automated",
      "Automated three-way match between PO, goods receipt, and supplier invoice with tolerance limits and exception escalation; manual approval required for unmatched payments above thresholds.",
      "Per invoice",
      "Accounts Payable / Financial Controller",
      "Match rate; exceptions escalated; tolerance breaches; manual override volume",
      "COSO 2013 P10; SOX ITAC; PCAOB AS 2201"),
],

# ── R-008 Process failure — Tolerance limits / edit checks / automated calculations ──
"R-008": [
    C("Application controls — edit checks, tolerance limits, automated calculations",
      "Preventive", "Automated",
      "Embedded application controls including field validation, edit checks, tolerance limits, and automated calculations with override governance and exception reporting.",
      "Continuous (per transaction)",
      "Process Owners / IT",
      "Validation reject rate; tolerance overrides; calculation errors detected",
      "COSO 2013 P11; SOX ITAC; PCAOB AS 2201"),
],

# ── R-015 Cyber — Quarterly user access review (UAR) ──
"R-015": [
    C("Quarterly user access reviews and certification",
      "Detective", "Hybrid",
      "Quarterly user access review (UAR) campaign with manager certification of direct reports' access, removal of orphaned and excessive entitlements, and audit trail.",
      "Quarterly",
      "CISO / Identity Lead",
      "UAR completion rate; entitlements removed per cycle; orphan account count; SOX walkthrough findings",
      "NIST 800-53 AC-2(j); SOX ITGC; SOC 2 CC6.2; ISO 27001 A.5.18"),
    C("File integrity monitoring (FIM) on critical assets",
      "Detective", "Automated",
      "File integrity monitoring on critical assets (CDE, regulated systems, configuration files) with baseline establishment, change detection, and alert investigation.",
      "Continuous",
      "CISO / SOC",
      "FIM coverage of critical assets; unauthorised change alerts; investigation cycle time",
      "PCI DSS 11.5; CIS 8.x; NIST 800-53 SI-7"),
],

# ── R-017 Outage — Annual DR failover test with documented RTO/RPO ──
"R-017": [
    C("Annual disaster recovery failover test with documented RTO/RPO",
      "Corrective", "Hybrid",
      "Annual end-to-end disaster recovery failover exercise on tier-1 systems with documented RTO/RPO achievement, lessons learned, and remediation actions tracked to closure.",
      "Annually",
      "BCM Lead / Head of Infrastructure",
      "RTO/RPO achieved vs target; remediation actions closed; tier-1 system coverage",
      "ISO 22301; ISO 27031; NIST 800-53 CP-9/CP-10; SOC 2 A1.2"),
],

# ── R-039 Data quality — Capacity monitoring ──
"R-039": [
    C("Data platform capacity and performance monitoring",
      "Detective", "Automated",
      "Real-time monitoring of data platform capacity, performance, and SLA adherence with auto-scaling triggers and capacity planning forecasts.",
      "Continuous + Quarterly capacity review",
      "Data Platform Lead / SRE",
      "Capacity utilisation; SLA achievement; forecast accuracy; scaling events",
      "ITIL Capacity Mgmt; SOC 2 A1.1; NIST 800-53 SC-5"),
],

}


# ════════════════════════════════════════════════════════════════
# FRAMEWORKS REFERENCE — for new tab
# ════════════════════════════════════════════════════════════════
FRAMEWORKS_REFERENCE = [
    # (Category, Framework, Section/Reference, Brief description)
    ("Internal Control / Governance", "COSO 2013", "17 Principles + Illustrative Tools",
     "Internal Control – Integrated Framework. Core principles for control environment, risk assessment, control activities, information & communication, monitoring."),
    ("Internal Control / Governance", "COSO ERM 2017", "20 Principles",
     "Enterprise Risk Management – Integrating with Strategy and Performance. Strategic and entity-level risk framework."),
    ("Internal Control / Governance", "ISO 31000:2018", "§4-§6",
     "Risk Management — Guidelines. Principles, framework, and process for managing risk across the enterprise."),
    ("Internal Control / Governance", "ISO 37000", "Governance principles",
     "Governance of organisations — Guidance."),

    ("Financial Reporting", "SOX (PCAOB AS 2201)", "ITGC, ITAC, Entity-level",
     "Sarbanes-Oxley Act §302/§404 internal control over financial reporting, audited per PCAOB AS 2201."),
    ("Financial Reporting", "ASC 606 / IFRS 15", "Revenue recognition",
     "Revenue from Contracts with Customers — five-step model."),
    ("Financial Reporting", "IFRS 13 / IAS 36", "Fair value / impairment",
     "Fair value measurement and impairment of assets."),
    ("Financial Reporting", "OECD BEPS Pillar Two", "GloBE rules",
     "Global anti-base erosion rules — minimum effective tax rate of 15% for large MNEs."),
    ("Financial Reporting", "FATCA / CRS", "Customer tax reporting",
     "Foreign Account Tax Compliance Act + OECD Common Reporting Standard."),

    ("IT Governance & Cyber", "COBIT 2019", "40 governance/management objectives",
     "Governance and management framework for enterprise IT. APO, BAI, DSS, MEA domains."),
    ("IT Governance & Cyber", "NIST SP 800-53 Rev. 5", "20 control families (~1,000 controls)",
     "Security and Privacy Controls for Information Systems and Organizations. Most comprehensive control catalogue."),
    ("IT Governance & Cyber", "NIST CSF 2.0", "Govern, Identify, Protect, Detect, Respond, Recover",
     "Cybersecurity Framework — Subcategories serve as control points (e.g. PR.AC-1, DE.CM-1)."),
    ("IT Governance & Cyber", "ISO/IEC 27001:2022", "Annex A — 93 controls",
     "Information security management system requirements. 4 control themes: Organizational, People, Physical, Technological."),
    ("IT Governance & Cyber", "SOC 2 / TSP 100", "Common Criteria + A/C/PI/Privacy",
     "AICPA Trust Services Criteria. Common controls: CC1-CC9; Availability, Confidentiality, Processing Integrity, Privacy."),
    ("IT Governance & Cyber", "PCI DSS 4.0", "12 requirements (~280 sub-controls)",
     "Payment Card Industry Data Security Standard — protection of cardholder data."),
    ("IT Governance & Cyber", "CIS Controls v8", "153 safeguards across 18 controls",
     "Center for Internet Security — most operational cyber baseline."),
    ("IT Governance & Cyber", "IEC 62443", "OT/ICS security",
     "Industrial automation and control systems security."),
    ("IT Governance & Cyber", "OWASP SAMM", "5 business functions",
     "Software Assurance Maturity Model — secure software development."),
    ("IT Governance & Cyber", "NIST SSDF (SP 800-218)", "Secure development",
     "Secure Software Development Framework."),

    ("Operational Resilience", "ISO 22301", "BCMS",
     "Business Continuity Management System."),
    ("Operational Resilience", "ISO 22361", "Crisis management",
     "Crisis management — Guidelines."),
    ("Operational Resilience", "ISO 27031", "ICT readiness",
     "ICT readiness for business continuity."),
    ("Operational Resilience", "APRA CPS 230", "Operational risk management",
     "Australian prudential standard on operational risk and resilience (effective 1 July 2025)."),
    ("Operational Resilience", "FCA / PRA SS1/21", "Operational resilience",
     "UK regulator operational resilience framework — important business services and impact tolerances."),
    ("Operational Resilience", "EU DORA", "Digital operational resilience",
     "Digital Operational Resilience Act (effective Jan 2025)."),

    ("Data & Privacy", "BCBS 239", "11 principles",
     "Basel Committee — Principles for effective risk data aggregation and risk reporting."),
    ("Data & Privacy", "DAMA-DMBOK", "11 knowledge areas",
     "Data Management Body of Knowledge — data governance, quality, architecture, metadata."),
    ("Data & Privacy", "GDPR", "Articles 1-99",
     "EU General Data Protection Regulation — including Art. 25 (privacy by design), Art. 35 (DPIA)."),
    ("Data & Privacy", "Privacy Act 1988 (AU) / APPs", "13 Australian Privacy Principles",
     "Australian privacy law and Notifiable Data Breaches scheme."),
    ("Data & Privacy", "CCPA", "Consumer rights",
     "California Consumer Privacy Act."),
    ("Data & Privacy", "HIPAA Security/Privacy Rule", "PHI protection",
     "US health information privacy and security."),
    ("Data & Privacy", "ISO/IEC 27701", "PIMS",
     "Privacy information management system extension to ISO 27001."),

    ("Financial Crime", "FATF Recommendations", "40 Recommendations",
     "Global AML/CTF standards — risk-based approach."),
    ("Financial Crime", "AML/CTF Act (AU)", "Programme requirements",
     "Australian AML/CTF Act 2006 — including upcoming tranche 2 covering professional services."),
    ("Financial Crime", "Wolfsberg Standards", "AML, Sanctions, ABC",
     "Wolfsberg Group industry standards on AML, sanctions, anti-bribery."),
    ("Financial Crime", "ISO 37001", "Anti-bribery management",
     "Anti-bribery management systems."),
    ("Financial Crime", "FCPA", "Anti-bribery",
     "US Foreign Corrupt Practices Act — extra-territorial bribery enforcement."),
    ("Financial Crime", "UK Bribery Act 2010", "Anti-bribery",
     "UK comprehensive anti-bribery legislation."),
    ("Financial Crime", "OFAC / UN / DFAT / OFSI", "Sanctions regimes",
     "US, UN, AU, UK sanctions — list-based and country-based restrictions."),

    ("Conduct & Compliance", "ISO 37301", "Compliance management",
     "Compliance management systems."),
    ("Conduct & Compliance", "ISO 37002", "Whistleblowing management",
     "Whistleblowing management systems."),
    ("Conduct & Compliance", "FCA Consumer Duty", "Consumer outcomes",
     "UK conduct standard for retail financial services — focuses on consumer outcomes."),
    ("Conduct & Compliance", "ASIC RG 271", "Internal dispute resolution",
     "Australian internal dispute resolution standards."),
    ("Conduct & Compliance", "ASIC RG 274", "Product design and distribution",
     "Australian product design and distribution obligations (DDO)."),
    ("Conduct & Compliance", "FCA SMCR", "Senior Manager accountability",
     "Senior Managers and Certification Regime."),
    ("Conduct & Compliance", "APRA BEAR / FAR", "Banking accountability",
     "Banking Executive Accountability Regime / Financial Accountability Regime."),
    ("Conduct & Compliance", "APRA CPS 220 / 230 / 511", "Risk, Op risk, Remuneration",
     "Australian prudential standards on risk management, operational resilience, remuneration."),

    ("Health & Safety", "ISO 45001", "OHSMS",
     "Occupational health and safety management systems."),
    ("Health & Safety", "ISO 45003", "Psychosocial safety",
     "Psychological health and safety at work."),
    ("Health & Safety", "ICMM Critical Control", "Fatality prevention",
     "International Council on Mining and Metals — critical control management for fatality prevention."),
    ("Health & Safety", "OSHA PSM", "29 CFR 1910.119",
     "US Process Safety Management of Highly Hazardous Chemicals."),
    ("Health & Safety", "ACSQHC NSQHS Standards", "Patient safety",
     "Australian Commission on Safety and Quality in Health Care — National Safety and Quality Health Service standards."),
    ("Health & Safety", "WHO Patient Safety", "Global patient safety",
     "World Health Organization patient safety frameworks."),

    ("Environmental & Social", "ISO 14001", "EMS",
     "Environmental management systems."),
    ("Environmental & Social", "TCFD", "Climate-related disclosures",
     "Task Force on Climate-Related Financial Disclosures."),
    ("Environmental & Social", "ISSB IFRS S1/S2", "Sustainability disclosures",
     "International Sustainability Standards Board — general sustainability and climate disclosures."),
    ("Environmental & Social", "ASRS S1/S2", "AU sustainability disclosures",
     "Australian Sustainability Reporting Standards (effective 1 Jan 2025 for largest entities)."),
    ("Environmental & Social", "GHG Protocol", "Scope 1/2/3 emissions",
     "Greenhouse Gas Protocol — corporate emissions accounting."),
    ("Environmental & Social", "SBTi", "Science-based targets",
     "Science Based Targets initiative — emissions reduction pathway alignment."),
    ("Environmental & Social", "GRI / SASB", "Sustainability reporting",
     "Global Reporting Initiative / Sustainability Accounting Standards Board."),
    ("Environmental & Social", "Modern Slavery Acts", "Supply chain",
     "Modern Slavery Act 2018 (AU) / 2015 (UK) — annual statements."),
    ("Environmental & Social", "UN Guiding Principles", "Business and human rights",
     "UN Guiding Principles on Business and Human Rights (UNGP)."),

    ("Third Party / Supplier", "ISO/IEC 27036", "Supplier security",
     "Information security for supplier relationships."),
    ("Third Party / Supplier", "APRA CPS 230 / 231", "Outsourcing",
     "Australian outsourcing and operational resilience standards."),
    ("Third Party / Supplier", "FCA SYSC 8", "UK outsourcing",
     "UK Financial Conduct Authority outsourcing rules."),
    ("Third Party / Supplier", "SIG (Shared Assessments)", "Vendor due diligence",
     "Standardized Information Gathering questionnaire."),

    ("Model / AI", "Fed SR 11-7 / OCC 2011-12", "Model risk management",
     "US supervisory guidance on model risk management."),
    ("Model / AI", "PRA SS1/23", "Model risk management",
     "UK PRA model risk management principles for banks."),
    ("Model / AI", "APRA CPS 113", "IRB models",
     "Australian capital adequacy — internal ratings-based approach to credit risk."),
    ("Model / AI", "EU AI Act", "AI regulation",
     "Risk-tiered AI regulation (effective progressively from 2024)."),
    ("Model / AI", "NIST AI RMF", "AI risk management",
     "Voluntary framework for managing AI risks — Govern, Map, Measure, Manage."),
    ("Model / AI", "ISO/IEC 42001", "AI management systems",
     "AI management system requirements (analogous to ISO 27001 for AI)."),
    ("Model / AI", "ISO/IEC 23053", "ML framework",
     "Framework for AI systems using machine learning."),
    ("Model / AI", "TGA / FDA SaMD", "Medical AI",
     "Software as a Medical Device — clinical AI regulatory pathways."),

    ("Quality & Operations", "ISO 9001", "QMS",
     "Quality management systems."),
    ("Quality & Operations", "ISO 10002", "Complaints handling",
     "Customer satisfaction — guidelines for complaints handling."),
    ("Quality & Operations", "ITIL 4", "Service management",
     "IT service management practices."),
    ("Quality & Operations", "ISO/IEC 20000", "ITSM",
     "IT service management."),
    ("Quality & Operations", "ISO 55000", "Asset management",
     "Asset management — overview, principles, terminology."),
    ("Quality & Operations", "Six Sigma / SPC", "Statistical process control",
     "Statistical process control and continuous improvement."),

    ("Project / Change", "PMI PMBOK", "Project management",
     "Project Management Institute — Project Management Body of Knowledge."),
    ("Project / Change", "PRINCE2", "Project method",
     "Projects in Controlled Environments."),
    ("Project / Change", "DORA Metrics", "Software delivery performance",
     "Deployment frequency, lead time, change failure rate, MTTR."),
    ("Project / Change", "Google SRE", "Site reliability",
     "SLOs, error budgets, toil reduction, blameless postmortems."),

    ("Legal", "ISO 44001", "Collaborative business relationships",
     "Collaborative business relationship management."),
    ("Legal", "WIPO / National IP frameworks", "IP protection",
     "World Intellectual Property Organization and national IP regimes."),

    ("Sector — Banking/Insurance", "Basel III / IV", "Capital, liquidity, leverage",
     "Basel Committee international banking framework."),
    ("Sector — Banking/Insurance", "BCBS 248", "Intraday liquidity",
     "Monitoring tools for intraday liquidity management."),
    ("Sector — Banking/Insurance", "BCBS 368", "IRRBB",
     "Interest rate risk in the banking book."),
    ("Sector — Banking/Insurance", "Basel III FRTB", "Market risk",
     "Fundamental Review of the Trading Book."),

    ("Sector — Healthcare", "TGA / FDA Medical Device", "Device regulation",
     "Australian Therapeutic Goods Administration / US FDA medical device regulation."),
    ("Sector — Healthcare", "ACSQHC NSQHS Standards", "Health quality",
     "8 standards covering clinical governance, partnering with consumers, healthcare-associated infections, medication safety, etc."),
    ("Sector — Healthcare", "Joint Commission", "Hospital accreditation",
     "US hospital accreditation standards."),

    ("Sector — Retail / Consumer", "FSANZ", "Food standards",
     "Food Standards Australia New Zealand."),
    ("Sector — Retail / Consumer", "ACCC / ACL", "Consumer protection",
     "Australian Competition and Consumer Commission / Australian Consumer Law."),
]
