"""
Batch 8A — Completeness gap-fill controls (R-001 to R-018).
Each new control fills a theme gap identified by the cross-tab analysis.
Authored to fit our existing voice; aligned to recognised frameworks.
"""
from risk_controls import C

GAP_FILL_8A = {

# ── R-001 Strategic plan failure — missing: Risk Assessment ──
"R-001": [
    C("Enterprise risk assessment integrated with strategy",
      "Detective", "Manual",
      "Annual enterprise risk assessment refreshed in line with the strategic plan, identifying threats to delivery, opportunities, and required risk appetite, with board endorsement.",
      "Annually + Per material change",
      "CRO / Strategy Lead",
      "Risk assessment refresh; risks linked to strategic objectives; appetite breaches",
      "ISO 31000 §6.4; COSO ERM 2017"),
],

# ── R-002 Market disruption — missing: Governance & Reporting, Risk Assessment ──
"R-002": [
    C("Innovation steering committee and disruption oversight",
      "Directive", "Manual",
      "Cross-functional innovation / disruption steering committee with executive sponsorship, monthly review of horizon items, and escalation to board on material threats.",
      "Monthly",
      "Chief Innovation Officer / ExCo",
      "Committee participation; horizon items escalated; board engagement on disruption",
      "ISO 37000; COSO ERM 2017"),
    C("Disruption risk and scenario assessment",
      "Detective", "Manual",
      "Periodic structured assessment of disruption scenarios (technology, regulation, entrant, demand shift) with likelihood / impact ratings and pre-mortem against current business model.",
      "Annually + Per material trigger",
      "Strategy Lead / CRO",
      "Scenarios assessed; pre-mortem findings actioned; response options on shelf",
      "ISO 31000; COSO ERM 2017"),
],

# ── R-003 M&A — missing: Governance & Reporting, Monitoring & Surveillance ──
"R-003": [
    C("M&A governance and investment committee",
      "Directive", "Manual",
      "Investment / M&A committee with documented terms of reference, investment thesis approval at term sheet and final, and post-deal review reporting to the board.",
      "Per transaction + Quarterly",
      "Investment Committee / Board",
      "Committee minutes; thesis approvals; deviation from approved deal economics",
      "ISO 37000; ASX CGC Principles"),
    C("Post-deal integration KPI dashboard",
      "Detective", "Hybrid",
      "Monthly integration performance dashboard tracking financial synergies, talent retention, customer / supplier continuity, and integration milestones for 24 months post-deal.",
      "Monthly post-deal",
      "Integration Lead / CFO",
      "Synergy realisation; talent retention 12/24m; customer attrition; integration milestones",
      "PMI Benefits Realization; COSO ERM 2017"),
],

# ── R-004 Cash flow / liquidity — missing: Reconciliation & Verification ──
"R-004": [
    C("Daily cash position reconciliation",
      "Detective", "Hybrid",
      "Daily reconciliation of cash positions across bank accounts, treasury system, and general ledger with break investigation, ageing limits, and cash forecasting feedback.",
      "Daily",
      "Treasurer / Finance Operations",
      "Aged breaks; forecast vs actual variance; reconciliation completion timeliness",
      "COSO 2013 P10; SOX financial close"),
],

# ── R-005 Revenue concentration — missing: Monitoring & Surveillance, Reconciliation & Verification ──
"R-005": [
    C("Customer concentration monitoring dashboard",
      "Detective", "Hybrid",
      "Monthly dashboard tracking top-10 / top-20 customer revenue concentration, growth rates, and dependency metrics with concentration risk-appetite thresholds.",
      "Monthly",
      "CFO / Chief Commercial Officer",
      "Top-10 concentration %; HHI index; appetite breaches; quarter-over-quarter shifts",
      "ISO 31000; COSO ERM monitoring"),
    C("Revenue and contract reconciliation",
      "Detective", "Hybrid",
      "Monthly reconciliation between billing system, contracts, and recognised revenue with anomaly investigation flagging unexpected concentration shifts or contract changes.",
      "Monthly",
      "Financial Controller",
      "Reconciliation breaks; revenue recognition findings; contract-billing discrepancies",
      "COSO 2013 P10; SOX financial close"),
],

# ── R-006 Internal fraud — missing: Risk Assessment ──
"R-006": [
    C("Annual fraud risk assessment with key risk identification",
      "Detective", "Hybrid",
      "Annual fraud risk assessment per ACFE / COSO Fraud Risk Management Guide identifying key fraud risks, schemes, and inherent / residual risk by process and function.",
      "Annually + Event-driven",
      "Internal Audit / CFO",
      "Risk assessment refresh; high-risk schemes identified; control gaps closed",
      "ACFE; COSO Fraud Risk Mgmt Guide"),
],

# ── R-007 Currency / interest rate — missing: Risk Assessment ──
"R-007": [
    C("Market risk identification and quantification framework",
      "Detective", "Hybrid",
      "Documented framework for identifying and quantifying FX, IR, and commodity exposures including transaction, translation, and economic exposures with sensitivity analysis.",
      "Continuous + Quarterly review",
      "Treasurer / CRO",
      "Exposure coverage; sensitivity analysis completeness; unhedged residual exposure",
      "ISO 31000; IFRS 9 / IAS 39"),
],

# ── R-008 Critical process failure — missing: Investigation & Remediation, Risk Assessment ──
"R-008": [
    C("Process risk assessment for critical operations",
      "Detective", "Hybrid",
      "Periodic risk assessment of critical processes covering single points of failure, capacity, control adequacy, and resilience with treatment actions tracked to closure.",
      "Annually + Per material change",
      "COO / Process Owners",
      "Critical processes assessed; treatment actions closed; SPoF count",
      "ISO 31000; ISO 9001 §6"),
    C("Root cause investigation on material process incidents",
      "Corrective", "Hybrid",
      "Root cause analysis for material process incidents using structured methodology (5 Whys, fishbone, fault tree) with corrective actions, learning dissemination, and effectiveness review.",
      "Per incident",
      "Operations Director / Quality",
      "RCA completion timeliness; recurring root causes; verified effectiveness of CAPA",
      "ISO 9001 §10; ISO 22301"),
],

# ── R-009 Asset / equipment failure — missing: many themes ──
"R-009": [
    C("Asset management policy and lifecycle framework",
      "Directive", "Manual",
      "Documented asset management framework aligned to ISO 55000 covering acquisition, operation, maintenance, and disposal with risk-based criticality classification.",
      "Continuous + Annual review",
      "Chief Engineer / Asset Manager",
      "Framework currency; criticality coverage; lifecycle compliance",
      "ISO 55000; ISO 31000"),
    C("Asset condition and performance monitoring",
      "Detective", "Hybrid",
      "Continuous condition and performance monitoring of critical assets with threshold-based alerting, trending, and integration to maintenance planning.",
      "Continuous",
      "Asset Manager / Maintenance",
      "Asset health scores; threshold breaches; predictive vs reactive maintenance ratio",
      "ISO 55000; ITIL"),
    C("Asset criticality and failure risk assessment",
      "Detective", "Hybrid",
      "Risk assessment of asset failure consequences (FMEA-style) for critical assets, driving redundancy, spares, and maintenance investment decisions.",
      "Annually + Per change",
      "Reliability Engineer",
      "FMEA coverage; high-criticality assets with mitigations; risk-driven capex %",
      "ISO 55000; ISO 31000; SAE J1739 (FMEA)"),
    C("Asset failure investigation and reliability improvement",
      "Corrective", "Hybrid",
      "Structured investigation of asset failures with root cause analysis, reliability improvement actions, and feedback into design / procurement standards.",
      "Per material failure",
      "Reliability Engineer",
      "Investigation completion; reliability improvement actions closed; MTBF trend",
      "ISO 55000; ISO 9001 §10"),
    C("Asset management quality assurance and audit",
      "Detective", "Manual",
      "Internal audit programme over asset management practices including data integrity, maintenance compliance, and lifecycle decisions.",
      "Annually",
      "Internal Audit",
      "Audit findings; finding closure; data integrity scores",
      "ISO 55000; IIA Standards"),
],

# ── R-010 Capacity constraint — missing: Investigation & Remediation, Monitoring, Quality Reviews, Risk Assessment ──
"R-010": [
    C("Capacity utilisation monitoring and forecast tracking",
      "Detective", "Hybrid",
      "Real-time monitoring of capacity utilisation against forecasts and demand, with trend analysis and proactive escalation when sustained pressure is detected.",
      "Continuous + Weekly review",
      "Operations Director / Workforce Planning",
      "Utilisation vs target; forecast accuracy; sustained pressure events",
      "ITIL Capacity Mgmt; ISO 31000 §6.6"),
    C("Capacity bottleneck and demand-supply risk assessment",
      "Detective", "Manual",
      "Periodic risk assessment of capacity bottlenecks, demand-supply mismatch, and surge scenarios with mitigation actions integrated into capital and workforce plans.",
      "Quarterly",
      "Operations Director",
      "Bottlenecks identified; mitigations on track; surge readiness scores",
      "ITIL Capacity Mgmt; ISO 31000"),
    C("Capacity failure investigation and improvement",
      "Corrective", "Manual",
      "Structured investigation of capacity-related service failures or SLA breaches with root cause analysis and capacity uplift / process improvement actions.",
      "Per incident",
      "Operations Director",
      "Investigation completion; uplift actions closed; recurrence rate",
      "ISO 9001 §10"),
    C("Capacity assurance and stress testing",
      "Detective", "Manual",
      "Periodic stress testing of capacity against severe-but-plausible demand scenarios with assurance over plans, alternative arrangements, and surge capability.",
      "Annually",
      "Operations Director / BCM Lead",
      "Stress tests completed; gap closure; severe-scenario readiness",
      "ISO 22301; ITIL"),
],

# ── R-011 Quality failure — missing: Continuity & Recovery, Monitoring & Surveillance ──
"R-011": [
    C("Quality KPI dashboard and trend monitoring",
      "Detective", "Automated",
      "Real-time quality KPI dashboard (defect rate, complaint rate, NPS, first-pass yield, near-miss volume) with threshold alerts, trend analysis, and management review cadence.",
      "Continuous + Monthly review",
      "Quality Manager / COO",
      "Defect rate; complaint trends; first-pass yield; NPS movement",
      "ISO 9001 §9; Six Sigma"),
    C("Quality recovery and customer remediation capability",
      "Corrective", "Hybrid",
      "Defined process for quality recovery covering containment, customer remediation, recall coordination, and reputation management with rehearsed activation.",
      "Continuous + Per incident",
      "Quality Director / Customer Service",
      "Remediation activation time; customer impact resolved; recall capability tests",
      "ISO 10002; ISO 22301"),
],

# ── R-036 BCM — missing: Investigation & Remediation, Monitoring & Surveillance, Quality Reviews ──
"R-036": [
    C("Business continuity exercise programme and effectiveness review",
      "Detective", "Hybrid",
      "Programme of BC exercises (tabletop, walkthrough, full simulation) covering scenarios from BIA with documented findings, action closure, and capability maturity tracking.",
      "Quarterly + Annual full-scale",
      "BCM Lead / COO",
      "Exercise frequency; findings closed; capability maturity scores",
      "ISO 22301 §8.5; APRA CPS 230"),
    C("Resilience metrics monitoring and tolerance breaches",
      "Detective", "Hybrid",
      "Continuous monitoring of resilience metrics (RTO/RPO achievement, IBS availability, third-party SLAs) with alerting on tolerance breaches and trend analysis.",
      "Continuous + Monthly review",
      "BCM Lead / Resilience Lead",
      "RTO/RPO achievement; tolerance breaches; third-party SLA performance",
      "APRA CPS 230; ISO 22301; SOC 2 A1.x"),
    C("Post-disruption review and learning",
      "Corrective", "Manual",
      "Structured post-disruption review for material disruption events covering response effectiveness, customer impact, lessons learned, and BCMS improvement actions.",
      "Per material event",
      "BCM Lead / COO",
      "Review completion; lessons learned closure; BCMS updates from learnings",
      "ISO 22301 §10; ISO 9001 §10"),
],

# ── R-012 Loss of key personnel — missing: Investigation & Remediation, Monitoring & Surveillance ──
"R-012": [
    C("Key person dependency monitoring and risk dashboard",
      "Detective", "Hybrid",
      "Monitoring of key person dependencies, retention indicators, and succession bench depth with quarterly executive review and proactive intervention triggers.",
      "Quarterly",
      "CHRO / ExCo",
      "Retention of identified talent; succession bench coverage; flight risk indicators",
      "ASX CGC Principle 1; APRA Fit & Proper"),
    C("Departure investigation and knowledge protection",
      "Corrective", "Manual",
      "Process for material departures (key personnel, MRTs) covering exit interview, knowledge transfer verification, customer / matter handover, and learning capture.",
      "Per departure",
      "CHRO / Direct Manager",
      "Knowledge transfer completion; customer continuity; exit insights captured",
      "ISO 30414; APRA Fit & Proper"),
],

# ── R-013 Talent attraction/retention — missing: Investigation & Remediation, Monitoring & Surveillance, Training & Awareness ──
"R-013": [
    C("Talent metrics monitoring and attrition surveillance",
      "Detective", "Automated",
      "Continuous monitoring of talent metrics (attrition by tenure / level / function, time-to-hire, offer acceptance) with monthly leadership review and root cause investigation on adverse trends.",
      "Continuous + Monthly review",
      "CHRO",
      "Regretted attrition; offer acceptance; time-to-hire; tenure profile",
      "ISO 30414"),
    C("Manager capability training and development",
      "Preventive", "Hybrid",
      "Mandatory manager capability training covering recruitment, coaching, performance management, and inclusive leadership with refresher cycles and effectiveness measurement.",
      "Annually + Per promotion",
      "CHRO / L&D",
      "Manager training completion; manager capability scores; team retention by manager",
      "ISO 30414; ISO 9001 §7.2"),
    C("Talent loss investigation and pattern analysis",
      "Corrective", "Manual",
      "Structured investigation of regretted attrition patterns including exit interviews, manager review, and integration of findings into EVP and retention initiatives.",
      "Per departure + Quarterly trend review",
      "CHRO",
      "Exit interview completion; pattern themes; intervention actions closed",
      "ISO 30414"),
],

# ── R-014 Culture / conduct — missing: Investigation & Remediation ──
"R-014": [
    C("Culture / conduct issue investigation and consequence framework",
      "Corrective", "Manual",
      "Independent investigation framework for culture and conduct issues with documented standards, skilled investigators, and consistent consequences regardless of seniority.",
      "Per allegation",
      "CHRO / Head of Investigations",
      "Investigation cycle time; substantiation rate; consequence consistency",
      "ISO 37002; FCA SMCR"),
],

# ── R-015 Cyber attack — missing: Incident & Crisis Management, Risk Assessment ──
"R-015": [
    C("Cyber risk assessment and threat modelling",
      "Detective", "Hybrid",
      "Periodic cyber risk assessment using threat modelling, attack-path analysis, and risk quantification for critical assets, services, and data.",
      "Annually + Per material change",
      "CISO",
      "Critical assets assessed; threat models current; high-risk findings closed",
      "NIST 800-30; ISO 27005; FAIR"),
    C("Cyber incident response and crisis management",
      "Corrective", "Hybrid",
      "Documented cyber IR plan covering detection, containment, eradication, recovery, and lessons learned with executive crisis activation, regulator notification, and tabletop exercises.",
      "Continuous + Quarterly tabletop",
      "CISO / Crisis Lead",
      "MTTD/MTTR; tabletop completion; regulator notification timeliness; recovery effectiveness",
      "NIST 800-61; ISO 27035; APRA CPS 234"),
],

# ── R-016 Data loss — missing: Incident & Crisis Management, Policy & Framework, Risk Assessment ──
"R-016": [
    C("Data protection policy and privacy framework",
      "Directive", "Manual",
      "Board-approved data protection policy framework covering data classification, handling, retention, sharing, deletion, breach response, and individual rights.",
      "Continuous + Annual review",
      "DPO / Privacy Officer",
      "Policy attestation; coverage of data flows; breach incidents",
      "GDPR; ISO 27701; Privacy Act APP 1"),
    C("Data risk and DPIA programme",
      "Detective", "Hybrid",
      "Programme of data risk assessment and DPIAs for new processes, systems, and high-risk processing, with mitigation tracking and DPO sign-off.",
      "Per project + Annual portfolio review",
      "DPO / Privacy Officer",
      "DPIA completion; high-risk findings closed; portfolio risk profile",
      "GDPR Art. 35; ISO 27701; Privacy Act APP 1"),
    C("Data breach response and notification",
      "Corrective", "Hybrid",
      "Documented data breach response covering detection, assessment, containment, notification (regulators / individuals within statutory timeframes), and lessons learned.",
      "Continuous + Per incident",
      "DPO / CISO",
      "Notification timeliness; affected individuals reach; lessons learned closure",
      "GDPR Art. 33-34; Privacy Act NDB; ISO 27035"),
],

# ── R-017 System outage — missing: Access & Identity Management, Policy & Framework ──
"R-017": [
    C("IT operations and service management policy framework",
      "Directive", "Manual",
      "Documented IT service management framework aligned to ITIL / ISO 20000 covering change, incident, problem, capacity, and availability management.",
      "Continuous + Annual review",
      "Head of IT Operations",
      "Framework currency; certification status; service management maturity",
      "ITIL 4; ISO/IEC 20000"),
    C("Production access and change-window controls",
      "Preventive", "Hybrid",
      "Strict controls on production access including JIT elevation, change windows, segregation of dev / prod, and audit logging of all production activity.",
      "Continuous",
      "Head of IT Operations / CISO",
      "Production access events; out-of-window changes; segregation breaches",
      "NIST 800-53 AC-3/AC-6; SOX ITGC; SOC 2 CC8.1"),
],

# ── R-018 Tech obsolescence — missing: many ──
"R-018": [
    C("Identity and access modernisation programme",
      "Preventive", "Hybrid",
      "Programme to modernise legacy identity and access patterns including consolidation of identity providers, retirement of weak authentication, and zero-trust transition.",
      "Continuous (multi-year)",
      "CIO / CISO",
      "Identity provider consolidation; zero-trust adoption; legacy auth retirement",
      "NIST 800-207 (Zero Trust); CIS 5.x"),
    C("Legacy system continuity and exit planning",
      "Corrective", "Manual",
      "Continuity and exit planning for legacy systems including data preservation, integration replacement, and contingency for vendor failure or end-of-life events.",
      "Per legacy system + Annual review",
      "CIO / Enterprise Architect",
      "Systems with exit plans; vendor risk indicators; data preservation tested",
      "ISO 22301; APRA CPS 230"),
    C("Tech debt risk assessment and prioritisation",
      "Detective", "Hybrid",
      "Periodic risk assessment of technical debt covering security exposure, operational risk, and remediation cost, driving prioritised investment decisions.",
      "Annually + Continuous",
      "Enterprise Architect / CIO",
      "Debt items; high-risk debt remediated; security exposure from debt",
      "ISO 31000; NIST 800-53 RA"),
    C("Modernisation engineering standards and reference architecture",
      "Preventive", "Manual",
      "Engineering standards and reference architecture for modernisation initiatives covering cloud-native patterns, security-by-design, observability, and resilience.",
      "Continuous + Per major initiative",
      "Chief Architect",
      "Standards adoption; reference architecture coverage; deviation justified",
      "TOGAF; NIST SSDF; CIS Benchmarks"),
    C("Modernisation incident response and rollback capability",
      "Corrective", "Hybrid",
      "Documented incident response and rollback capability for modernisation deployments including parallel running, data reconciliation, and reversion criteria.",
      "Per major release",
      "Head of Engineering / Change Manager",
      "Rollback successes; parallel-run effectiveness; modernisation incident MTTR",
      "ITIL; SOC 2 CC8.1"),
    C("Modernisation programme monitoring and reporting",
      "Detective", "Manual",
      "Monthly executive reporting on modernisation programme health covering milestones, budget, capability uplift, legacy retirement, and risk events.",
      "Monthly",
      "CIO / Chief Transformation Officer",
      "Programme RAG; legacy retirement; capability uplift; risk events",
      "PMI PMBOK; ISO 21500"),
],

}
