"""
Batch 8B — Completeness gap-fill controls (R-019 to R-040).
"""
from risk_controls import C

GAP_FILL_8B = {

# ── R-019 Compliance — missing: Investigation & Remediation, Monitoring & Surveillance ──
"R-019": [
    C("Compliance breach investigation and remediation",
      "Corrective", "Hybrid",
      "Defined process for compliance breach investigation, root cause analysis, customer / regulator notification, and remediation tracked through to closure with effectiveness verification.",
      "Per breach",
      "CCO / Investigations Lead",
      "Investigation timeliness; remediation completion; effectiveness verification",
      "ISO 37301; ISO 19011"),
    C("Compliance monitoring dashboard and breach surveillance",
      "Detective", "Hybrid",
      "Real-time compliance monitoring dashboard tracking breaches, near-misses, control failures, and regulator interactions with monthly executive review.",
      "Continuous + Monthly review",
      "CCO",
      "Breach volume / severity; control failure trends; regulator interactions",
      "ISO 37301"),
],

# ── R-020 Litigation — already strong; no critical gaps ──

# ── R-021 Reg change — missing: Investigation & Remediation ──
"R-021": [
    C("Regulatory implementation post-mortem",
      "Corrective", "Manual",
      "Post-mortem on regulatory change implementations covering effectiveness, lessons learned, and improvements to the regulatory change framework.",
      "Per major change",
      "CCO / Reg Change Lead",
      "Post-mortem completion; lessons captured; framework improvements adopted",
      "ISO 37301; ISO 9001 §10"),
],

# ── R-038 Statutory reporting — missing: Investigation & Remediation, Training & Awareness ──
"R-038": [
    C("Reporting error investigation and restatement governance",
      "Corrective", "Hybrid",
      "Defined process for investigating reporting errors, determining materiality, restatement governance, and regulator / market communication.",
      "Per material error",
      "CFO / Audit Committee",
      "Investigation timeliness; restatements; regulator interaction quality",
      "PCAOB AS 2820; SOX §302/§404"),
    C("Statutory reporting and tax training programme",
      "Preventive", "Hybrid",
      "Targeted training for finance, tax, and operational staff on reporting obligations, control responsibilities, and emerging requirements with knowledge testing.",
      "Annually + Per material change",
      "CFO / Head of Tax / L&D",
      "Training completion; assessment scores; control responsibility awareness",
      "ISO 9001 §7.2; SOX entity-level"),
],

# ── R-023 Loss of stakeholder trust — missing: Incident & Crisis Management ──
"R-023": [
    C("Trust and credibility incident response",
      "Corrective", "Manual",
      "Activation playbook for events affecting stakeholder trust including stakeholder communication, narrative management, and visible remediation tracking.",
      "Per material event",
      "Chief Communications Officer / CEO",
      "Activation timeliness; stakeholder reach; sentiment recovery",
      "ISO 22361; AA1000SES"),
],

# ── R-024 Environmental incident — missing: Monitoring & Surveillance, Risk Assessment ──
"R-024": [
    C("Environmental performance monitoring",
      "Detective", "Automated",
      "Continuous environmental performance monitoring (emissions, water, waste, exceedances) with regulatory-grade telemetry, threshold alerts, and trend analysis.",
      "Continuous",
      "HSE Director / Sustainability",
      "Monitoring coverage; exceedance events; trend versus targets",
      "ISO 14001 §9; sector environmental regs"),
    C("Environmental aspects and impacts assessment",
      "Detective", "Hybrid",
      "Periodic assessment of environmental aspects and impacts driving objectives, controls, and mitigation per ISO 14001 with stakeholder input.",
      "Annually + Per change",
      "Sustainability Lead / HSE",
      "Aspects/impacts inventory; high-impact controls; objective achievement",
      "ISO 14001 §6.1.2"),
],

# ── R-025 Social licence — missing: Incident & Crisis Management ──
"R-025": [
    C("Community grievance and incident response",
      "Corrective", "Manual",
      "Documented response to community grievances, protests, and social licence events with rapid engagement, transparent communication, and resolution tracking.",
      "Per event",
      "GM Community Relations",
      "Response timeliness; grievance closure; community sentiment recovery",
      "AA1000SES; UN Guiding Principles"),
],

# ── R-026 Workplace injury — missing: Incident & Crisis Management, Investigation & Remediation, Monitoring & Surveillance ──
"R-026": [
    C("Safety performance monitoring and leading indicators",
      "Detective", "Hybrid",
      "Real-time safety dashboard tracking lagging (TRIFR, LTIFR) and leading indicators (near-miss reporting, hazard observations, critical control verifications) with monthly executive review.",
      "Continuous + Monthly review",
      "Chief Safety Officer",
      "TRIFR; near-miss reporting rate; critical control verification rate",
      "ISO 45001 §9; ICMM Critical Control"),
    C("Serious injury / fatality response and notification",
      "Corrective", "Manual",
      "Documented response to serious injury and fatality events covering family liaison, emergency response, regulator notification, scene preservation, and CEO accountability.",
      "Per SIF event",
      "Chief Safety Officer / CEO",
      "Response timeliness; regulator notification; family support effectiveness",
      "ISO 45001 §10; AU/UK Safety Acts"),
    C("Safety incident investigation and CAPA",
      "Corrective", "Hybrid",
      "Structured safety investigation using ICAM / TapRoot methodology with corrective action verification of effectiveness and learning across operations.",
      "Per material incident",
      "Chief Safety Officer / Site Managers",
      "Investigation completion; CAPA closure; verification of effectiveness; recurrence rate",
      "ISO 45001 §10; ICAM"),
],

# ── R-027 Public / customer safety — missing: Investigation & Remediation, Monitoring & Surveillance, Training & Awareness ──
"R-027": [
    C("Public safety performance monitoring",
      "Detective", "Hybrid",
      "Continuous monitoring of public safety incidents, near-misses, and complaints with thematic analysis driving design and operational improvements.",
      "Continuous + Monthly review",
      "Safety Manager",
      "Public incident volume; near-miss reporting; complaint themes",
      "ISO 45001 §9"),
    C("Customer / public safety incident investigation",
      "Corrective", "Hybrid",
      "Investigation of public / customer safety incidents with root cause analysis, regulator notification where required, and design / process improvements.",
      "Per incident",
      "Safety Manager / Quality",
      "Investigation timeliness; root cause findings; remediation effectiveness",
      "ISO 9001 §10; ISO 45001 §10"),
    C("Customer-facing staff safety training",
      "Preventive", "Hybrid",
      "Role-specific training for customer-facing staff covering aggression management, emergency response, vulnerable customer protection, and product / service safety.",
      "Annually + Onboarding",
      "Operations / L&D",
      "Training completion; assessment scores; incident reduction post-training",
      "ISO 45001 §7.2; ISO 45003"),
],

# ── R-028 Project / change failure — missing: Governance, Investigation, Monitoring ──
"R-028": [
    C("Project / programme governance and steering",
      "Directive", "Manual",
      "Documented project governance including steering committee, role accountability, decision rights, escalation, and ExCo / board reporting on material programmes.",
      "Per programme + Continuous",
      "Programme Sponsor / PMO",
      "Steering committee participation; escalation timeliness; board engagement",
      "PMI PMBOK; PRINCE2; ISO 21500"),
    C("Programme health monitoring and KPI dashboard",
      "Detective", "Hybrid",
      "Monthly programme health dashboard tracking schedule, budget, scope, benefits, risks, and quality with RAG status and trend analysis.",
      "Monthly",
      "PMO / Programme Sponsor",
      "Programmes RAG; benefits realisation; risk closure; budget variance",
      "PMI PMBOK; ISO 21500"),
    C("Project failure investigation and lessons learned",
      "Corrective", "Manual",
      "Post-implementation review on every material project covering benefits achievement, what went well, what didn't, and integration of lessons into PMO standards.",
      "Per project closure",
      "PMO",
      "PIR completion; lessons captured; PMO standard updates",
      "PMI PMBOK; ISO 21500"),
],

# ── R-029 Third party — missing: Monitoring & Surveillance, Policy & Framework ──
"R-029": [
    C("Third-party risk management framework",
      "Directive", "Hybrid",
      "Documented TPRM framework covering tiering, due diligence, contracting, ongoing monitoring, exit, and resilience with risk-tier-driven oversight cadence.",
      "Continuous + Annual review",
      "Vendor Risk / CCO",
      "Framework currency; tier coverage; concentration metrics",
      "APRA CPS 230; FCA SYSC 8; ISO 27036"),
    C("Third-party performance and risk monitoring",
      "Detective", "Hybrid",
      "Ongoing monitoring of third-party performance (SLA, financial health, ESG, security posture) and risk indicators with trigger-based reassessment.",
      "Continuous + Quarterly review",
      "Vendor Risk / Procurement",
      "SLA performance; financial health indicators; trigger events",
      "APRA CPS 230; ISO 27036"),
],

# ── R-030 Outsourcing — missing: Continuity & Recovery, Policy & Framework, Risk Assessment ──
"R-030": [
    C("Outsourcing policy and material outsourcing framework",
      "Directive", "Hybrid",
      "Board-approved outsourcing policy aligned to APRA CPS 230 / FCA SYSC 8 / DORA covering material identification, governance, due diligence, and exit.",
      "Continuous + Annual review",
      "COO / CRO",
      "Policy attestation; material outsourcing register; governance compliance",
      "APRA CPS 230 / 231; FCA SYSC 8; EU DORA"),
    C("Outsourcing risk assessment and reassessment",
      "Detective", "Hybrid",
      "Risk assessment at onboarding and periodically thereafter covering operational, security, financial, geographic, and concentration risk with mitigation tracking.",
      "Per onboarding + Annual",
      "Vendor Risk / CCO",
      "Risk assessment refresh; high-risk exposure %; mitigation closure",
      "APRA CPS 230; ISO 27036"),
    C("Outsourcing exit planning and continuity",
      "Corrective", "Manual",
      "Documented exit plan for material outsourcing arrangements covering data return, knowledge transfer, alternative provider readiness, and stressed-exit feasibility.",
      "Per material arrangement + Annual review",
      "Vendor Risk / BCM Lead",
      "Exit plans current; stressed-exit testing; alternatives identified",
      "APRA CPS 230; FCA Op Res; EU DORA"),
],

# ── R-031 Customer churn — missing: Policy & Framework ──
"R-031": [
    C("Customer experience and retention framework",
      "Directive", "Hybrid",
      "Documented customer experience framework defining standards, journey ownership, retention initiatives, and voice-of-customer integration with executive accountability.",
      "Continuous + Annual review",
      "Chief Customer Officer",
      "Framework adoption; journey ownership; VOC integration",
      "ISO 10004; ISO 9001 §9.1.2"),
],

# ── R-037 Conduct — missing: Investigation & Remediation ──
"R-037": [
    C("Conduct event investigation and customer remediation",
      "Corrective", "Manual",
      "Investigation framework for material conduct events including customer harm assessment, root cause analysis, customer remediation, and consequence application.",
      "Per material event",
      "CCO / Conduct Lead",
      "Investigation timeliness; customer reach in remediation; recurrence rate",
      "FCA Consumer Duty; ASIC RG 271; ISO 37301"),
],

# ── R-033 Money laundering — missing: Investigation & Remediation, Policy & Framework, Training ──
"R-033": [
    C("AML/CTF policy and programme framework",
      "Directive", "Hybrid",
      "Board-approved AML/CTF policy and programme aligned to FATF Recommendations and local regimes covering risk assessment, CDD, monitoring, reporting, and training.",
      "Continuous + Annual review",
      "MLRO",
      "Programme attestation; effectiveness review; regulator findings",
      "FATF Recs; AML/CTF Act; FCA FCG"),
    C("AML investigation and case management",
      "Corrective", "Hybrid",
      "Investigation framework for AML alerts and cases covering documentation standards, decisioning, SAR/SMR filing, and feedback into typologies.",
      "Per case",
      "Financial Crime Operations / MLRO",
      "Case cycle time; SAR conversion; quality review pass rate",
      "FATF Rec 20; AUSTRAC; FinCEN"),
    C("AML / sanctions training programme",
      "Preventive", "Hybrid",
      "Tiered AML / sanctions training (general, role-specific, MLRO-level) with assessment, case-based scenarios, and regulator-aligned refresher cycles.",
      "Annually + Onboarding",
      "MLRO / L&D",
      "Training completion; assessment scores; role-specific completion",
      "FATF Recs; AML/CTF Rules"),
],

# ── R-034 Bribery — missing: Investigation & Remediation, Monitoring & Surveillance ──
"R-034": [
    C("ABC monitoring and surveillance",
      "Detective", "Hybrid",
      "Surveillance over high-risk ABC indicators including unusual hospitality, gift register exceptions, intermediary payments, and political contributions with alert investigation.",
      "Continuous + Quarterly review",
      "CCO / Compliance Surveillance",
      "Alerts generated; investigation outcomes; pattern indicators",
      "ISO 37001; FCPA; UK Bribery Act"),
    C("Bribery investigation and consequence management",
      "Corrective", "Manual",
      "Investigation framework for bribery allegations with skilled investigators, regulator engagement protocols, and consistent consequences regardless of seniority.",
      "Per allegation",
      "GC / Investigations Lead",
      "Investigation cycle time; substantiation rate; consequence consistency",
      "ISO 37001; FCPA Resource Guide"),
],

# ── R-035 External fraud — missing: Due Diligence & Onboarding, Risk Assessment ──
"R-035": [
    C("Customer / counterparty fraud risk screening at onboarding",
      "Preventive", "Hybrid",
      "Fraud-specific risk screening at onboarding (identity verification, device intelligence, velocity checks, watchlists) with risk-tier-based EDD on suspicious applications.",
      "Per onboarding",
      "Fraud Operations / Onboarding",
      "Onboarding fraud rate; EDD rate; declined applications",
      "FATF Rec 10; FFIEC; PSD2 SCA"),
    C("External fraud risk assessment",
      "Detective", "Hybrid",
      "Annual external fraud risk assessment covering scams, payment fraud, identity, and emerging typologies with control adequacy review and treatment planning.",
      "Annually + Event-driven",
      "Head of Fraud",
      "Risk assessment refresh; emerging typology coverage; treatment closure",
      "ACFE; COSO Fraud Risk Mgmt"),
],

# ── R-039 Data quality — missing: Access, Continuity, Engineering, Incident, Risk Assessment ──
"R-039": [
    C("Data access governance and stewardship roles",
      "Preventive", "Hybrid",
      "Role-based data access governance with stewards accountable for data quality, definitions, access decisions, and quality issue resolution.",
      "Continuous + Quarterly stewardship review",
      "CDO",
      "Stewardship coverage; access review completion; quality issue closure by steward",
      "DAMA-DMBOK; BCBS 239"),
    C("Data platform continuity and recovery",
      "Corrective", "Hybrid",
      "Continuity and recovery for data platforms covering point-in-time recovery, integrity validation post-recovery, and tested data pipeline failover.",
      "Continuous + Quarterly testing",
      "Data Platform Lead / SRE",
      "RPO/RTO achieved on data; integrity post-recovery; pipeline failover tests",
      "ISO 22301; SOC 2 A1.2"),
    C("Data engineering standards and pipeline integrity",
      "Preventive", "Hybrid",
      "Engineering standards for data pipelines covering schema enforcement, contract testing, lineage capture, and integrity validation at each stage.",
      "Continuous",
      "Data Engineering Lead",
      "Schema test coverage; lineage completeness; integrity check failures",
      "DAMA-DMBOK; ISO/IEC 25012"),
    C("Data quality incident response",
      "Corrective", "Hybrid",
      "Defined process for data quality incidents covering detection, downstream impact assessment, customer / regulator notification, remediation, and root cause learning.",
      "Per incident",
      "CDO / Data Quality Lead",
      "Detection-to-resolution time; downstream impact contained; lessons learned closure",
      "BCBS 239; ISO 27035"),
    C("Data risk assessment and CDE prioritisation",
      "Detective", "Hybrid",
      "Periodic data risk assessment identifying critical data elements (CDEs), criticality drivers, quality risks, and prioritisation of monitoring and remediation investment.",
      "Annually + Per material change",
      "CDO",
      "CDE coverage; risk-driven monitoring; remediation prioritisation",
      "BCBS 239; DAMA-DMBOK"),
],

# ── R-040 Model / AI — missing: Access, Continuity, Engineering, Incident ──
"R-040": [
    C("Model and AI access governance",
      "Preventive", "Hybrid",
      "Access governance for models, training data, deployment pipelines, and AI tools covering least privilege, segregation of duties (development / approval / deployment), and audit logging.",
      "Continuous",
      "Head of AI / CISO",
      "Access events; SoD breaches; audit log coverage",
      "NIST 800-53 AC; ISO/IEC 42001"),
    C("Model and AI service continuity",
      "Corrective", "Hybrid",
      "Continuity arrangements for AI / model services covering fallback to human / rules-based decisions, model version rollback, and graceful degradation under load or failure.",
      "Continuous + Per major release",
      "Head of ML / SRE",
      "Fallback activation tests; rollback success; degraded-mode availability",
      "ISO 22301; ISO/IEC 42001; SOC 2 A1.2"),
    C("AI / model engineering standards and reproducibility",
      "Preventive", "Hybrid",
      "Engineering standards for AI / ML covering reproducibility, version control of code and data, evaluation harness, deployment gates, and observability instrumentation.",
      "Continuous",
      "Head of ML / Platform Engineering",
      "Reproducibility tests; deployment gate failure rate; observability coverage",
      "Google MLOps; ISO/IEC 23053; ISO/IEC 42001"),
    C("AI / model incident and harm response",
      "Corrective", "Hybrid",
      "Documented response to AI / model incidents (degradation, bias, harmful outputs) covering rapid detection, containment, customer remediation, regulator notification, and learning.",
      "Per incident",
      "Head of AI / CCO",
      "Detection-to-containment time; customer remediation; regulator notifications",
      "NIST AI RMF; EU AI Act; ISO 27035"),
],

}
