"""
Universal risk descriptions for each of the 40 risk themes.
Rendered in the Risk Hierarchy tab (formerly Themes Index).
"""

UNIVERSAL_DESCRIPTIONS = {
    "R-001": "The strategic plan fails to deliver intended competitive position, market share, or value due to flawed strategic choices, weak execution, or inadequate response to changing market conditions.",
    "R-002": "A new technology, business model, or market entrant disrupts the organisation's value proposition, eroding revenue, margins, or relevance faster than the organisation can adapt.",
    "R-003": "A merger, acquisition, joint venture, or major investment fails to deliver expected synergies, value, or strategic outcomes due to flawed deal logic, integration failure, or unforeseen liabilities.",
    "R-004": "The organisation cannot meet near-term financial obligations due to cash flow timing mismatches, working capital pressures, funding constraints, or sudden withdrawal of credit facilities.",
    "R-005": "An over-reliance on one or a few customers creates material exposure, with customer loss or contract change triggering revenue, profit, or operational impacts.",
    "R-006": "An employee, contractor, or insider misappropriates funds, assets, or information for personal benefit through theft, falsification, collusion, or abuse of authority.",
    "R-007": "Movements in foreign exchange, interest rates, or commodity prices adversely affect financial results, asset values, or competitive position beyond the organisation's risk appetite.",
    "R-008": "A critical operational process fails or degrades, causing service disruption, customer impact, financial loss, or regulatory consequences.",
    "R-009": "A critical asset, piece of equipment, or infrastructure component fails or becomes unavailable, disrupting operations and requiring emergency response or replacement.",
    "R-010": "Operational capacity (workforce, facility, system) cannot meet sustained or peak demand, resulting in lost revenue, customer attrition, or service quality degradation.",
    "R-011": "A product, service, or output fails to meet quality standards, leading to customer harm, recall, complaints, brand damage, or regulatory action.",
    "R-012": "Departure of executives, leaders, or specialists with critical knowledge or relationships disrupts operations, strategy, or stakeholder confidence.",
    "R-013": "The organisation cannot attract, develop, or retain workforce capability needed for current or future operations, creating capability gaps and execution risk.",
    "R-014": "Workplace culture, leadership behaviour, or individual conduct creates harm, regulatory exposure, reputational damage, or talent attrition.",
    "R-015": "An external or insider cyber attack compromises confidentiality, integrity, or availability of systems and data, with potential operational, financial, regulatory, and reputational consequences.",
    "R-016": "Data is lost, corrupted, or disclosed without authorisation through human error, system failure, or malicious action, breaching privacy obligations and exposing affected parties to harm.",
    "R-017": "A critical system or technology platform becomes unavailable or impaired, disrupting business processes, customer service, and revenue generation.",
    "R-018": "Aging technology, accumulated technical debt, or vendor end-of-life events create operational, security, and capability risks that compound over time.",
    "R-019": "The organisation fails to comply with applicable laws, regulations, prudential standards, or licence conditions, resulting in fines, restrictions, or loss of authorisation to operate.",
    "R-020": "A claim, lawsuit, contractual dispute, or class action exposes the organisation to financial liability, business disruption, and reputational damage.",
    "R-021": "The organisation fails to identify, plan for, or implement regulatory changes in time, leading to non-compliance, breach reporting, or competitive disadvantage.",
    "R-022": "A negative public event (incident, scandal, leak, social media crisis) damages brand value and stakeholder perception, with knock-on effects to customers, talent, and investors.",
    "R-023": "Erosion of trust among customers, investors, regulators, communities, or employees reduces willingness to engage with or support the organisation.",
    "R-024": "An environmental incident (spill, emission, contamination) or compliance failure causes ecological harm, regulatory action, remediation costs, and reputational damage.",
    "R-025": "Loss of community support, indigenous opposition, or NGO / activist pressure constrains operations, delays projects, or forces business model change.",
    "R-026": "A worker, contractor, or visitor suffers serious injury or fatality due to workplace hazards, with consequences for the affected person, regulatory penalties, and organisational impact.",
    "R-027": "A customer, patient, beneficiary, or member of the public is harmed by the organisation's products, services, premises, or activities.",
    "R-028": "A material project or change initiative fails to deliver scope, time, cost, benefits, or quality objectives, with financial, operational, and reputational consequences.",
    "R-029": "A critical supplier or vendor fails to perform, becomes unavailable, or creates concentration risk that disrupts the organisation's ability to operate.",
    "R-030": "Outsourced functions or third-party arrangements fail due to weak governance, inadequate oversight, or third-party conduct, with impacts attributable to the organisation.",
    "R-031": "Customers leave the organisation in significant numbers due to dissatisfaction, competitive offer, conduct events, or trust erosion, eroding revenue and brand value.",
    "R-032": "Macroeconomic shifts, geopolitical events, or global market shocks affect demand, costs, supply chains, capital availability, or operating environment in ways the organisation cannot fully control.",
    "R-033": "The organisation is used to launder money, evade sanctions, or finance terrorism due to inadequate customer due diligence, transaction monitoring, or sanctions screening.",
    "R-034": "Bribery, corruption, or improper payments — by or to staff, agents, or third parties — expose the organisation to regulatory, legal, and reputational consequences.",
    "R-035": "External actors defraud the organisation through scams, identity fraud, payment fraud, or organised crime, causing financial loss and customer harm.",
    "R-036": "The organisation cannot maintain critical operations through disruption (cyber, natural, supply chain, third-party, geopolitical) within tolerable impact thresholds.",
    "R-037": "Sales practices, product design, pricing, or market behaviour cause customer harm or undermine market integrity, breaching conduct standards and regulator expectations.",
    "R-038": "Errors, omissions, or delays in statutory financial, tax, prudential, or sustainability reporting result in regulatory action, restatements, or stakeholder loss of confidence.",
    "R-039": "Data quality, integrity, lineage, or stewardship failures undermine decisions, reporting, regulatory submissions, and AI / analytics outputs.",
    "R-040": "Models or AI / ML systems produce flawed, biased, or harmful outputs due to inadequate validation, monitoring, or governance, with operational, regulatory, and customer impacts.",
}
