"""Batch 4: R-019 through R-027 (Legal & Regulatory, Reputational, Env & Social, H&S)"""

BATCH_4 = [
    # ════════════════════════════════════════════════════════════════
    # DOMAIN: LEGAL & REGULATORY (3 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-019",
        "domain": "Legal and Regulatory",
        "theme": "Regulatory non-compliance / sanction",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Non-compliance with professional standards or regulatory obligations",
                "description": "Failure to comply with professional standards (e.g. legal practice rules, audit standards, AML obligations) results in regulator sanction.",
                "causes_people": "Awareness gaps among partners; pressures on compliance team",
                "causes_process": "Compliance monitoring weak; CPD / training inconsistent",
                "causes_systems": "AML / KYC systems immature; conflicts checking weak",
                "causes_external": "Regulatory change; regulator focus on professional services AML",
                "consequence": "Fines, practice condition restrictions, partner deregistration, reputational damage, possible criminal proceedings.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with reputational",
                "owner_suggested": "Chief Compliance Officer / Managing Partner",
            },
            "FINS": {
                "title": "Material breach of prudential, conduct, or financial-crime regulation",
                "description": "Material breach of regulatory obligations across prudential, conduct, AML, sanctions, privacy, or product domains results in enforcement action.",
                "causes_people": "Risk and compliance capacity stretched; conduct pressures",
                "causes_process": "Three-lines-of-defence weak; obligations register incomplete",
                "causes_systems": "Compliance monitoring systems immature; regulatory reporting prone to error",
                "causes_external": "Regulator priorities shifting; new regulation adding obligations",
                "consequence": "Substantial fines, enforceable undertakings, individual accountability action, share price impact, possible licence conditions.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe financial and reputational impact",
                "owner_suggested": "Chief Risk Officer / Chief Compliance Officer",
            },
            "TECH": {
                "title": "Non-compliance with privacy, AI, sector-specific, or international regulation",
                "description": "Failure to comply with privacy, emerging AI regulation, sector-specific or cross-border requirements (GDPR, CCPA, EU AI Act) results in fines and operational restrictions.",
                "causes_people": "Compliance capability limited at scale; cross-functional alignment weak",
                "causes_process": "Privacy by design immature; regulatory scanning informal",
                "causes_systems": "Data handling systems not configurable for jurisdictional differences",
                "causes_external": "Rapidly evolving privacy and AI regulation across jurisdictions",
                "consequence": "Fines (potentially substantial — e.g. GDPR up to 4% global revenue), service restrictions, customer trust loss, sales-cycle impact.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with financial and customer impact",
                "owner_suggested": "Privacy Officer / General Counsel",
            },
            "HCAR": {
                "title": "Non-compliance with clinical, accreditation, or operational regulation",
                "description": "Failure to comply with clinical standards, accreditation requirements, AHPRA / registrar obligations, privacy, or workplace requirements results in regulatory action.",
                "causes_people": "Clinician compliance variable; managerial oversight gaps",
                "causes_process": "Accreditation preparation reactive; clinical governance immature",
                "causes_systems": "Compliance, incident, and credentialing systems siloed",
                "causes_external": "Regulator focus areas shifting; sector reviews and royal commissions",
                "consequence": "Loss of accreditation, funding consequences, registrar action against clinicians, regulator notifications, reputational impact.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe financial impact",
                "owner_suggested": "Chief Medical Officer / Compliance Officer",
            },
            "RETL": {
                "title": "Non-compliance with consumer law, food safety, employment, or industry regulation",
                "description": "Failure to comply with Australian Consumer Law (or equivalent), food safety, employment / wage law, advertising standards, or industry-specific requirements results in enforcement.",
                "causes_people": "Compliance capability stretched at scale; store team awareness gaps",
                "causes_process": "Compliance monitoring at store level inconsistent; supplier compliance variable",
                "causes_systems": "Compliance and quality systems not joined up",
                "causes_external": "Regulator focus on retail wage compliance, food safety, environmental claims",
                "consequence": "Fines, court-enforceable undertakings, recalls, mass remediation costs (e.g. wage underpayments), reputational damage.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with financial and reputational impact",
                "owner_suggested": "General Counsel / Chief Compliance Officer",
            },
            "INDU": {
                "title": "Non-compliance with safety, environmental, or critical-infrastructure regulation",
                "description": "Failure to comply with WHS / safety, environmental protection, anti-bribery, modern slavery, or critical-infrastructure obligations results in enforcement.",
                "causes_people": "Site-level compliance variable; supervisor capability gaps",
                "causes_process": "Compliance integration with site operations weak; subcontractor oversight limited",
                "causes_systems": "Compliance systems siloed from operational systems",
                "causes_external": "Regulator focus on industrial harm, environment, and supply-chain ethics",
                "consequence": "Fines, prosecutions (corporate and individual), loss of operating licence, contract loss with major customers requiring compliance.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe operational and reputational impact",
                "owner_suggested": "Chief Risk Officer / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Non-compliance with sector regulation, funder requirements, or charity law",
                "description": "Failure to comply with charity law, funder agreements, child safety / safeguarding, privacy, or sector-specific regulation results in enforcement and funding consequences.",
                "causes_people": "Limited compliance resource; reliance on volunteers without training",
                "causes_process": "Compliance monitoring informal; safeguarding processes immature",
                "causes_systems": "Compliance and safeguarding case systems limited",
                "causes_external": "Regulator focus on safeguarding, governance, and beneficiary protection",
                "consequence": "Funder action, regulator action (e.g. ACNC), board accountability, loss of trust, possible criminal proceedings.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with severe reputational impact",
                "owner_suggested": "CEO / Compliance Officer",
            },
        },
    },

    {
        "id": "R-020",
        "domain": "Legal and Regulatory",
        "theme": "Litigation, claim, or contractual dispute",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Professional indemnity claim or commercial dispute",
                "description": "Client commences action alleging negligent advice, error, or omission, or significant commercial dispute over fees or scope.",
                "causes_people": "Time pressure compromising review; complex matters with limited supervision",
                "causes_process": "Engagement letters weak; scope creep undocumented; quality review inconsistent",
                "causes_systems": "Matter file documentation weak; conflicts checking imperfect",
                "causes_external": "Claims environment more litigious; class action firms targeting professionals",
                "consequence": "PI insurance impact (cost and excess), management distraction, reputational damage, possible partner accountability.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — combined with reputational impact",
                "owner_suggested": "Risk Partner / General Counsel",
            },
            "FINS": {
                "title": "Customer litigation, class actions, or contractual disputes",
                "description": "Customer-led litigation (including class actions) or contractual disputes alleging mis-selling, breach of contract, or unfair conduct.",
                "causes_people": "Front-line conduct issues; sales incentive misalignment",
                "causes_process": "Product governance weak; customer outcome monitoring limited",
                "causes_systems": "Customer interaction logging weak; advice quality monitoring immature",
                "causes_external": "Active class action sector; regulator-led remediation programs spawning litigation",
                "consequence": "Substantial settlement / judgment costs, remediation programs, regulator action, reputational damage, share-price impact.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — combined with reputational impact",
                "owner_suggested": "General Counsel / Chief Risk Officer",
            },
            "TECH": {
                "title": "Customer dispute, IP litigation, or contractual claim",
                "description": "Customer dispute over service quality, IP litigation (patent or copyright), or contractual claims (breach of SLA, performance) result in significant cost and distraction.",
                "causes_people": "Sales over-promising; engineering capacity limiting delivery",
                "causes_process": "Contract negotiation weak in growth phase; SLA monitoring weak",
                "causes_systems": "Code provenance and licensing tracking weak; SLA reporting limited",
                "causes_external": "Patent troll activity; competitor IP enforcement; class action environment",
                "consequence": "Settlement / judgment costs, distraction from core, IP-licensing implications, customer confidence impact.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Financial — combined with operational distraction",
                "owner_suggested": "General Counsel / CEO",
            },
            "HCAR": {
                "title": "Medical negligence claim, patient action, or contractual dispute",
                "description": "Patient-led legal action alleging clinical negligence, harm, or breach of duty, or contractual disputes with payers.",
                "causes_people": "Clinical fatigue; communication breakdown with patients and families",
                "causes_process": "Clinical incident investigation weak; documentation inconsistent",
                "causes_systems": "Clinical systems with weak audit trail; patient communication systems limited",
                "causes_external": "Class action environment; coronial inquiries; payer disputes",
                "consequence": "Compensation costs, MDO premium impact, registrar action, reputational damage.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — combined with reputational impact",
                "owner_suggested": "General Counsel / Chief Medical Officer",
            },
            "RETL": {
                "title": "Consumer law claim, product liability, or supplier dispute",
                "description": "Customer claims under consumer law, product liability litigation, or significant supplier disputes.",
                "causes_people": "Customer service handling of complaints inconsistent",
                "causes_process": "Returns and refund processes weak; supplier contracts not enforcing standards",
                "causes_systems": "Customer complaint and product-liability data fragmented",
                "causes_external": "Class actions on misleading claims (e.g. ESG, country of origin); product safety regulator action",
                "consequence": "Settlement / judgment costs, recall and remediation, brand damage, regulator action.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Financial — combined with reputational",
                "owner_suggested": "General Counsel",
            },
            "INDU": {
                "title": "Contract dispute, project claim, or third-party litigation",
                "description": "Major project disputes (delay, scope, payment), customer warranty claims, or third-party litigation (community, environmental, employee).",
                "causes_people": "Project commercial discipline weak; subcontractor oversight gaps",
                "causes_process": "Variation management weak; documentation inconsistent",
                "causes_systems": "Project controls and document management weak",
                "causes_external": "Adverse weather affecting projects; commodity moves changing economics; community opposition",
                "consequence": "Substantial settlement / judgment costs, contract reputation impact, capital tied up in disputes.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — direct and indirect",
                "owner_suggested": "General Counsel / Chief Commercial Officer",
            },
            "PUBL": {
                "title": "Litigation from beneficiaries, stakeholders, or contractual disputes",
                "description": "Litigation from beneficiaries (including historical abuse claims), employment disputes, or contractual claims with funders or partners.",
                "causes_people": "Safeguarding breaches in past or present; employment matters not handled well",
                "causes_process": "Safeguarding processes immature historically; investigations weak",
                "causes_systems": "Historical record-keeping incomplete; safeguarding systems limited",
                "causes_external": "Royal commission / sector reviews surfacing historical issues; class action environment",
                "consequence": "Substantial compensation (often historical-claim related), funder withdrawal, reputational devastation, board accountability.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with severe financial impact",
                "owner_suggested": "General Counsel / CEO",
            },
        },
    },

    {
        "id": "R-021",
        "domain": "Legal and Regulatory",
        "theme": "Failure to keep pace with regulatory change",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Failure to keep pace with regulatory change affecting professional services",
                "description": "Insufficient horizon scanning and adoption of changes to professional standards, AML, privacy, and tax regulation.",
                "causes_people": "Compliance capacity limited; partners under-engaged on regulatory change",
                "causes_process": "Regulatory scanning ad-hoc; impact assessment slow",
                "causes_systems": "Obligations register incomplete or outdated",
                "causes_external": "Frequent regulatory change in tax, privacy, AML; cross-border obligations",
                "consequence": "Inadvertent non-compliance, late adoption costs, client harm if advice is outdated.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Regulatory — combined with reputational",
                "owner_suggested": "Chief Compliance Officer",
            },
            "FINS": {
                "title": "Failure to keep pace with prudential, conduct, AI, climate, and privacy regulation",
                "description": "Continuous regulatory change across multiple domains creates risk of late, partial, or inconsistent implementation.",
                "causes_people": "Regulatory change capacity overstretched; cross-functional coordination weak",
                "causes_process": "Change management for regulation immature; programme governance weak",
                "causes_systems": "Obligations register fragmented; regulatory reporting system change cycles long",
                "causes_external": "High volume of concurrent regulatory change (climate, AI, prudential reform, conduct)",
                "consequence": "Late or partial implementation creating non-compliance, regulator engagement, remediation costs.",
                "inh_likelihood": 5, "inh_impact": 4,
                "impact_rationale": "Regulatory — material and recurring",
                "owner_suggested": "Chief Compliance Officer",
            },
            "TECH": {
                "title": "Failure to keep pace with privacy, AI, and cross-border regulation",
                "description": "Rapidly evolving and divergent privacy, AI, and platform regulation across jurisdictions creates compliance complexity and risk of late adoption.",
                "causes_people": "Compliance capability limited at scale; product teams not regulator-aware",
                "causes_process": "Regulatory scanning informal; jurisdictional variation handling weak",
                "causes_systems": "Product systems not configurable for jurisdictional rules",
                "causes_external": "EU AI Act; state-level US privacy regulation; sector-specific AI rules",
                "consequence": "Inability to enter / serve markets, fines, sales-cycle friction with enterprise customers.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Regulatory — combined with strategic impact",
                "owner_suggested": "General Counsel / Privacy Officer",
            },
            "HCAR": {
                "title": "Failure to keep pace with clinical, accreditation, and privacy regulation",
                "description": "Continuous evolution in clinical standards, accreditation requirements, privacy, and sector-specific regulation creates implementation risk.",
                "causes_people": "Clinical governance capacity stretched; CPD / training cycles slow",
                "causes_process": "Regulatory scanning weak; accreditation preparation reactive",
                "causes_systems": "Clinical guidelines and obligations registers fragmented",
                "causes_external": "Sector reviews, royal commissions, evolving clinical standards",
                "consequence": "Late or partial compliance, accreditation risk, regulator action, clinical risk.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with patient safety",
                "owner_suggested": "Chief Medical Officer / Compliance Officer",
            },
            "RETL": {
                "title": "Failure to keep pace with consumer, environmental, employment, and product regulation",
                "description": "Continuous change in consumer law, environmental claims, modern slavery, food safety, and employment regulation creates compliance risk.",
                "causes_people": "Compliance capacity stretched; supplier compliance hard to verify",
                "causes_process": "Regulatory scanning informal; supplier audit immature",
                "causes_systems": "Compliance systems not surfacing all obligations",
                "causes_external": "Regulator focus on greenwashing, modern slavery, payments protection",
                "consequence": "Fines, recalls, reputational impact, supplier dispute risk.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Regulatory — combined with reputational",
                "owner_suggested": "General Counsel / Chief Compliance Officer",
            },
            "INDU": {
                "title": "Failure to keep pace with safety, environmental, climate, and modern-slavery regulation",
                "description": "Continuous evolution of safety, environmental, climate-disclosure, and supply-chain ethics regulation creates compliance and reporting risk.",
                "causes_people": "Compliance capability decentralised across sites; capability gaps",
                "causes_process": "Regulatory scanning ad-hoc; site-level adoption inconsistent",
                "causes_systems": "ESG and compliance systems immature",
                "causes_external": "Climate-related disclosure standards (e.g. ISSB / TCFD); modern slavery; emissions reporting",
                "consequence": "Fines, contract loss with customers requiring compliance, ESG ratings impact, reputational damage.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with strategic",
                "owner_suggested": "Chief Risk Officer / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Failure to keep pace with charity, safeguarding, and sector regulation",
                "description": "Continuous evolution of charity / governance regulation, safeguarding requirements, and sector-specific rules creates compliance complexity.",
                "causes_people": "Compliance resource limited; volunteer-led environments",
                "causes_process": "Regulatory scanning informal; cross-program coordination weak",
                "causes_systems": "Compliance and safeguarding systems immature",
                "causes_external": "Charity regulator (e.g. ACNC) focus areas evolving; safeguarding rule changes",
                "consequence": "Funder action, regulator action, board accountability, reputational impact.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Regulatory — combined with funding consequences",
                "owner_suggested": "Compliance Officer / CEO",
            },
        },
    },

    # ════════════════════════════════════════════════════════════════
    # DOMAIN: REPUTATIONAL (2 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-022",
        "domain": "Reputational",
        "theme": "Brand damage from negative public event",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Negative public event damaging firm reputation",
                "description": "Public incident — partner misconduct, client controversy, scandal involving a high-profile matter — generates negative coverage and damages firm reputation.",
                "causes_people": "Partner public conduct; controversial matters accepted without reputational analysis",
                "causes_process": "Reputation review process for new clients/matters weak",
                "causes_systems": "Social listening immature",
                "causes_external": "Activist scrutiny; client controversy; whistleblower disclosure",
                "consequence": "Talent attraction issues, client losses, partner exits, possible regulator scrutiny.",
                "inh_likelihood": 2, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with financial",
                "owner_suggested": "Managing Partner / Marketing Director",
            },
            "FINS": {
                "title": "Public event causing material brand damage",
                "description": "Significant public incident — IT outage, scandal, customer harm event, conduct revelation — damages brand and customer trust.",
                "causes_people": "Crisis communications capability limited; spokesperson capability gaps",
                "causes_process": "Crisis management procedures untested; social media response slow",
                "causes_systems": "Social listening and reputation monitoring immature",
                "causes_external": "Active media environment for financial-services scrutiny; activist investor pressure",
                "consequence": "Customer attrition, share price impact, regulator engagement, executive accountability action.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with customer and financial impact",
                "owner_suggested": "Chief Communications Officer / CEO",
            },
            "TECH": {
                "title": "Public incident damaging brand and customer trust",
                "description": "Public event — outage, security breach, controversial product decision, leadership scandal — damages brand and customer / employee trust.",
                "causes_people": "Founder / executive social media presence; crisis comms capability limited",
                "causes_process": "Crisis playbooks immature; cross-functional alignment weak",
                "causes_systems": "Social listening and brand monitoring limited",
                "causes_external": "Active tech-sector scrutiny; viral social moment; activist customer / employee actions",
                "consequence": "Customer trust loss, churn, talent attraction issues, valuation impact.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with financial impact",
                "owner_suggested": "Head of Marketing / CEO",
            },
            "HCAR": {
                "title": "Public event damaging organisational reputation",
                "description": "Adverse clinical incident, infection outbreak, abuse allegation, or other public event damages reputation and trust.",
                "causes_people": "Clinical leadership communication; staff handling of media",
                "causes_process": "Crisis communications and stakeholder management weak; family communication inconsistent",
                "causes_systems": "Reputation monitoring limited",
                "causes_external": "Coronial findings; royal commission outcomes; investigative journalism",
                "consequence": "Patient / referrer confidence loss, accreditation impact, recruitment difficulty, funding consequences.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with patient and operational impact",
                "owner_suggested": "Chief Communications Officer / CEO",
            },
            "RETL": {
                "title": "Brand damage from product, supplier, or marketing controversy",
                "description": "Negative event — product safety, supplier ethics, marketing controversy, store-level conduct — generates viral negative coverage.",
                "causes_people": "Marketing decisions made quickly; supplier oversight gaps",
                "causes_process": "Content approval weak; supplier due diligence variable",
                "causes_systems": "Social listening reactive rather than proactive",
                "causes_external": "Activist consumer scrutiny; investigative journalism; influencer-driven backlash",
                "consequence": "Sales decline, customer boycott, supplier renegotiations, possible regulator interest.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with sales impact",
                "owner_suggested": "Chief Communications Officer / Chief Marketing Officer",
            },
            "INDU": {
                "title": "Brand damage from safety, environmental, or community incident",
                "description": "Major safety incident, environmental release, community impact event, or supply-chain ethics scandal generates significant negative coverage.",
                "causes_people": "Site-level communications capability limited; community relations under-resourced",
                "causes_process": "Crisis management procedures inconsistent across sites",
                "causes_systems": "Stakeholder mapping and engagement systems immature",
                "causes_external": "ESG-focused investor scrutiny; activist groups; community organisations",
                "consequence": "Loss of social licence, contract loss, ESG ratings impact, regulator scrutiny.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with social licence and financial impact",
                "owner_suggested": "Head of External Affairs / CEO",
            },
            "PUBL": {
                "title": "Public event damaging trust in mission or governance",
                "description": "Safeguarding incident, governance scandal, financial mismanagement claim, or campaign controversy damages public trust in the organisation.",
                "causes_people": "Governance and trustee capability variable; communications capability limited",
                "causes_process": "Investigation processes immature; whistleblower management weak",
                "causes_systems": "Reputation and stakeholder monitoring immature",
                "causes_external": "Investigative journalism; political scrutiny; donor activism",
                "consequence": "Donor / funder withdrawal, mission delivery impact, board accountability, possible regulator action.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with funding and mission impact",
                "owner_suggested": "CEO / Director of Communications",
            },
        },
    },

    {
        "id": "R-023",
        "domain": "Reputational",
        "theme": "Loss of stakeholder trust / credibility",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Erosion of stakeholder trust and credibility",
                "description": "Gradual erosion of credibility — through inconsistent quality, poor communication, ESG positioning lapses — undermines firm standing.",
                "causes_people": "Inconsistent client experience across partners; weak KAM",
                "causes_process": "Stakeholder engagement informal; issue-tracking limited",
                "causes_systems": "Client feedback and stakeholder data fragmented",
                "causes_external": "Increased client demands for ESG, diversity, transparency; market consolidation",
                "consequence": "Slow decline in win rates, talent attraction difficulty, reduced referrals.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — gradual financial impact",
                "owner_suggested": "Marketing Director / Managing Partner",
            },
            "FINS": {
                "title": "Erosion of customer, regulator, or shareholder trust",
                "description": "Cumulative impact of incidents, conduct issues, or perceived shortcomings erodes stakeholder trust over time.",
                "causes_people": "Crisis management capability uneven; cross-functional alignment weak",
                "causes_process": "Customer outcome monitoring weak; ESG strategy delivery inconsistent",
                "causes_systems": "Reputation, customer satisfaction, and ESG data fragmented",
                "causes_external": "Active scrutiny from regulators, activists, and customers post-Royal Commission environment",
                "consequence": "Customer attrition, regulator skepticism, share-price multiple impact, talent challenges.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with strategic and financial impact",
                "owner_suggested": "CEO / Chief Communications Officer",
            },
            "TECH": {
                "title": "Erosion of customer, employee, or investor trust",
                "description": "Cumulative impact of outages, incidents, controversial decisions, or culture issues erodes stakeholder trust.",
                "causes_people": "Founder communication style; culture under scaling pressure",
                "causes_process": "Customer feedback loops weak; ESG / DEI delivery inconsistent",
                "causes_systems": "Stakeholder feedback and reputation systems limited",
                "causes_external": "Tech-sector scrutiny; investor focus on governance; employee activism",
                "consequence": "Increased churn, talent attraction harder, valuation impact, sales-cycle friction.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with strategic impact",
                "owner_suggested": "CEO / Chief People Officer",
            },
            "HCAR": {
                "title": "Erosion of trust with patients, community, regulators, and clinicians",
                "description": "Cumulative impact of incidents, communication issues, or perceived shortcomings erodes trust with key stakeholders.",
                "causes_people": "Clinical leadership communication; family-engagement capability variable",
                "causes_process": "Stakeholder feedback weak; complaints handling inconsistent",
                "causes_systems": "Patient experience and stakeholder data fragmented",
                "causes_external": "Sector-wide scrutiny; royal commissions; community expectations evolving",
                "consequence": "Referrer / patient attrition, accreditation difficulty, recruitment challenges, funding consequences.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with strategic and operational impact",
                "owner_suggested": "CEO / Chief Communications Officer",
            },
            "RETL": {
                "title": "Erosion of customer trust and brand credibility",
                "description": "Cumulative impact of price perception, quality issues, ESG missteps, or service failures erodes brand trust.",
                "causes_people": "Front-line service quality variable; marketing decisions opportunistic",
                "causes_process": "Customer feedback loops weak; ESG strategy delivery inconsistent",
                "causes_systems": "Customer experience and brand data fragmented",
                "causes_external": "Activist consumers; ESG-focused customer behaviour",
                "consequence": "Customer attrition to competitors, reduced repeat purchase, mark-down pressure.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with sales decline",
                "owner_suggested": "Chief Marketing Officer",
            },
            "INDU": {
                "title": "Erosion of social licence and stakeholder trust",
                "description": "Gradual erosion of social licence to operate through cumulative environmental, community, safety, or supply-chain issues.",
                "causes_people": "Community relations capability under-resourced; site leadership variable",
                "causes_process": "Stakeholder engagement informal; ESG strategy variable across sites",
                "causes_systems": "Stakeholder feedback and ESG data fragmented",
                "causes_external": "ESG-focused investors; activist organisations; community expectations evolving",
                "consequence": "Permitting difficulties, contract loss, ESG rating impact, gradual financial cost.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with strategic impact",
                "owner_suggested": "Head of External Affairs / CEO",
            },
            "PUBL": {
                "title": "Erosion of trust with beneficiaries, donors, and community",
                "description": "Gradual erosion of trust through governance issues, mission drift, communications failures, or perceived effectiveness gaps.",
                "causes_people": "Communications and engagement capability limited; trustee turnover",
                "causes_process": "Outcomes measurement weak; stakeholder feedback informal",
                "causes_systems": "Outcome and stakeholder data fragmented",
                "causes_external": "Sector competition for donor attention; declining trust in institutions",
                "consequence": "Donor decline, beneficiary disengagement, government partnership difficulty, mission impact.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with funding consequences",
                "owner_suggested": "CEO / Director of Communications",
            },
        },
    },

    # ════════════════════════════════════════════════════════════════
    # DOMAIN: ENVIRONMENTAL & SOCIAL (2 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-024",
        "domain": "Environmental and Social",
        "theme": "Environmental incident or compliance failure",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Environmental footprint, climate disclosure, or sustainability commitments",
                "description": "Failure to manage and report on environmental footprint, or to deliver on sustainability commitments, creates regulatory and reputational risk.",
                "causes_people": "Sustainability capability limited; partner buy-in variable",
                "causes_process": "Emissions measurement immature; supplier sustainability assessment limited",
                "causes_systems": "ESG / emissions tracking systems limited",
                "causes_external": "Climate-related disclosure standards (TCFD / ISSB); client and recruit expectations",
                "consequence": "Reputational impact, talent attraction difficulty, possible regulatory action under disclosure rules.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "Environmental — combined with reputational",
                "owner_suggested": "Head of Sustainability / Managing Partner",
            },
            "FINS": {
                "title": "Climate-related and environmental risk in lending, investments, and operations",
                "description": "Climate-related transition and physical risk in customer portfolios, investment portfolios, and own operations creates financial and disclosure risk.",
                "causes_people": "Specialist climate/ESG capability stretched",
                "causes_process": "Climate scenario analysis immature; ESG integration in credit / investment decisions inconsistent",
                "causes_systems": "Climate data fragmented; scenario analysis tooling limited",
                "causes_external": "TCFD / ISSB / sector-specific disclosure rules; physical climate events",
                "consequence": "Regulator action, capital impact, customer / investment portfolio impairments, reputational impact.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Regulatory — combined with financial and reputational",
                "owner_suggested": "Chief Sustainability Officer / CRO",
            },
            "TECH": {
                "title": "Carbon footprint, sustainability commitments, and disclosure",
                "description": "Cloud-related carbon footprint, hardware lifecycle impacts, and sustainability commitments create reporting and reputational risk.",
                "causes_people": "Sustainability capability limited; engineering buy-in variable",
                "causes_process": "Emissions measurement at cloud / dev level immature",
                "causes_systems": "Sustainability data not integrated with operational systems",
                "causes_external": "Customer ESG procurement requirements; investor focus on tech-sector emissions",
                "consequence": "Reputational impact, contract loss with ESG-focused customers, possible regulatory action.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "Reputational — combined with environmental and customer",
                "owner_suggested": "Head of Sustainability / VP Engineering",
            },
            "HCAR": {
                "title": "Environmental footprint of operations and clinical waste management",
                "description": "Energy use, clinical waste, pharmaceutical disposal, and supply-chain environmental impact create regulatory and reputational risk.",
                "causes_people": "Sustainability capability limited; clinical priorities competing",
                "causes_process": "Waste segregation inconsistent; emissions tracking immature",
                "causes_systems": "ESG data not integrated; waste tracking manual",
                "causes_external": "EPA / environmental regulator focus on clinical waste; healthcare-sector emissions targets",
                "consequence": "Regulator action, additional costs, reputational impact.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "Environmental — combined with regulatory",
                "owner_suggested": "Head of Sustainability / Facilities Director",
            },
            "RETL": {
                "title": "Environmental footprint, packaging, and supply-chain sustainability",
                "description": "Environmental footprint of products, packaging, supply chain, and operations creates regulatory, reputational, and customer risk.",
                "causes_people": "Sustainability capability stretched; supplier oversight limited",
                "causes_process": "Supplier sustainability audits weak; product lifecycle assessment limited",
                "causes_systems": "ESG and supply-chain data fragmented",
                "causes_external": "Regulator focus on greenwashing, packaging waste, recycling, modern slavery",
                "consequence": "Greenwashing claims (regulator action), customer activism, supplier renegotiations, costs of compliance.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with regulatory and environmental",
                "owner_suggested": "Chief Sustainability Officer / Chief Commercial Officer",
            },
            "INDU": {
                "title": "Major environmental incident or regulatory non-compliance",
                "description": "Spill, emission, contamination event, or systemic environmental non-compliance results in significant impact and regulator action.",
                "causes_people": "Operator awareness gaps; environmental management capability variable across sites",
                "causes_process": "Environmental management plans not consistently followed; monitoring weak",
                "causes_systems": "Aging assets prone to leaks; environmental monitoring systems immature",
                "causes_external": "Severe weather; community / activist scrutiny; regulator inspections",
                "consequence": "Substantial fines and remediation costs, criminal proceedings (corporate and individual), loss of operating licence, reputational devastation.",
                "inh_likelihood": 3, "inh_impact": 5,
                "impact_rationale": "Environmental — combined with severe regulatory and financial impact",
                "owner_suggested": "Chief Risk Officer / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Environmental compliance and sustainability reporting",
                "description": "Failure to manage environmental footprint of operations or meet sustainability commitments important to funders and stakeholders.",
                "causes_people": "Sustainability capability limited",
                "causes_process": "Environmental management at facility level inconsistent",
                "causes_systems": "ESG data limited",
                "causes_external": "Funder ESG requirements; community expectations",
                "consequence": "Funder consequences, reputational impact, possible regulatory action.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "Environmental — combined with funding consequences",
                "owner_suggested": "Director of Operations / CEO",
            },
        },
    },

    {
        "id": "R-025",
        "domain": "Environmental and Social",
        "theme": "Social licence / community opposition",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Reputational concerns about clients, matters, or social positioning",
                "description": "Concerns from staff, recruits, community, or activists about firm clients, matters, or social positioning damage reputation and recruitment.",
                "causes_people": "Partners with controversial client portfolios; staff activism",
                "causes_process": "Reputation review for new clients / matters informal",
                "causes_systems": "Stakeholder mapping limited",
                "causes_external": "Activist scrutiny; staff and recruit expectations; ESG-focused client demands",
                "consequence": "Talent attraction difficulty, staff disengagement, lost matters, partner exits.",
                "inh_likelihood": 2, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with people impact",
                "owner_suggested": "Managing Partner",
            },
            "FINS": {
                "title": "Social licence concerns about lending, investment, or product practices",
                "description": "Activist or community opposition to lending in controversial sectors (fossil fuels, weapons, gambling), product practices, or social impact creates reputational and operational risk.",
                "causes_people": "Insufficient ESG capability in customer-facing teams",
                "causes_process": "ESG screening immature; stakeholder engagement informal",
                "causes_systems": "ESG data and decision-support systems limited",
                "causes_external": "Activist investors; AGM activism; sector-specific divestment movements",
                "consequence": "Investor pressure, customer and recruit concerns, board accountability action.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with strategic impact",
                "owner_suggested": "Chief Sustainability Officer / Chief Risk Officer",
            },
            "TECH": {
                "title": "Social impact concerns about products, customers, or operations",
                "description": "Concerns about product social impact (privacy, content, safety), customer base (controversial sectors), or operational practices create stakeholder pressure.",
                "causes_people": "Founder positioning; employee activism",
                "causes_process": "Trust & safety processes immature; customer screening informal",
                "causes_systems": "Content moderation and trust & safety tools limited",
                "causes_external": "Employee activism; customer activism; regulator scrutiny on harm",
                "consequence": "Talent attraction issues, customer pressure, possible regulatory action.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with people and customer impact",
                "owner_suggested": "Chief People Officer / Trust & Safety Lead",
            },
            "HCAR": {
                "title": "Community opposition to facility location, services, or practices",
                "description": "Community opposition to facility location, expansion, or particular services / practices creates approval, recruitment, and reputational issues.",
                "causes_people": "Community relations capability limited",
                "causes_process": "Stakeholder engagement processes informal",
                "causes_systems": "Stakeholder mapping limited",
                "causes_external": "Local community concerns; cultural / religious considerations",
                "consequence": "Approval delays, increased costs, recruitment difficulty in opposed communities.",
                "inh_likelihood": 2, "inh_impact": 3,
                "impact_rationale": "Social — combined with operational impact",
                "owner_suggested": "Head of External Affairs",
            },
            "RETL": {
                "title": "Community opposition to store openings, supplier practices, or operations",
                "description": "Community or activist opposition to specific stores, supplier practices, or operational decisions creates reputational and approval risk.",
                "causes_people": "Community engagement capability limited at store level",
                "causes_process": "New-store engagement processes informal",
                "causes_systems": "Stakeholder mapping limited",
                "causes_external": "Local activism; investigative journalism on supply chain",
                "consequence": "Approval delays, brand damage, store boycotts.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "Reputational — combined with social impact",
                "owner_suggested": "Head of External Affairs / Property Director",
            },
            "INDU": {
                "title": "Loss of social licence and community opposition",
                "description": "Community, indigenous, or activist opposition to operations, projects, or expansion creates approval delays, costs, and reputational damage.",
                "causes_people": "Community relations under-resourced; cultural-heritage capability limited",
                "causes_process": "Stakeholder engagement and consent processes immature",
                "causes_systems": "Stakeholder mapping and engagement systems limited",
                "causes_external": "Indigenous land rights; activist organisations; ESG-focused investors",
                "consequence": "Project delays / cancellations, approval rejections, contract loss, ESG ratings impact, possible legal action.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Social — combined with strategic and financial impact",
                "owner_suggested": "Head of External Affairs / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Loss of community trust or stakeholder opposition",
                "description": "Loss of community trust, stakeholder opposition, or beneficiary criticism creates legitimacy and effectiveness challenges.",
                "causes_people": "Community engagement variable; trustee community connection limited",
                "causes_process": "Stakeholder engagement informal",
                "causes_systems": "Stakeholder data limited",
                "causes_external": "Sector competition; community disillusionment; political environment",
                "consequence": "Reduced effectiveness, beneficiary disengagement, funder concerns, board accountability.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Social — combined with reputational and funding impact",
                "owner_suggested": "CEO / Head of Community Engagement",
            },
        },
    },

    # ════════════════════════════════════════════════════════════════
    # DOMAIN: HEALTH & SAFETY (2 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-026",
        "domain": "Health and Safety",
        "theme": "Workplace injury or fatality",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Workplace injury, psychological injury, or wellbeing failure",
                "description": "Office-based injuries (musculoskeletal, slips/trips), psychological injury from overwork or harassment, or systemic wellbeing failures.",
                "causes_people": "Long working hours culture; harassment / bullying issues",
                "causes_process": "WHS management at office level informal; psychological safety practices limited",
                "causes_systems": "Incident reporting underused; ergonomic assessments inconsistent",
                "causes_external": "Regulator focus on psychosocial hazards (e.g. SafeWork)",
                "consequence": "Workers compensation claims, regulator action, reputational impact, talent attraction issues.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "People — psychological and physical safety",
                "owner_suggested": "WHS Officer / CHRO",
            },
            "FINS": {
                "title": "Workplace injury or psychological harm",
                "description": "Office workplace injuries (mostly psychological — stress, conduct-driven harm) plus customer-violence risk in branch network.",
                "causes_people": "High-pressure roles; customer aggression in branches",
                "causes_process": "Psychosocial risk management immature; branch security inconsistent",
                "causes_systems": "Incident reporting under-utilised",
                "causes_external": "Customer aggression trends; regulator focus on psychosocial hazards",
                "consequence": "Workers compensation, regulator action, reputational impact, branch staff attrition.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "People — psychological injury",
                "owner_suggested": "WHS Lead / CHRO",
            },
            "TECH": {
                "title": "Psychological injury from overwork, stress, or culture",
                "description": "Sustained work pressure, on-call rotations, scaling intensity, and culture issues result in psychological injury and burnout.",
                "causes_people": "Founder / executive pace expectations; manager capability variable",
                "causes_process": "On-call rotations punishing; performance management inconsistent",
                "causes_systems": "Wellbeing monitoring limited",
                "causes_external": "Sector culture norms; regulator focus on psychosocial hazards",
                "consequence": "Workers compensation, attrition, reputational impact, regulator action.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "People — psychological safety",
                "owner_suggested": "VP People",
            },
            "HCAR": {
                "title": "Workplace injury, psychological harm, or violence in clinical settings",
                "description": "Manual handling injuries, needlestick injuries, infectious exposure, occupational violence (from patients / family), and psychological injury.",
                "causes_people": "Workforce shortages increasing pressure; behaviour-of-concern incidents",
                "causes_process": "WHS in clinical settings complex; violence prevention programs variable",
                "causes_systems": "Incident reporting and PPE management variable",
                "causes_external": "Pressure on healthcare creating violence and stress; regulator focus",
                "consequence": "Staff harm, workers compensation, attrition, regulator action, possible criminal proceedings (in fatality scenarios).",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "People — staff safety",
                "owner_suggested": "WHS Director / CHRO",
            },
            "RETL": {
                "title": "Workplace injury, customer aggression, or psychological harm",
                "description": "Retail and DC injuries (manual handling, slips, vehicle), customer aggression incidents, and retail wage / shift psychological pressures.",
                "causes_people": "Casual workforce; lone working in some stores; supervisor capability variable",
                "causes_process": "WHS at store level inconsistent; security arrangements weak in some stores",
                "causes_systems": "Incident reporting under-utilised; CCTV gaps",
                "causes_external": "Customer aggression rising; regulator focus on retail safety",
                "consequence": "Staff injury, workers compensation, regulator action, attrition.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "People — staff safety",
                "owner_suggested": "WHS Manager / CHRO",
            },
            "INDU": {
                "title": "Workplace fatality, serious injury, or significant safety incident",
                "description": "Serious injury or fatality from machinery, falls, mobile plant, electrical, confined space, or other industrial hazards.",
                "causes_people": "Operator behaviour; supervisor capability; subcontractor management variable",
                "causes_process": "WHS systems variable across sites; permit-to-work processes inconsistent",
                "causes_systems": "Aging plant; safety systems not always integrated",
                "causes_external": "Subcontractor workforce variable; regulatory inspection environment",
                "consequence": "Fatality, serious injury, regulator action including industrial manslaughter prosecution, contract loss, reputational devastation.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "People — direct safety impact",
                "owner_suggested": "Chief Risk / Safety Officer",
            },
            "PUBL": {
                "title": "Workplace injury, psychological harm, or volunteer safety",
                "description": "Workplace injuries to staff and volunteers, including psychological injury from beneficiary interactions, and direct safety risks in service-delivery contexts.",
                "causes_people": "Volunteer safety capability variable; trauma exposure of staff",
                "causes_process": "WHS programs immature in volunteer-led organisations",
                "causes_systems": "Incident reporting under-utilised",
                "causes_external": "Beneficiary aggression; regulator focus on psychosocial hazards",
                "consequence": "Staff and volunteer harm, workers compensation, regulator action, recruitment difficulty.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "People — staff and volunteer safety",
                "owner_suggested": "WHS Lead / CEO",
            },
        },
    },

    {
        "id": "R-027",
        "domain": "Health and Safety",
        "theme": "Public / customer safety incident",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Visitor or contractor safety in firm premises",
                "description": "Limited public-safety exposure beyond visitors and contractors on firm premises.",
                "causes_people": "Reception / security awareness variable",
                "causes_process": "Visitor management informal",
                "causes_systems": "Building safety systems standard",
                "causes_external": "Building incidents; emergency events",
                "consequence": "Visitor injury, public liability claim, regulator engagement.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "People — visitor safety",
                "owner_suggested": "Office Manager",
            },
            "FINS": {
                "title": "Customer or visitor safety incidents in branch network",
                "description": "Customer-facing branches expose institution to slip/trip incidents, customer-on-customer aggression, and medical events on-premises.",
                "causes_people": "Branch staff training variable",
                "causes_process": "Branch safety procedures inconsistent",
                "causes_systems": "Branch safety equipment variable",
                "causes_external": "Customer aggression rising; ageing customer demographic",
                "consequence": "Customer injury, public liability claim, reputational impact, regulator engagement.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "People — customer safety",
                "owner_suggested": "Head of Branch Operations",
            },
            "TECH": {
                "title": "Customer harm from product safety or trust & safety failures",
                "description": "Customer harm from product trust & safety failures, including content harm, fraud enablement, harassment on platform, or unsafe product behaviour.",
                "causes_people": "Trust & safety capability limited; product team safety-by-design immature",
                "causes_process": "Trust & safety processes reactive; safety-by-design weak",
                "causes_systems": "Detection and moderation tools limited; AI-driven harm scenarios",
                "causes_external": "Bad actors using platform; sector-wide harm scenarios",
                "consequence": "Customer harm, regulator action, possible criminal liability, reputational devastation.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "People — combined with regulatory and reputational",
                "owner_suggested": "Head of Trust & Safety",
            },
            "HCAR": {
                "title": "Patient safety incident — clinical harm, never-event, infection",
                "description": "Patient safety incidents including never-events, healthcare-associated infections, medication errors, falls, or other clinical harm.",
                "causes_people": "Clinical staffing pressure; communication failures; capability gaps",
                "causes_process": "Clinical pathways and protocols not consistently followed; handover weak",
                "causes_systems": "Clinical decision support gaps; infection control variable",
                "causes_external": "Antimicrobial resistance; surge in demand creating pressure",
                "consequence": "Patient harm or death, regulator action, registrar action, possible criminal proceedings, reputational impact.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "People — patient safety",
                "owner_suggested": "Chief Medical Officer / Director of Patient Safety",
            },
            "RETL": {
                "title": "Customer safety, product harm, or in-store incident",
                "description": "Customer safety incidents including slip/trips, product safety harm, food safety illness, or in-store accidents.",
                "causes_people": "Store staff training variable; product knowledge gaps",
                "causes_process": "Store safety inspections inconsistent; supplier QA variable",
                "causes_systems": "Recall and traceability systems limited; in-store hazard reporting weak",
                "causes_external": "Supplier product issues; food chain contamination; regulator inspection",
                "consequence": "Customer harm, public liability claims, recall costs, regulator action, brand damage.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "People — customer safety",
                "owner_suggested": "WHS Manager / Quality Lead",
            },
            "INDU": {
                "title": "Public / community safety incident from operations, products, or transport",
                "description": "Incidents affecting public or community safety from production processes, transport, products in the field, or environmental release.",
                "causes_people": "Community engagement capability limited; site-level safety variable",
                "causes_process": "Public safety protocols inconsistent; transport / logistics safety variable",
                "causes_systems": "Risk assessment and modelling for public-impact scenarios immature",
                "causes_external": "Transport network conditions; community proximity to operations",
                "consequence": "Public harm, criminal proceedings (corporate and individual), substantial fines, loss of operating licence.",
                "inh_likelihood": 3, "inh_impact": 5,
                "impact_rationale": "People — public safety",
                "owner_suggested": "Chief Risk / Safety Officer",
            },
            "PUBL": {
                "title": "Beneficiary safety incident or safeguarding failure",
                "description": "Safety incidents or safeguarding failures affecting beneficiaries — particularly children, elderly, or vulnerable adults — through abuse, neglect, or service failure.",
                "causes_people": "Volunteer screening variable; safeguarding awareness inconsistent; predator risk in mission-driven orgs",
                "causes_process": "Safeguarding processes immature historically; investigations weak",
                "causes_systems": "Safeguarding case management systems limited",
                "causes_external": "Royal commissions / sector reviews; regulator focus on safeguarding",
                "consequence": "Severe beneficiary harm, criminal proceedings, regulator action, funder withdrawal, reputational devastation.",
                "inh_likelihood": 3, "inh_impact": 5,
                "impact_rationale": "People — combined with severe regulatory and reputational impact",
                "owner_suggested": "Safeguarding Lead / CEO",
            },
        },
    },
]
