"""Batch 2: R-005 through R-011 (Financial completion + Operational domain)"""

BATCH_2 = [
    {
        "id": "R-005",
        "domain": "Financial",
        "theme": "Revenue concentration / loss of major customer",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Loss of a key client representing a disproportionate share of revenue",
                "description": "A small number of major clients represent a large share of fee revenue; loss of one or two materially affects financial viability.",
                "causes_people": "Single-partner relationship rather than firm-wide; weak relationship breadth",
                "causes_process": "Limited cross-selling; no formal key-account program",
                "causes_systems": "Client revenue concentration not actively monitored",
                "causes_external": "Client insolvency; competitor poaching; in-housing of advisory work",
                "consequence": "Material revenue shortfall, redundancy of dedicated teams, partner exits, cash flow pressure.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — direct revenue impact",
                "owner_suggested": "Managing Partner",
            },
            "FINS": {
                "title": "Concentration in a single segment, product, or large institutional customer",
                "description": "Significant share of revenue or AUM is concentrated in a small number of customers, segments, or products, exposing the institution to material loss if any are withdrawn.",
                "causes_people": "Sales incentives biased to large deals; relationship managers in single hands",
                "causes_process": "Concentration limits not tested or enforced; product mix monitoring weak",
                "causes_systems": "Customer profitability and concentration analytics fragmented",
                "causes_external": "Major customer relocates banking; regulatory change disadvantaging key product; competitor pricing aggressively",
                "consequence": "Revenue decline, capital reallocation, cost base unable to flex, possible board / regulator concern.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — revenue and franchise value",
                "owner_suggested": "Chief Commercial Officer",
            },
            "TECH": {
                "title": "Revenue concentration in a small number of enterprise customers",
                "description": "A small number of enterprise customers represent a disproportionate share of ARR; loss of any creates a material revenue gap.",
                "causes_people": "Sales focused on logos rather than customer base diversification; CSM coverage uneven",
                "causes_process": "No formal account health monitoring; renewal forecasting weak",
                "causes_systems": "Customer success platform not surfacing churn signals early",
                "causes_external": "Major customer acquired or restructures; competitor wins displacement deal; budget cuts at major customer",
                "consequence": "ARR decline, growth-rate impact on valuation, sales-team confidence, possible layoffs.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — material ARR loss",
                "owner_suggested": "Chief Revenue Officer",
            },
            "HCAR": {
                "title": "Funding concentration in a single payer, contract, or referral source",
                "description": "Material reliance on one funding stream, contract, or referrer creates exposure if terms change or the relationship ends.",
                "causes_people": "Single point of contact for major payer relationships",
                "causes_process": "No active diversification of referrals or funding sources",
                "causes_systems": "Funding source breakdown not surfaced in management reporting",
                "causes_external": "Payer policy change; major referrer (e.g. GP, hospital) shifts referrals; government contract not renewed",
                "consequence": "Material revenue shortfall, service rationalisation, redundancy, capacity underutilisation.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — revenue and continuity of services",
                "owner_suggested": "CFO",
            },
            "RETL": {
                "title": "Concentration in a small number of major suppliers, brands, or key SKUs",
                "description": "Disproportionate dependence on a small set of suppliers, exclusive brands, or hero SKUs creates risk if any are lost or disrupted.",
                "causes_people": "Buying relationships managed by single individuals; limited supplier diversification",
                "causes_process": "Supplier concentration limits not monitored; no exit / substitution plans",
                "causes_systems": "Supplier dependency not visible in category planning systems",
                "causes_external": "Major supplier insolvency or strategic shift; brand goes direct-to-consumer; exclusivity arrangement ends",
                "consequence": "Range gaps, sales loss, customer dissatisfaction, margin pressure from rushed substitution.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Financial — combined with customer impact",
                "owner_suggested": "Chief Commercial Officer",
            },
            "INDU": {
                "title": "Customer or contract concentration creating revenue dependency",
                "description": "Reliance on a small number of major contracts, projects, or end customers creates exposure if any are lost or scaled back.",
                "causes_people": "Sales / business development under-resourced for diversification",
                "causes_process": "Customer concentration limits not actively tested",
                "causes_systems": "CRM and project pipeline systems not driving diversification metrics",
                "causes_external": "Major customer insolvency; project cancellation; commodity price affecting customer demand",
                "consequence": "Revenue cliff, asset underutilisation, redundancy, possible covenant pressure.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — material revenue impact",
                "owner_suggested": "Chief Commercial Officer",
            },
            "PUBL": {
                "title": "Concentration in a single funder, grant program, or government contract",
                "description": "High dependency on one funder or grant creates material exposure if priorities shift or funding is withdrawn.",
                "causes_people": "Fundraising / development team capacity limited; single funder relationship managers",
                "causes_process": "Insufficient diversification of revenue base; weak donor pipeline",
                "causes_systems": "Funding mix not actively monitored or stress-tested",
                "causes_external": "Government funding shifts; major philanthropic donor changes priorities; tax law affecting giving",
                "consequence": "Program closure, redundancy, failure to deliver mission, reputational impact.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — direct funding loss combined with mission impact",
                "owner_suggested": "CEO / Director of Fundraising",
            },
        },
    },

    {
        "id": "R-006",
        "domain": "Financial",
        "theme": "Fraud / financial misappropriation",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Internal fraud or misuse of client trust funds",
                "description": "Misappropriation of firm or client monies (including trust account balances) by staff, partners, or external actors.",
                "causes_people": "Trust-based culture without controls; single-person handling client money",
                "causes_process": "Inadequate segregation of duties; weak trust account reconciliations",
                "causes_systems": "Practice management system permissions overly broad; no transaction alerting",
                "causes_external": "External actors targeting trust accounts via social engineering",
                "consequence": "Direct financial loss, regulatory action (e.g. law society, CPA), partner liability, reputational destruction, criminal proceedings.",
                "inh_likelihood": 2, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe reputational impact",
                "owner_suggested": "Managing Partner / CFO",
            },
            "FINS": {
                "title": "Internal fraud, market manipulation, or financial crime by staff",
                "description": "Internal misappropriation, unauthorised trading, or facilitation of financial crime by staff causes financial loss and regulatory action.",
                "causes_people": "Pressure to meet sales / trading targets; rogue actor with authority",
                "causes_process": "Weak transaction monitoring; inadequate three-lines-of-defence",
                "causes_systems": "Surveillance systems missing key signals; access controls overbroad",
                "causes_external": "Sophisticated external collusion; targeted attacks on internal staff",
                "consequence": "Regulatory fines (potentially substantial), criminal prosecution, customer compensation, stock impact, executive accountability action.",
                "inh_likelihood": 2, "inh_impact": 5,
                "impact_rationale": "Regulatory — material fine and enforcement risk",
                "owner_suggested": "Chief Risk Officer",
            },
            "TECH": {
                "title": "Internal financial fraud or expense / vendor misappropriation",
                "description": "Misappropriation by staff via fraudulent vendor invoices, expense fraud, or unauthorised commercial arrangements.",
                "causes_people": "Trust-based culture; finance team understaffed; founder-controlled environment",
                "causes_process": "Weak vendor onboarding; expense approvals informal",
                "causes_systems": "Expense and AP systems lacking controls; single approver routes",
                "causes_external": "Vendor invoice fraud (e.g. fake supplier invoices); BEC attacks on finance team",
                "consequence": "Direct financial loss, audit issues affecting next funding round, governance concerns from board / investors.",
                "inh_likelihood": 2, "inh_impact": 4,
                "impact_rationale": "Financial — direct loss combined with investor confidence",
                "owner_suggested": "CFO",
            },
            "HCAR": {
                "title": "Misappropriation of funds, billing fraud, or pharmaceutical theft",
                "description": "Internal fraud through false claims, billing fraud, theft of controlled substances, or misuse of patient or organisational funds.",
                "causes_people": "Pressure to meet revenue targets; weak supervision of clinical billing",
                "causes_process": "Coding and billing oversight weak; controlled drug audits infrequent",
                "causes_systems": "Patient management / billing systems with weak audit trail",
                "causes_external": "Organised fraud schemes targeting healthcare; insurance fraud",
                "consequence": "Funder clawback, criminal prosecution, accreditation impact, registrar action against clinicians, reputational impact.",
                "inh_likelihood": 2, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with reputational impact",
                "owner_suggested": "CFO / Compliance Officer",
            },
            "RETL": {
                "title": "Internal theft, point-of-sale fraud, or cash handling misappropriation",
                "description": "Staff theft of stock, cash, or fraudulent transactions at POS lead to material shrinkage and financial loss.",
                "causes_people": "Casual workforce with limited screening; cash-handling staff under pressure",
                "causes_process": "Stock controls and cash reconciliation weak; refund and discount approvals lax",
                "causes_systems": "POS systems lacking transaction analytics; CCTV gaps",
                "causes_external": "Organised retail crime; customer-employee collusion",
                "consequence": "Inventory shrinkage, margin erosion, insurance premium increases, reputational impact in extreme cases.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Financial — recurring shrinkage at scale",
                "owner_suggested": "Head of Loss Prevention",
            },
            "INDU": {
                "title": "Internal fraud, supplier kickbacks, or asset misappropriation",
                "description": "Fraud through inflated supplier invoices, kickbacks, theft of materials or equipment, or false project claims.",
                "causes_people": "Site-based decision-making with limited oversight; long-tenured procurement staff with limited rotation",
                "causes_process": "Procurement controls weak at site level; tendering not properly contested",
                "causes_systems": "ERP controls bypassed by site-level processes; weak access management",
                "causes_external": "Cartel or collusion among suppliers; criminal targeting of high-value sites or materials",
                "consequence": "Direct financial loss, contract overpricing accumulated over years, regulator scrutiny, criminal proceedings.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — substantial cumulative loss",
                "owner_suggested": "CFO / Head of Procurement",
            },
            "PUBL": {
                "title": "Misuse of grant funds, donor money, or organisational assets",
                "description": "Misappropriation of funds intended for beneficiaries, fraudulent grant claims, or misuse of organisational assets.",
                "causes_people": "Trust-based culture; volunteer involvement without proper screening",
                "causes_process": "Grant acquittal weak; segregation of duties limited in small teams",
                "causes_systems": "Financial system controls minimal; expense approvals manual",
                "causes_external": "Targeting by external fraudsters; donor-directed fraud",
                "consequence": "Funding clawback, ACNC / charity regulator action, donor confidence loss, mission disruption.",
                "inh_likelihood": 2, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with regulatory and funding impact",
                "owner_suggested": "CEO / CFO",
            },
        },
    },

    {
        "id": "R-007",
        "domain": "Financial",
        "theme": "Currency, interest rate, or commodity price exposure",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Foreign currency exposure on cross-border engagements",
                "description": "Engagements priced in non-functional currency expose the firm to FX movement between billing and collection.",
                "causes_people": "Pricing decisions made without FX consideration; treasury capability limited",
                "causes_process": "No FX hedging policy for cross-border work",
                "causes_systems": "Practice management system not flagging FX exposure",
                "causes_external": "Volatile exchange rate movements; client demands for local-currency billing",
                "consequence": "Margin erosion on international work; profit volatility on long-running matters.",
                "inh_likelihood": 3, "inh_impact": 2,
                "impact_rationale": "Financial — margin volatility",
                "owner_suggested": "CFO",
            },
            "FINS": {
                "title": "Market risk exposure from interest rate, FX, or equity movements",
                "description": "Movements in interest rates, FX, or equity markets adversely affect trading book, banking book, or investment portfolio values.",
                "causes_people": "Risk appetite breaches not escalated promptly; trader behaviour outside mandate",
                "causes_process": "Stress testing inadequate; ALCO review cycle too slow",
                "causes_systems": "Risk systems not capturing all positions; valuation models weak",
                "causes_external": "Sudden rate moves; geopolitical events affecting markets; commodity shocks",
                "consequence": "Earnings volatility, capital impact, regulatory limit breach, possible trading desk closures.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Financial — earnings and capital impact",
                "owner_suggested": "Chief Risk Officer / Treasurer",
            },
            "TECH": {
                "title": "FX exposure on global revenue, cloud costs, or international workforce",
                "description": "Currency movements affect both revenue (multi-currency billing) and major cost centres (cloud infrastructure, distributed workforce).",
                "causes_people": "Treasury capability limited at growth stage",
                "causes_process": "No FX hedging policy; pricing not regularly reviewed against FX",
                "causes_systems": "Billing system pricing not dynamic to currency",
                "causes_external": "Significant currency moves; cloud provider price changes",
                "consequence": "Margin compression, gross margin volatility affecting valuation multiples.",
                "inh_likelihood": 3, "inh_impact": 2,
                "impact_rationale": "Financial — margin and reported earnings",
                "owner_suggested": "CFO",
            },
            "HCAR": {
                "title": "Cost exposure to imported pharmaceuticals, equipment, and consumables",
                "description": "Significant non-functional-currency exposure on medical equipment, drugs, and consumables creates margin volatility.",
                "causes_people": "Procurement team limited FX visibility",
                "causes_process": "Forward purchasing limited; no FX hedging",
                "causes_systems": "Procurement systems not surfacing FX exposure",
                "causes_external": "Currency depreciation; supplier price increases",
                "consequence": "Margin pressure, potential need to substitute lower-quality alternatives, rationing of services.",
                "inh_likelihood": 3, "inh_impact": 2,
                "impact_rationale": "Financial — margin impact",
                "owner_suggested": "CFO / Head of Procurement",
            },
            "RETL": {
                "title": "FX and commodity exposure on imported goods",
                "description": "Movement in import currency or input commodity prices affects landed cost of goods, with limited ability to pass through to consumers.",
                "causes_people": "Buying team focused on landed cost at order; limited treasury collaboration",
                "causes_process": "Limited forward cover or hedging on imports",
                "causes_systems": "Cost systems not modelling FX scenarios",
                "causes_external": "Currency depreciation; commodity price spikes (cotton, oil-based plastics, food); shipping cost volatility",
                "consequence": "Margin compression, need to raise prices in competitive market, range simplification, supplier disputes.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Financial — margin and competitive position",
                "owner_suggested": "Chief Commercial Officer",
            },
            "INDU": {
                "title": "Commodity price exposure on inputs or outputs",
                "description": "Material exposure to commodity price movements (energy, raw materials, fuel) affects cost base or output prices.",
                "causes_people": "Procurement and treasury teams not aligned; commercial team without commodity expertise",
                "causes_process": "Hedging policy informal; pricing of customer contracts not indexed",
                "causes_systems": "Risk and procurement systems siloed",
                "causes_external": "Commodity price shocks (oil, steel, copper); energy market disruption; geopolitical events",
                "consequence": "Margin volatility, customer contract losses, possible covenant pressure.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — material earnings impact",
                "owner_suggested": "CFO / Treasurer",
            },
            "PUBL": {
                "title": "Limited financial market exposure but funding model sensitivity to economic shifts",
                "description": "While direct market exposure is typically limited, organisational funding may be sensitive to interest rates, inflation, or tax law changes.",
                "causes_people": "Finance and reserves capability limited; investment policy outdated",
                "causes_process": "Reserves policy not stress-tested; no regular ALM review",
                "causes_systems": "Investment performance not regularly reviewed against benchmarks",
                "causes_external": "Interest rate environment affecting investment returns; inflation eroding real value of reserves",
                "consequence": "Reserves erosion, programme funding gaps, possible breach of donor restrictions.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "Financial — reserves and investment income",
                "owner_suggested": "CFO / Treasurer",
            },
        },
    },

    # ════════════════════════════════════════════════════════════════
    # DOMAIN: OPERATIONAL (4 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-008",
        "domain": "Operational",
        "theme": "Critical process failure causing service disruption",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Failure of a critical client-service process or matter delivery",
                "description": "Failure in a core engagement-delivery process (deadlines, deliverables, conflicts, reporting) causes client harm and engagement breakdown.",
                "causes_people": "Capacity overload on engagement team; weak supervision of junior staff",
                "causes_process": "Engagement planning weak; quality review inconsistent; deadline tracking informal",
                "causes_systems": "Practice management and matter tracking systems not integrated; conflicts checking manual",
                "causes_external": "Last-minute client demands; regulatory or court-driven deadline shifts",
                "consequence": "Missed filing deadlines, client complaints, fee write-offs, professional indemnity claim risk.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Customer — combined with financial impact",
                "owner_suggested": "COO / Practice Manager",
            },
            "FINS": {
                "title": "Failure of a critical operational process (payments, settlements, customer onboarding)",
                "description": "Disruption in core operational processes (payment processing, settlements, KYC onboarding, claims) prevents service delivery to customers.",
                "causes_people": "Team capacity stretched; complex processes dependent on key individuals",
                "causes_process": "Process change management weak; insufficient automation; manual handoffs",
                "causes_systems": "Process orchestration systems lacking resilience; manual workarounds embedded",
                "causes_external": "Surge in volumes; counterparty failure; regulatory change requiring rapid process update",
                "consequence": "Customer complaints, regulator engagement, financial loss, reputational impact, possible breach of service standards.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Customer — combined with regulatory and financial impact",
                "owner_suggested": "COO",
            },
            "TECH": {
                "title": "Failure of a critical engineering, deployment, or customer-facing process",
                "description": "Process failure in deployment, change management, customer onboarding, or support causes service disruption or customer harm.",
                "causes_people": "Engineering capacity stretched; process bypassed under deadline pressure",
                "causes_process": "Change management informal; insufficient automated testing",
                "causes_systems": "CI/CD or deployment tooling immature; observability gaps",
                "causes_external": "Surge in customer demand; partner integration breaking changes",
                "consequence": "Customer outage, SLA breach, churn, NPS impact, executive distraction.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Customer — service availability impact",
                "owner_suggested": "VP Engineering / COO",
            },
            "HCAR": {
                "title": "Failure of a critical clinical or operational process",
                "description": "Failure in a clinical pathway, medication management, infection control, or critical operational process causes patient harm or service disruption.",
                "causes_people": "Clinical workforce shortage; staff fatigue; communication breakdown at handover",
                "causes_process": "Standard operating procedures not followed; clinical pathway gaps",
                "causes_systems": "Clinical systems usability issues; alert fatigue; integration gaps",
                "causes_external": "Demand surge; pharmaceutical or equipment shortage",
                "consequence": "Patient harm or near-miss, regulator notification, accreditation impact, criminal liability in extreme cases.",
                "inh_likelihood": 3, "inh_impact": 5,
                "impact_rationale": "People — patient safety impact",
                "owner_suggested": "Chief Medical Officer / Chief Operating Officer",
            },
            "RETL": {
                "title": "Failure of store operations, fulfilment, or supply replenishment",
                "description": "Failure of core retail processes (store operations, replenishment, e-commerce fulfilment, returns) prevents serving customers.",
                "causes_people": "Store team turnover; managerial capability gaps; head office vs store disconnect",
                "causes_process": "Replenishment cadence inadequate; returns processes manual",
                "causes_systems": "POS, inventory, and online platforms not integrated; outages during peak",
                "causes_external": "Demand surge (e.g. promotional event); supply chain disruption",
                "consequence": "Lost sales, customer dissatisfaction, mark-downs, brand impact.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Customer — combined with financial impact",
                "owner_suggested": "Chief Operating Officer",
            },
            "INDU": {
                "title": "Failure of critical production, project execution, or logistics process",
                "description": "Process failure on production line, in project execution, or in logistics causes customer disruption, quality failures, or asset damage.",
                "causes_people": "Operator skill gaps; turnover at supervisory level; safety culture pressures",
                "causes_process": "Standard operating procedures outdated; weak handover between shifts",
                "causes_systems": "Asset management or MES systems not integrated; sensor data not actionable",
                "causes_external": "Raw material quality issues; weather or environmental events; regulatory inspection",
                "consequence": "Production loss, contract penalties, customer loss, possible safety or environmental incident.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — combined with customer and safety impact",
                "owner_suggested": "Chief Operating Officer",
            },
            "PUBL": {
                "title": "Failure of a critical service-delivery or compliance process",
                "description": "Failure in a key service-delivery process (case management, payment delivery, eligibility assessment, statutory reporting) prevents serving beneficiaries.",
                "causes_people": "Caseworker workload high; staff turnover; capability gaps",
                "causes_process": "Process design dated; manual handoffs creating delays",
                "causes_systems": "Legacy case management systems; integration gaps with funder systems",
                "causes_external": "Surge in demand; policy change requiring rapid process redesign",
                "consequence": "Beneficiary harm, ministerial inquiry, ombudsman complaints, funding clawback.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with social and regulatory impact",
                "owner_suggested": "Chief Operating Officer",
            },
        },
    },

    {
        "id": "R-009",
        "domain": "Operational",
        "theme": "Asset / equipment / infrastructure failure",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Failure of office facilities, IT infrastructure, or workplace assets",
                "description": "Building, power, network, or workplace asset failure prevents fee earners from working productively.",
                "causes_people": "Facilities management capability limited; outsourced support unresponsive",
                "causes_process": "Preventive maintenance ad-hoc; no formal asset register",
                "causes_systems": "Building management systems aging; IT redundancy minimal",
                "causes_external": "Building landlord issues; utility outage; weather events",
                "consequence": "Productivity loss, missed deadlines, reputational impact in client-facing scenarios.",
                "inh_likelihood": 2, "inh_impact": 2,
                "impact_rationale": "Financial — productivity loss",
                "owner_suggested": "Office Manager / COO",
            },
            "FINS": {
                "title": "Failure of branch network, ATM fleet, or critical infrastructure",
                "description": "Failure in physical infrastructure (branches, ATM network, data centres) disrupts customer access and core operations.",
                "causes_people": "Facilities and infrastructure teams under-resourced",
                "causes_process": "Preventive maintenance lapses; capacity planning weak",
                "causes_systems": "Aging hardware; insufficient redundancy in network design",
                "causes_external": "Power grid failures; weather events; physical attacks (e.g. ATM ram-raids)",
                "consequence": "Customer access disruption, complaints, regulatory engagement, reputational impact.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Customer — service availability",
                "owner_suggested": "COO",
            },
            "TECH": {
                "title": "Failure of cloud infrastructure, third-party services, or development tooling",
                "description": "Outage of cloud provider, critical SaaS dependency, or dev tooling prevents engineering and customer-facing operations.",
                "causes_people": "SRE capability limited; on-call coverage gaps",
                "causes_process": "Incident response immature; vendor management weak",
                "causes_systems": "Single-region or single-vendor architecture; observability gaps",
                "causes_external": "Cloud provider outages; SaaS dependency failure; DDoS events",
                "consequence": "Customer outage, SLA breach, churn, executive distraction, contractual remedies.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Customer — service availability and contractual impact",
                "owner_suggested": "VP Engineering / CTO",
            },
            "HCAR": {
                "title": "Failure of medical equipment, clinical systems, or facility infrastructure",
                "description": "Failure of essential medical equipment (imaging, monitoring, surgical), clinical IT systems, or facility infrastructure (power, water, gases) disrupts patient care.",
                "causes_people": "Biomedical engineering capacity limited; preventive maintenance backlog",
                "causes_process": "Asset replacement program underfunded; calibration cycles slipped",
                "causes_systems": "Aging medical equipment; clinical systems lacking redundancy",
                "causes_external": "Manufacturer recall; supply chain shortage of parts; weather / power events",
                "consequence": "Patient harm or care delay, accreditation impact, financial loss, possible regulatory action.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "People — patient safety",
                "owner_suggested": "Chief Medical Officer / Facilities Director",
            },
            "RETL": {
                "title": "Failure of POS, e-commerce platform, or distribution infrastructure",
                "description": "Failure of customer-facing or distribution infrastructure (POS, online platform, DC equipment, refrigeration) prevents trading.",
                "causes_people": "Store IT support capacity limited; DC operations dependent on key staff",
                "causes_process": "Preventive maintenance backlog; resilience testing weak",
                "causes_systems": "Aging in-store technology; e-commerce platform single-region",
                "causes_external": "Power outages; cyber events; weather affecting DCs",
                "consequence": "Lost sales during outage, perishable inventory loss (e.g. cold chain), customer complaints.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Customer — combined with financial loss",
                "owner_suggested": "Chief Operating Officer",
            },
            "INDU": {
                "title": "Failure of critical plant, equipment, or infrastructure",
                "description": "Failure of major production assets, fleet, or operational infrastructure causes production loss, safety incidents, or environmental impact.",
                "causes_people": "Maintenance crew skill gaps; operator error; reliance on contractors",
                "causes_process": "Preventive maintenance backlog; condition monitoring inadequate",
                "causes_systems": "Aging assets; integration of asset management with operations weak",
                "causes_external": "Raw material quality affecting equipment; severe weather; vendor parts shortage",
                "consequence": "Production loss, contract penalties, possible safety or environmental incident, capital cost of replacement.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — combined with safety and environmental risk",
                "owner_suggested": "Head of Maintenance / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Failure of facility, infrastructure, or service-delivery assets",
                "description": "Failure of facilities, service-delivery assets (vehicles, equipment), or technology infrastructure disrupts services to beneficiaries.",
                "causes_people": "Facilities team under-resourced; volunteer-led operations",
                "causes_process": "Asset register incomplete; maintenance budgets cut",
                "causes_systems": "Aging facilities and equipment; insufficient capital reserves",
                "causes_external": "Weather events; vandalism; utility failure",
                "consequence": "Service disruption, beneficiary harm, additional emergency funding required.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with service-delivery impact",
                "owner_suggested": "Chief Operating Officer / Facilities Manager",
            },
        },
    },

    {
        "id": "R-010",
        "domain": "Operational",
        "theme": "Capacity constraint (cannot meet demand)",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Insufficient fee-earner capacity to meet client demand",
                "description": "Demand for services exceeds available fee-earner capacity, resulting in declined work, deadline pressure, and burnout.",
                "causes_people": "Recruitment lag; high attrition; partner-level bottlenecks on review",
                "causes_process": "Resource planning informal; engagement scoping weak",
                "causes_systems": "Capacity / utilisation reporting limited; no forward demand pipeline visibility",
                "causes_external": "Surge in regulatory deadlines or client transactions; market events driving demand",
                "consequence": "Declined work and lost fee revenue, missed deadlines, burnout-driven attrition, quality slip.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Financial — combined with people and customer impact",
                "owner_suggested": "Practice Manager / COO",
            },
            "FINS": {
                "title": "Operational capacity unable to meet customer demand or volume surges",
                "description": "Customer onboarding, claims processing, contact centre, or transaction processing capacity unable to keep pace with demand.",
                "causes_people": "Hiring lag; high attrition in operations roles",
                "causes_process": "Forecasting weak; no surge-capacity planning",
                "causes_systems": "Process automation immature; system throughput limits",
                "causes_external": "Marketing campaign spike; market event driving claims; rate-cycle change driving applications",
                "consequence": "Customer complaints, regulator engagement, lost sales, reputational damage.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Customer — service experience impact",
                "owner_suggested": "Chief Operating Officer",
            },
            "TECH": {
                "title": "Engineering, support, or infrastructure capacity unable to meet demand",
                "description": "Insufficient engineering capacity, support staffing, or infrastructure scale limits ability to deliver roadmap, support customers, or handle traffic.",
                "causes_people": "Hiring competition; engineering manager span too wide",
                "causes_process": "Roadmap not prioritised against capacity; support tier model unclear",
                "causes_systems": "Auto-scaling not configured; support tooling immature",
                "causes_external": "Customer growth surge; viral product moment; competitor outage shifting users",
                "consequence": "Roadmap delays, support backlog, NPS decline, churn, executive frustration.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Customer — combined with financial impact via churn",
                "owner_suggested": "VP Engineering / Head of Customer Support",
            },
            "HCAR": {
                "title": "Clinical or operational capacity unable to meet patient demand",
                "description": "Patient demand exceeds available beds, clinicians, theatre time, or community capacity, leading to wait list growth and clinical risk.",
                "causes_people": "Clinician shortage; locum dependence; nurse-to-patient ratios under pressure",
                "causes_process": "Capacity planning reactive; weak demand-supply matching",
                "causes_systems": "Theatre / bed management systems not optimising utilisation",
                "causes_external": "Population health changes; pandemic / seasonal surge; competing facility closures",
                "consequence": "Patient harm from delayed care, regulator action, ombudsman complaints, reputational impact.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "People — patient safety risk",
                "owner_suggested": "Chief Medical Officer",
            },
            "RETL": {
                "title": "Inability to meet customer demand at peak trading periods",
                "description": "Stock, store staffing, or fulfilment capacity insufficient to meet demand at peak (e.g. seasonal events, promotions) leading to lost sales.",
                "causes_people": "Casual workforce hiring lag; key store roles unfilled",
                "causes_process": "Demand forecasting weak; supplier lead times not factored",
                "causes_systems": "Inventory replenishment systems not aligned with promotional plans",
                "causes_external": "Promotional event or competitor disruption shifting demand; supply chain disruption",
                "consequence": "Lost sales at peak (often unrecoverable), customer dissatisfaction, brand impact.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Financial — direct lost revenue",
                "owner_suggested": "Chief Commercial Officer",
            },
            "INDU": {
                "title": "Production, project, or logistics capacity unable to meet demand",
                "description": "Plant capacity, skilled workforce, or logistics throughput cannot meet contracted or expected demand.",
                "causes_people": "Skilled trades shortage; turnover in key roles",
                "causes_process": "S&OP weak; capacity planning reactive",
                "causes_systems": "MES / ERP not optimising scheduling",
                "causes_external": "Demand surge; supply chain bottlenecks; energy availability",
                "consequence": "Contract penalties, customer loss, premium-cost subcontracting, margin compression.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Financial — contract performance and margin",
                "owner_suggested": "Chief Operating Officer",
            },
            "PUBL": {
                "title": "Service-delivery capacity unable to meet beneficiary demand",
                "description": "Demand for services from beneficiaries exceeds available case workers, programs, or facilities, leading to long wait lists and harm.",
                "causes_people": "Funding doesn't match demand; volunteer base shrinking",
                "causes_process": "Eligibility assessment weak; no formal demand management",
                "causes_systems": "Case management systems not optimising allocation",
                "causes_external": "Cost of living crisis driving demand; population growth; competing service closures",
                "consequence": "Beneficiary harm, ministerial inquiry, ombudsman complaints, staff burnout.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Social — beneficiary harm and reputational impact",
                "owner_suggested": "Chief Operating Officer / Director of Services",
            },
        },
    },

    {
        "id": "R-011",
        "domain": "Operational",
        "theme": "Quality failure in product or service delivery",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Quality failure in advice, deliverables, or engagement output",
                "description": "Errors, omissions, or below-standard advice in client deliverables result in client harm and exposure to claims.",
                "causes_people": "Junior work not adequately reviewed; subject matter experts overcommitted",
                "causes_process": "Quality review steps inconsistent; tight deadlines compressing review time",
                "causes_systems": "Knowledge management weak; precedent / template currency uncertain",
                "causes_external": "Complex regulatory or commercial environments; rapid change in advice domain",
                "consequence": "Client harm, fee write-offs, professional indemnity claim, reputational impact, partner accountability.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Customer — combined with financial and reputational impact",
                "owner_suggested": "Quality / Risk Partner",
            },
            "FINS": {
                "title": "Quality failure in advice, product execution, or customer outcomes",
                "description": "Mis-selling, poor advice, product execution failure, or unfair customer outcomes lead to remediation, regulator action, and reputational harm.",
                "causes_people": "Sales incentives misaligned with customer outcomes; advice training gaps",
                "causes_process": "Product governance weak; customer-outcome monitoring limited",
                "causes_systems": "Advice and CX monitoring systems immature",
                "causes_external": "Regulator focus on customer outcomes; class action environment",
                "consequence": "Remediation programs (potentially substantial), regulatory action, fines, executive accountability, reputational impact.",
                "inh_likelihood": 3, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe financial and reputational impact",
                "owner_suggested": "Chief Risk Officer / Head of Compliance",
            },
            "TECH": {
                "title": "Quality failure in product, releases, or customer experience",
                "description": "Bugs, quality issues, or poor customer experience in releases damage customer trust, increase support load, and drive churn.",
                "causes_people": "QA capacity limited; engineering velocity prioritised over quality",
                "causes_process": "Test automation immature; insufficient pre-release testing",
                "causes_systems": "Observability gaps; staging environment differing from production",
                "causes_external": "Third-party API or library defects propagating",
                "consequence": "Customer churn, NPS decline, support cost increase, reputational impact.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Customer — service quality impact",
                "owner_suggested": "VP Engineering / Head of QA",
            },
            "HCAR": {
                "title": "Clinical quality failure or below-standard care",
                "description": "Failure to meet clinical standards results in patient harm, near-misses, or systemic quality issues identified by accreditors or regulators.",
                "causes_people": "Clinician fatigue; staff capability gaps; communication failures",
                "causes_process": "Clinical guidelines not followed; quality monitoring weak",
                "causes_systems": "Clinical decision support gaps; alert fatigue",
                "causes_external": "New treatment standards rapidly emerging; accreditor scrutiny",
                "consequence": "Patient harm, accreditation impact, regulator action, criminal liability in extreme cases, reputational damage.",
                "inh_likelihood": 3, "inh_impact": 5,
                "impact_rationale": "People — patient safety",
                "owner_suggested": "Chief Medical Officer / Director of Clinical Governance",
            },
            "RETL": {
                "title": "Product quality failure, food safety, or service quality issues",
                "description": "Defective products, food safety incidents, or service quality issues result in customer harm, recalls, and reputational damage.",
                "causes_people": "Supplier QA team capacity; store team training gaps",
                "causes_process": "Supplier audits infrequent; in-store quality checks weak",
                "causes_systems": "Quality and recall systems manual; traceability limited",
                "causes_external": "Supplier quality failures; raw material contamination",
                "consequence": "Product recall costs, customer harm, regulator action, reputational damage, possible class action.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Customer — combined with regulatory and reputational",
                "owner_suggested": "Head of Quality / Chief Commercial Officer",
            },
            "INDU": {
                "title": "Product quality failure or out-of-specification output",
                "description": "Manufacturing defects, project quality issues, or out-of-spec output leads to customer rejection, rework, and warranty cost.",
                "causes_people": "Operator skill gaps; inspector turnover",
                "causes_process": "Quality control processes inconsistent; weak supplier quality assurance",
                "causes_systems": "Quality management systems not integrated with production",
                "causes_external": "Raw material quality variability; component supplier issues",
                "consequence": "Customer rejection, warranty costs, recall costs, reputational impact, possible safety implications.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Customer — combined with financial impact",
                "owner_suggested": "Head of Quality",
            },
            "PUBL": {
                "title": "Service-quality failure affecting beneficiaries",
                "description": "Failure to deliver services to a quality standard expected by beneficiaries, funders, or accreditors results in harm or loss of funding.",
                "causes_people": "Workforce capability variable; high reliance on volunteers",
                "causes_process": "Service standards not consistently applied; weak quality monitoring",
                "causes_systems": "Outcome measurement immature",
                "causes_external": "Funder requirements raising the standard; community expectations evolving",
                "consequence": "Beneficiary harm, funder action, accreditation loss, reputational damage.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Social — beneficiary outcomes and reputation",
                "owner_suggested": "Director of Services / Quality Lead",
            },
        },
    },
]
