"""
Blue Peak Risk — Master Risk Library
=====================================

Universal taxonomy of 32 risk themes across 13 domains, with 7 industry-tailored
variants each. All inherent ratings are indicative starting points and should be
adjusted by the user based on their organisation's specific context.

Industry archetypes:
  PROF - Professional Services
  FINS - Financial Services
  TECH - Technology / SaaS
  HCAR - Healthcare
  RETL - Retail / Hospitality
  INDU - Industrial / Physical (Manufacturing, Construction, Mining, Energy, Logistics)
  PUBL - Public / NFP (Government, Education, Charity, Community)

Impact category abbreviations:
  FIN - Financial
  CUS - Customer
  REG - Regulatory
  REP - Reputational
  PPL - People (Health, Safety, Wellbeing)
  SOC - Social (External Stakeholders)
  ENV - Environmental
"""

# Each entry follows the schema:
# {
#   "id": "R-001",
#   "domain": "Strategic",
#   "theme": "Universal name",
#   "treatment": "Reduce",
#   "industries": {
#       "PROF": { ...all industry-tailored fields... },
#       "FINS": { ... },
#       ...
#   }
# }

RISK_LIBRARY = [
    # ════════════════════════════════════════════════════════════════
    # DOMAIN: STRATEGIC (3 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-001",
        "domain": "Strategic",
        "theme": "Strategic plan failure / loss of competitive position",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Failure to evolve service offering against changing client needs",
                "description": "The firm's service mix, pricing, or delivery model fails to keep pace with how clients buy and use professional services, eroding competitive position.",
                "causes_people": "Partner group resistant to change; insufficient strategic capability in leadership team",
                "causes_process": "Strategy reviewed too infrequently; weak market intelligence and competitor tracking",
                "causes_systems": "No systems to track win/loss data, client feedback, or pricing benchmarks",
                "causes_external": "Big-4 / boutique competition; clients moving to in-house teams; AI-driven service automation",
                "consequence": "Loss of market share, declining win rates, downward pressure on fees, and difficulty attracting talent.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — sustained revenue and margin decline",
                "owner_suggested": "Managing Partner",
            },
            "FINS": {
                "title": "Failure to adapt to digital disruption and changing customer expectations",
                "description": "The institution's products, channels, and customer experience fall behind digital-first challengers and changing customer demand.",
                "causes_people": "Legacy mindset in executive team; insufficient digital expertise on board",
                "causes_process": "Strategic planning cycle too long; product development cycles slow",
                "causes_systems": "Core platforms inflexible; data fragmented; limited real-time analytics",
                "causes_external": "Fintech challengers; embedded finance from non-bank entrants; open-banking enablement",
                "consequence": "Erosion of customer base to digital challengers, falling NPS, declining return on equity, regulatory pressure to modernise.",
                "inh_likelihood": 4,
                "inh_impact": 4,
                "impact_rationale": "Financial — long-term revenue and franchise value at stake",
                "owner_suggested": "Chief Strategy Officer",
            },
            "TECH": {
                "title": "Loss of product-market fit or competitive positioning",
                "description": "The product roadmap fails to keep pace with customer needs or competitor capability, leading to churn and stalled growth.",
                "causes_people": "Founder / CEO disconnected from customer base; product leadership inexperienced",
                "causes_process": "Insufficient customer discovery; roadmap driven by internal opinions not data",
                "causes_systems": "Limited usage analytics; no competitive intelligence platform",
                "causes_external": "Well-funded competitor entering market; technology paradigm shift (e.g. AI-native rivals)",
                "consequence": "Increased churn, declining win rates, valuation impact, difficulty raising capital, talent attrition.",
                "inh_likelihood": 4,
                "inh_impact": 5,
                "impact_rationale": "Financial — existential threat to business viability",
                "owner_suggested": "CEO / Chief Product Officer",
            },
            "HCAR": {
                "title": "Failure to adapt service model to changing healthcare delivery and funding",
                "description": "The organisation's service mix, locations, or care model becomes misaligned with patient demand, payer expectations, and clinical best practice.",
                "causes_people": "Clinical leadership averse to change; governance dominated by incumbents",
                "causes_process": "Strategy slow to incorporate population health and outcome-based care",
                "causes_systems": "Limited integration between clinical, financial, and patient-experience data",
                "causes_external": "Telehealth substitution; funding model reform; private hospital vs. public competition",
                "consequence": "Declining occupancy or referrals, funding shortfalls, loss of accreditation, reputational impact.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — combined with reputational and patient-outcome consequences",
                "owner_suggested": "CEO / Chief Medical Officer",
            },
            "RETL": {
                "title": "Failure to adapt to changing consumer behaviour and channel mix",
                "description": "The retail proposition, format, or channel mix fails to keep pace with consumer expectations around price, convenience, ethics, and experience.",
                "causes_people": "Merchandising decisions based on intuition rather than data; insufficient e-commerce capability",
                "causes_process": "Range planning cycle too slow; weak omnichannel coordination",
                "causes_systems": "Disconnected POS, online, and inventory systems limiting customer view",
                "causes_external": "Pure-play online competitors; cost-of-living pressure on consumers; rapid changes in consumer ethics expectations",
                "consequence": "Declining like-for-like sales, store closures, write-down of unsaleable inventory, brand fatigue.",
                "inh_likelihood": 4,
                "inh_impact": 4,
                "impact_rationale": "Financial — revenue compression and asset write-downs",
                "owner_suggested": "Chief Commercial Officer",
            },
            "INDU": {
                "title": "Failure to evolve operating model against industry transformation",
                "description": "The organisation's operating model, asset base, or product portfolio fails to keep pace with industry shifts (decarbonisation, automation, supply chain reshaping).",
                "causes_people": "Engineering culture resistant to non-traditional thinking; succession gaps in strategy roles",
                "causes_process": "Capital allocation framework biased to incumbent technology",
                "causes_systems": "Asset planning systems not modelling emerging scenarios (e.g. decarbonisation pathways)",
                "causes_external": "Emerging technology displacing existing methods; offshoring or reshoring of demand; ESG-driven capital reallocation",
                "consequence": "Stranded assets, capex misallocation, loss of customer contracts, declining margins, workforce displacement.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — significant asset and contract value at risk",
                "owner_suggested": "CEO / Chief Strategy Officer",
            },
            "PUBL": {
                "title": "Failure to deliver on mission, mandate, or strategic plan",
                "description": "The organisation's programs and services fail to keep pace with community need, beneficiary expectations, or stated strategic objectives.",
                "causes_people": "Board / Council disengaged from delivery; insufficient strategic capability",
                "causes_process": "Strategy reviewed too infrequently; outcomes measurement immature",
                "causes_systems": "Limited data on beneficiary outcomes or service utilisation",
                "causes_external": "Funding cuts or shifts; competing service providers; changing community demographics",
                "consequence": "Loss of funding, reduced impact, stakeholder criticism, ministerial intervention, loss of trust.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Reputational — combined with funding consequences",
                "owner_suggested": "CEO / Executive Director",
            },
        },
    },

    {
        "id": "R-002",
        "domain": "Strategic",
        "theme": "Market disruption from new technology or entrant",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Disruption from AI-enabled service delivery and alternative legal/advisory providers",
                "description": "Generative AI tools, alternative service providers (Big-4 advisory arms, legal-tech, virtual CFOs) substitute for traditional fee-earning work.",
                "causes_people": "Slow adoption of AI tools; fee-earner reluctance to embrace new methods",
                "causes_process": "Pricing models still hours-based when clients want fixed-fee or outcome-based",
                "causes_systems": "Lack of investment in AI / automation tooling within the firm",
                "causes_external": "Generative AI capability; ALSPs; clients building in-house teams",
                "consequence": "Commoditisation of advice, fee compression, disintermediation, redundancy of mid-tier roles.",
                "inh_likelihood": 4,
                "inh_impact": 4,
                "impact_rationale": "Financial — direct fee revenue substitution",
                "owner_suggested": "Managing Partner",
            },
            "FINS": {
                "title": "Disruption from neobanks, embedded finance, and crypto-native providers",
                "description": "Customers move banking, payments, or investment activity to faster, lower-cost, or specialised digital providers.",
                "causes_people": "Talent flight to fintechs limiting innovation capacity",
                "causes_process": "Product approval cycles too slow to compete with digital-native rivals",
                "causes_systems": "Core platforms cannot expose APIs at fintech speed",
                "causes_external": "Open banking regulation; well-funded neobanks; payment rails (e.g. real-time payment systems) commoditising basic banking",
                "consequence": "Customer base erosion, NIM compression, declining cross-sell, valuation impact.",
                "inh_likelihood": 4,
                "inh_impact": 4,
                "impact_rationale": "Financial — sustained revenue and franchise impact",
                "owner_suggested": "Chief Strategy Officer",
            },
            "TECH": {
                "title": "Competitor or technology shift renders product category obsolete",
                "description": "A new technology paradigm (e.g. AI-native architecture, no-code platforms, foundational model APIs) makes the company's product category outdated or commoditised.",
                "causes_people": "Engineering team building on aging architecture; lack of cross-functional research function",
                "causes_process": "Roadmap focused on incremental improvement, not platform shifts",
                "causes_systems": "Technology stack not modular enough to pivot quickly",
                "causes_external": "Foundational model launches; well-funded competitor entry; customer expectations shifting overnight",
                "consequence": "Rapid customer churn, valuation reset, forced pivot, layoffs, possible failure to raise next round.",
                "inh_likelihood": 4,
                "inh_impact": 5,
                "impact_rationale": "Financial — existential threat",
                "owner_suggested": "CEO / CTO",
            },
            "HCAR": {
                "title": "Disruption from digital health and alternative care models",
                "description": "Telehealth, AI-driven diagnostics, and consumer-direct health platforms substitute for traditional in-person clinical services.",
                "causes_people": "Clinical staff slow to adopt digital-first models",
                "causes_process": "Service redesign lags consumer expectation",
                "causes_systems": "Limited integration with telehealth, wearables, or remote-monitoring platforms",
                "causes_external": "Big-tech entry into healthcare; AI-enabled diagnostics; reimbursement model changes",
                "consequence": "Reduced patient volumes for in-person services, underutilised capacity, revenue compression, loss of relevance.",
                "inh_likelihood": 3,
                "inh_impact": 3,
                "impact_rationale": "Financial — combined with reputational and customer impact",
                "owner_suggested": "Chief Medical Officer",
            },
            "RETL": {
                "title": "Disruption from pure-play online, marketplace platforms, or new retail formats",
                "description": "Customers shift purchases to global marketplace platforms, social commerce, or new direct-to-consumer formats that the business cannot match on price, range, or convenience.",
                "causes_people": "Buying team focused on legacy categories; weak digital marketing capability",
                "causes_process": "Slow inventory turn and range refresh cycles vs. online-native competitors",
                "causes_systems": "Inability to ingest marketplace data; weak customer data platform",
                "causes_external": "Global marketplaces (e.g. Amazon, Temu, Shein); social commerce; private label brands gaining traction",
                "consequence": "Loss of market share, store underutilisation, margin compression, brand commoditisation.",
                "inh_likelihood": 5,
                "inh_impact": 4,
                "impact_rationale": "Financial — declining revenue and store viability",
                "owner_suggested": "CEO / Chief Digital Officer",
            },
            "INDU": {
                "title": "Disruption from new technology, materials, or business models",
                "description": "Emerging technologies (additive manufacturing, automation, alternative materials, autonomous logistics) or new business models displace established methods of production or delivery.",
                "causes_people": "Engineering and operations leadership rooted in established methods",
                "causes_process": "R&D investment biased to incremental rather than disruptive innovation",
                "causes_systems": "Asset planning frameworks not modelling disruptive scenarios",
                "causes_external": "Low-cost overseas competitors adopting new tech first; customer-driven sustainability requirements; commodity price shifts favouring substitutes",
                "consequence": "Loss of contracts, stranded capital equipment, workforce displacement, margin compression.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — capital and contract value at risk",
                "owner_suggested": "CEO",
            },
            "PUBL": {
                "title": "Disruption from new service delivery models or alternative providers",
                "description": "Beneficiaries, clients, or constituents shift to alternative providers, digital self-service, or community-led models that displace traditional service delivery.",
                "causes_people": "Service design capability limited within the organisation",
                "causes_process": "Slow internal change cycles vs. agile alternative providers",
                "causes_systems": "Legacy service-delivery systems creating poor user experience",
                "causes_external": "Government policy changes favouring competition; digital-native NFPs; commercial entrants in service space",
                "consequence": "Decline in service volume, funding loss, redundancy, reputational impact.",
                "inh_likelihood": 2,
                "inh_impact": 3,
                "impact_rationale": "Reputational — alongside funding impact",
                "owner_suggested": "CEO / Executive Director",
            },
        },
    },

    {
        "id": "R-003",
        "domain": "Strategic",
        "theme": "Failed M&A, partnership, or major investment",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Failed merger, lateral hire, or practice acquisition",
                "description": "A major lateral partner hire, practice merger, or geographic expansion fails to deliver expected revenue, client retention, or cultural integration.",
                "causes_people": "Cultural mismatch between firms; partner attrition post-deal; weak integration leadership",
                "causes_process": "Inadequate due diligence on revenue quality; no clear integration plan",
                "causes_systems": "Practice management, conflicts, and finance systems incompatible",
                "causes_external": "Key clients of acquired firm leave during transition",
                "consequence": "Goodwill write-downs, partner exits, client losses, distraction from core business, reputational impact.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — write-downs and lost revenue",
                "owner_suggested": "Managing Partner",
            },
            "FINS": {
                "title": "Failed acquisition, joint venture, or technology partnership",
                "description": "A major acquisition, JV, or strategic technology partnership fails to deliver financial returns, customer growth, or capability uplift.",
                "causes_people": "Integration team capacity constrained; cultural divergence between organisations",
                "causes_process": "Synergy targets unrealistic; inadequate due diligence on operational risk",
                "causes_systems": "Core banking platforms cannot integrate; data migration risk",
                "causes_external": "Regulatory delays; market shifts post-announcement; key talent leaving acquired entity",
                "consequence": "Goodwill impairment, regulatory action, customer attrition, board / shareholder action.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — write-downs and stranded investment",
                "owner_suggested": "CEO / Chief Strategy Officer",
            },
            "TECH": {
                "title": "Failed acquisition, product line investment, or strategic partnership",
                "description": "A major acquisition or strategic bet (new product line, vertical entry, major partnership) fails to deliver expected growth or capability.",
                "causes_people": "Founder / executive overconfidence; integration leadership lacking experience",
                "causes_process": "Inadequate technical and commercial due diligence; no clear post-deal operating model",
                "causes_systems": "Codebase or platform incompatibility; data migration risk",
                "causes_external": "Market thesis invalidated; key talent attrition post-deal",
                "consequence": "Goodwill write-down, distraction from core product, talent loss, valuation impact.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — write-downs and valuation impact",
                "owner_suggested": "CEO",
            },
            "HCAR": {
                "title": "Failed acquisition, service expansion, or capital project",
                "description": "A major capital investment (new facility, service line, acquired practice) fails to deliver expected patient volumes, clinical outcomes, or financial returns.",
                "causes_people": "Clinical leadership not engaged in business case; skill base mismatch",
                "causes_process": "Demand forecasting overoptimistic; weak implementation governance",
                "causes_systems": "Clinical and finance systems integration challenges",
                "causes_external": "Funding model changes; competitor opens nearby; clinical staff shortages",
                "consequence": "Capital impairment, operating losses, debt covenant pressure, board / regulator scrutiny.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — significant capital at risk",
                "owner_suggested": "CEO / CFO",
            },
            "RETL": {
                "title": "Failed store expansion, format change, or brand acquisition",
                "description": "Significant capital deployed into new stores, format conversions, or brand acquisitions fails to deliver expected sales density or returns.",
                "causes_people": "Buying / format design capability overstretched; weak local management",
                "causes_process": "Site selection or trade-area analysis flawed; rollout pace too aggressive",
                "causes_systems": "Inventory and supply chain systems unable to support expansion",
                "causes_external": "Consumer environment shifts post-investment; competitor response",
                "consequence": "Store closures, asset write-downs, rent liability, brand dilution.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — capital and lease impairment",
                "owner_suggested": "Chief Commercial Officer",
            },
            "INDU": {
                "title": "Failed major capital project, acquisition, or partnership",
                "description": "A large capital project (new plant, mine, infrastructure asset), acquisition, or JV fails to deliver expected output, returns, or strategic value.",
                "causes_people": "Project leadership inexperienced at scale; weak culture of cost discipline",
                "causes_process": "Cost and schedule estimates over-optimistic; weak stage-gate governance",
                "causes_systems": "Project controls and reporting tools immature for project scale",
                "causes_external": "Commodity price shifts; community opposition; permitting delays; partner default",
                "consequence": "Capital impairment, cost overruns, debt covenant pressure, stranded asset risk.",
                "inh_likelihood": 4,
                "inh_impact": 5,
                "impact_rationale": "Financial — material balance sheet impact",
                "owner_suggested": "CEO / Chief Projects Officer",
            },
            "PUBL": {
                "title": "Failed major program, partnership, or capital investment",
                "description": "A flagship program, multi-organisation partnership, or major infrastructure investment fails to deliver expected outcomes for beneficiaries or value for funders.",
                "causes_people": "Leadership turnover during delivery; consortium governance unclear",
                "causes_process": "Outcomes measurement weak; benefits realisation not tracked",
                "causes_systems": "Reporting systems immature; partner data integration challenges",
                "causes_external": "Funding withdrawn mid-program; political environment shifts; community opposition",
                "consequence": "Funding clawback, ministerial inquiry, reputational impact, loss of trust with funders.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Reputational — combined with funding impact",
                "owner_suggested": "CEO / Executive Director",
            },
        },
    },

    # ════════════════════════════════════════════════════════════════
    # DOMAIN: FINANCIAL (4 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-004",
        "domain": "Financial",
        "theme": "Cash flow / liquidity shortfall",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Working capital strain from extended client payment cycles",
                "description": "Slow-paying clients, billing lock-up, and partner drawings together create periodic cash flow stress.",
                "causes_people": "Partners reluctant to chase clients; weak finance discipline at engagement level",
                "causes_process": "Slow billing cycles; high WIP; insufficient retainer use",
                "causes_systems": "Practice management system not enforcing billing cadence",
                "causes_external": "Major clients in financial distress; economic slowdown extending payment terms",
                "consequence": "Inability to meet partner drawings, payroll, or tax commitments; emergency drawdowns on credit facility.",
                "inh_likelihood": 3,
                "inh_impact": 3,
                "impact_rationale": "Financial — direct cash flow impact",
                "owner_suggested": "CFO / Practice Manager",
            },
            "FINS": {
                "title": "Liquidity stress from funding mismatch or run on deposits",
                "description": "Mismatch between asset and liability tenors, or rapid customer outflows, creates liquidity pressure that may breach regulatory or operational thresholds.",
                "causes_people": "Treasury team capability gaps; ALCO oversight insufficient",
                "causes_process": "Funding plan over-reliant on one source; stress testing inadequate",
                "causes_systems": "Liquidity reporting systems slow to surface real-time positions",
                "causes_external": "Confidence event triggering rapid withdrawals; market closure for funding instruments",
                "consequence": "Regulatory breach, emergency funding at penalty rates, reputational impact, possible intervention.",
                "inh_likelihood": 2,
                "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe financial and reputational impact",
                "owner_suggested": "CFO / Treasurer",
            },
            "TECH": {
                "title": "Cash runway shortfall before next funding round or break-even",
                "description": "Burn rate, unexpected costs, or delayed revenue mean cash runway becomes critically short before the next funding milestone.",
                "causes_people": "CEO / CFO reluctance to act on burn early; sales hiring ahead of revenue",
                "causes_process": "Forecasting cycles too long; unit economics not closely tracked",
                "causes_systems": "Financial model not integrated with billing and cohort data",
                "causes_external": "Funding market closes; key customer churn; lengthening sales cycles",
                "consequence": "Down-round funding, layoffs, distressed sale, or insolvency.",
                "inh_likelihood": 3,
                "inh_impact": 5,
                "impact_rationale": "Financial — existential threat",
                "owner_suggested": "CFO / CEO",
            },
            "HCAR": {
                "title": "Operating cash flow pressure from funding model timing or volume shortfall",
                "description": "Reimbursement timing, casemix changes, or below-budget patient volumes lead to operating cash flow shortfalls.",
                "causes_people": "Coding and billing capability gaps; finance team capacity",
                "causes_process": "Slow billing of services; weak revenue cycle management",
                "causes_systems": "Patient management and billing systems not integrated; coding accuracy issues",
                "causes_external": "Funding model changes; payer disputes; demand drop (e.g. elective procedures)",
                "consequence": "Inability to meet payroll or supplier obligations, deferral of capital programs, possible regulator concern.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — combined with continuity of care concerns",
                "owner_suggested": "CFO",
            },
            "RETL": {
                "title": "Working capital strain from inventory build-up or seasonal mismatch",
                "description": "Excess inventory, delayed sell-through, or seasonal cash flow mismatches create pressure on working capital and supplier relationships.",
                "causes_people": "Buying team over-ordering; weak markdown discipline",
                "causes_process": "Inventory planning weak; range tail not actively managed",
                "causes_systems": "POS and inventory systems not surfacing slow-moving stock fast enough",
                "causes_external": "Sudden demand shift (e.g. weather, fashion cycle); supplier credit terms tightening",
                "consequence": "Distressed markdowns, supplier payment delays, breach of working-capital covenants, factoring usage.",
                "inh_likelihood": 4,
                "inh_impact": 3,
                "impact_rationale": "Financial — direct working capital impact",
                "owner_suggested": "CFO",
            },
            "INDU": {
                "title": "Cash flow pressure from project payment cycles and capex commitments",
                "description": "Long-cycle project payments, retentions, and ongoing capex commitments create periodic liquidity pressure.",
                "causes_people": "Project finance discipline weak; estimating assumptions optimistic",
                "causes_process": "Variation claims slow to be raised and recovered; retention release not actively pursued",
                "causes_systems": "Project accounting systems not integrated with cash forecasting",
                "causes_external": "Client payment delays; commodity price moves on input costs; regulatory delays affecting project milestones",
                "consequence": "Drawdown on credit facilities, deferral of capex, supplier pressure, possible covenant breach.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — direct liquidity and covenant impact",
                "owner_suggested": "CFO",
            },
            "PUBL": {
                "title": "Cash flow strain from grant timing or funding disruption",
                "description": "Delayed grant disbursements, funder requirements, or revenue diversification gaps create cash flow shortfalls.",
                "causes_people": "Finance capability stretched; fundraising team siloed from finance",
                "causes_process": "Grant compliance and acquittal slow; cash forecasting weak",
                "causes_systems": "Grants management system not integrated with financial system",
                "causes_external": "Government funding delays or cuts; donor fatigue; economic downturn affecting giving",
                "consequence": "Inability to meet payroll or program commitments, program suspension, reputational impact with beneficiaries.",
                "inh_likelihood": 3,
                "inh_impact": 4,
                "impact_rationale": "Financial — combined with mission delivery impact",
                "owner_suggested": "CFO",
            },
        },
    },
]

# --- end of batch 1 (Strategic + Financial R-004) ---
