"""Batch 3: R-012 through R-018 (People & HR + Technology & Cyber)"""

BATCH_3 = [
    # ════════════════════════════════════════════════════════════════
    # DOMAIN: PEOPLE & HR (3 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-012",
        "domain": "People and HR",
        "theme": "Loss of key personnel / succession gap",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Loss of key partners, fee earners, or specialist consultants",
                "description": "Departure of senior partners, niche specialists, or relationship-leading staff creates revenue, capability, and client-relationship gaps.",
                "causes_people": "Limited succession planning; key relationships held by single individuals; rainmaker culture",
                "causes_process": "No formal partner / talent retention program; equity arrangements unclear",
                "causes_systems": "Knowledge management weak; client relationships not formally documented",
                "causes_external": "Aggressive lateral recruitment by competitors; market events triggering moves",
                "consequence": "Loss of clients with the partner, revenue cliff, capability gap, team morale impact, possible team departures.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — combined with customer and reputational",
                "owner_suggested": "Managing Partner",
            },
            "FINS": {
                "title": "Loss of key executives, senior bankers, or specialist talent",
                "description": "Loss of executive leadership, senior bankers with key client relationships, or specialist roles (e.g. risk, compliance, technology) creates capability gaps.",
                "causes_people": "Succession planning informal at executive level; remuneration not market competitive",
                "causes_process": "Talent reviews infrequent; key-person designation not formalised",
                "causes_systems": "Knowledge transfer not systematised; client relationship management weak",
                "causes_external": "Competitor recruitment; M&A activity creating opportunities elsewhere",
                "consequence": "Strategic execution slowdown, client revenue at risk, regulator concern at executive turnover, possible team departures.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — combined with regulatory perception",
                "owner_suggested": "CHRO / CEO",
            },
            "TECH": {
                "title": "Loss of founders, executives, or key engineering talent",
                "description": "Departure of founders, key technical leaders, or specialist engineers (especially with deep product knowledge) creates significant continuity risk.",
                "causes_people": "Equity vesting cliffs; founder fatigue; manager span issues",
                "causes_process": "Documentation thin; bus factor of 1 on critical systems",
                "causes_systems": "Knowledge captured in individual heads; weak technical documentation",
                "causes_external": "Aggressive recruitment by competitors / FAANG; investor pressure changing direction",
                "consequence": "Roadmap delay, customer concern, investor concern, possible cascading departures.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — combined with customer and operational impact",
                "owner_suggested": "CEO / VP Engineering",
            },
            "HCAR": {
                "title": "Loss of key clinical leaders, specialists, or executive team",
                "description": "Departure of clinical leaders, sole-specialist clinicians, or executive team members creates capability and continuity gaps.",
                "causes_people": "Limited succession bench in specialised clinical roles; burnout in senior clinicians",
                "causes_process": "Workforce planning weak; locum dependence",
                "causes_systems": "Credentialing and onboarding slow; new starters take time to be productive",
                "causes_external": "National clinical workforce shortage; competing facility offering better conditions",
                "consequence": "Service closure or reduction, patient harm, accreditation impact, financial impact.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "People — patient care continuity",
                "owner_suggested": "Chief Medical Officer / CHRO",
            },
            "RETL": {
                "title": "Loss of key buyers, store leaders, or executives",
                "description": "Loss of category buyers, regional managers, or executive talent disrupts trading performance and strategic execution.",
                "causes_people": "Trading culture demanding; succession planning informal",
                "causes_process": "Talent review weak; no formal succession bench",
                "causes_systems": "Buyer-managed supplier relationships not documented",
                "causes_external": "Competitor recruitment; consumer-brand opportunities for buyers",
                "consequence": "Range and margin impact, supplier relationship disruption, store performance decline.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Financial — trading performance impact",
                "owner_suggested": "CHRO / Chief Commercial Officer",
            },
            "INDU": {
                "title": "Loss of skilled trades, engineers, or operational leaders",
                "description": "Departure of skilled trades, engineering leaders, or operational executives — often with deep institutional knowledge — disrupts production and project execution.",
                "causes_people": "Aging workforce; weak apprenticeship pipeline; few female / diverse candidates",
                "causes_process": "Knowledge transfer not formalised; succession planning patchy",
                "causes_systems": "Asset and process knowledge held informally; documentation limited",
                "causes_external": "Resource boom drawing talent; major project elsewhere offering premium rates",
                "consequence": "Production loss, project delays, safety risk during transition, capability erosion.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Financial — combined with safety risk",
                "owner_suggested": "Chief Operating Officer / CHRO",
            },
            "PUBL": {
                "title": "Loss of leadership, specialist staff, or experienced volunteers",
                "description": "Departure of CEO, senior leaders, or specialist staff (e.g. clinicians, social workers, fundraisers) creates significant continuity gaps.",
                "causes_people": "Below-market remuneration; mission fatigue; succession planning weak",
                "causes_process": "Volunteer management programs limited",
                "causes_systems": "Knowledge management weak across distributed sites",
                "causes_external": "Government and corporate sectors recruiting from sector; pay rate environment",
                "consequence": "Service disruption, funder concern, donor confidence impact, strategic execution slowdown.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Reputational — combined with operational impact",
                "owner_suggested": "CEO / CHRO",
            },
        },
    },

    {
        "id": "R-013",
        "domain": "People and HR",
        "theme": "Failure to attract and retain talent",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Inability to attract and retain quality professionals",
                "description": "Tight labour market, hybrid-work expectations, and competitor offers make hiring and retaining qualified professionals increasingly difficult.",
                "causes_people": "EVP not differentiated; partner mentoring inconsistent; bias in promotion",
                "causes_process": "Slow hiring processes; structured career development weak",
                "causes_systems": "ATS / talent management systems immature",
                "causes_external": "Big-4 / boutique competition; in-house counsel demand; international firms expanding",
                "consequence": "Capacity constraints, declined work, fee pressure, weakened succession.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Financial — combined with strategic capacity impact",
                "owner_suggested": "CHRO / Managing Partner",
            },
            "FINS": {
                "title": "Difficulty attracting and retaining specialist financial-services talent",
                "description": "Competition from fintech, technology, and global financial centres makes attraction and retention of specialist talent (technology, risk, advisory) difficult.",
                "causes_people": "Hierarchy and pace seen as outdated by next-gen talent; limited mobility",
                "causes_process": "Recruitment cycle slow; remuneration benchmarking infrequent",
                "causes_systems": "Talent analytics weak; succession planning systems immature",
                "causes_external": "Fintech and tech-sector remuneration premiums; international relocation opportunities",
                "consequence": "Capability gaps, project delays, regulator concern about talent depth, succession weakness.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Financial — combined with operational risk",
                "owner_suggested": "CHRO",
            },
            "TECH": {
                "title": "Difficulty attracting and retaining engineering and product talent",
                "description": "Hot labour market, remote-first competition, and equity expectations create challenges in hiring and retaining quality engineers, product, and data talent.",
                "causes_people": "Hiring bar inconsistent; engineering culture under pressure during scaling",
                "causes_process": "Hiring process slow vs. competitors; comp reviews infrequent",
                "causes_systems": "ATS not optimising candidate experience; equity systems opaque",
                "causes_external": "FAANG / well-funded scale-ups offering large packages; remote-first competitors",
                "consequence": "Roadmap delays, attrition spiral, founder time spent on hiring, possible burnout among remaining staff.",
                "inh_likelihood": 5, "inh_impact": 3,
                "impact_rationale": "Financial — combined with strategic and customer impact",
                "owner_suggested": "VP People / VP Engineering",
            },
            "HCAR": {
                "title": "Inability to attract and retain clinical and care workforce",
                "description": "National clinical workforce shortage, burnout, and competition with public/private providers makes hiring and retaining clinical staff (nurses, allied health, doctors) difficult.",
                "causes_people": "Burnout from pandemic and demand pressure; psychological safety gaps",
                "causes_process": "Onboarding and credentialing slow; rostering inflexible",
                "causes_systems": "Workforce management systems not optimising flexible work",
                "causes_external": "Public sector competition; international migration opportunities; immigration constraints",
                "consequence": "Service capacity reduced, locum costs ballooning, quality and safety risks, strategic plan delivery delayed.",
                "inh_likelihood": 5, "inh_impact": 4,
                "impact_rationale": "People — direct impact on care delivery",
                "owner_suggested": "CHRO / Chief Medical Officer",
            },
            "RETL": {
                "title": "Difficulty attracting and retaining store and DC workforce",
                "description": "Tight labour market, low pay perception, and shift work demands make hiring and retaining frontline retail and DC staff challenging.",
                "causes_people": "EVP weak vs. competitor (e.g. logistics) employers; supervisor capability gaps",
                "causes_process": "Onboarding slow; training inconsistent",
                "causes_systems": "Workforce management not optimising rostering",
                "causes_external": "Strong labour market; minimum wage legislation; lifestyle preference shifts",
                "consequence": "Store understaffing, customer experience decline, increased shrinkage, manager turnover.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Customer — combined with financial impact",
                "owner_suggested": "CHRO",
            },
            "INDU": {
                "title": "Skilled trades and operator workforce shortage",
                "description": "Aging workforce, declining apprenticeships, and competing demand from major projects make industrial hiring difficult.",
                "causes_people": "Industry image issues; weak diversity attraction; succession not planned",
                "causes_process": "Apprenticeship and training pipelines underfunded",
                "causes_systems": "Workforce planning and competency systems immature",
                "causes_external": "Major projects competing for skilled trades; government infrastructure spend; immigration policy",
                "consequence": "Production constraints, project delays, safety risk during workforce transitions, premium-cost contractor reliance.",
                "inh_likelihood": 5, "inh_impact": 4,
                "impact_rationale": "Financial — combined with safety and operational impact",
                "owner_suggested": "CHRO / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Difficulty attracting and retaining mission-driven staff and volunteers",
                "description": "Below-market remuneration, mission fatigue, and competition from corporate purpose programs limit ability to attract and retain talent.",
                "causes_people": "Pay rates below sector benchmarks; mission fatigue post-crisis",
                "causes_process": "Volunteer management informal; recognition programs limited",
                "causes_systems": "HR systems immature; volunteer coordination manual",
                "causes_external": "Corporate purpose-driven roles offering higher pay; cost of living forcing career changes",
                "consequence": "Service delivery constraints, volunteer base shrinking, leadership succession weak.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Social — service delivery and reputational",
                "owner_suggested": "CHRO / CEO",
            },
        },
    },

    {
        "id": "R-014",
        "domain": "People and HR",
        "theme": "Culture, conduct, or workplace misconduct",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Workplace misconduct, harassment, or bullying allegations",
                "description": "Allegations of bullying, harassment, or misconduct (including against partners) cause harm to staff, legal exposure, and reputational damage.",
                "causes_people": "Hierarchical culture; tolerance of high-performer behaviour; weak accountability for partners",
                "causes_process": "Speak-up culture immature; investigations inconsistent",
                "causes_systems": "Whistleblowing channels limited; HR case management weak",
                "causes_external": "Heightened public scrutiny; class action risk; mental-health public discourse",
                "consequence": "Staff harm, legal claims, regulator attention (e.g. SafeWork), reputational damage, partner accountability action.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "People — combined with reputational and regulatory",
                "owner_suggested": "CHRO / Managing Partner",
            },
            "FINS": {
                "title": "Conduct issues, misconduct, or culture-driven failures",
                "description": "Misconduct, sales-driven culture, or systemic culture issues lead to poor customer outcomes, regulator action, and possible enforcement against individuals.",
                "causes_people": "Sales / performance pressure misaligned with conduct expectations",
                "causes_process": "Conduct frameworks weak; speak-up channels under-trusted",
                "causes_systems": "Conduct monitoring systems immature; HR case management limited",
                "causes_external": "Regulator focus on banking conduct (post-Royal Commission environment); whistleblower protections",
                "consequence": "Regulator action against individuals and the institution, fines, remediation costs, reputational impact, possible licence conditions.",
                "inh_likelihood": 3, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe reputational impact",
                "owner_suggested": "CHRO / Chief Risk Officer",
            },
            "TECH": {
                "title": "Workplace culture issues, misconduct, or harassment",
                "description": "High-pressure scaling culture, misconduct, or harassment allegations damage team trust, drive attrition, and create legal exposure.",
                "causes_people": "Founder behaviour normalised by team; growth culture overriding fairness",
                "causes_process": "HR investigations weak in early-stage companies; performance management informal",
                "causes_systems": "Whistleblowing and HR case systems immature",
                "causes_external": "Public scrutiny of tech-sector culture; investor focus on culture in due diligence",
                "consequence": "Attrition spiral, public reputation damage, investor concern, possible litigation.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "People — combined with reputational and operational",
                "owner_suggested": "VP People / CEO",
            },
            "HCAR": {
                "title": "Workplace bullying, harassment, or culture issues affecting clinical teams",
                "description": "Hierarchical clinical culture and pressure environments create risk of bullying, harassment, or psychological injury to staff.",
                "causes_people": "Hierarchical clinical structures; long shifts; high-stakes decision pressure",
                "causes_process": "Speak-up culture immature; clinical leadership accountability inconsistent",
                "causes_systems": "Incident reporting and HR case management not joined up",
                "causes_external": "Workforce shortage increasing pressure; public attention on healthcare bullying",
                "consequence": "Staff harm, attrition, regulator and registrar action, patient safety risk, reputational impact.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "People — staff and patient safety",
                "owner_suggested": "CHRO / Chief Medical Officer",
            },
            "RETL": {
                "title": "Workplace conduct, harassment, or wage compliance issues",
                "description": "Workplace conduct issues, harassment by customers or staff, or wage compliance failures (e.g. underpayments) create exposure.",
                "causes_people": "Casual workforce supervision; customer-facing pressure",
                "causes_process": "Wage rate compliance complex; investigation processes weak in distributed teams",
                "causes_systems": "Workforce / payroll systems with errors; HR case systems limited",
                "causes_external": "Wage theft enforcement environment; customer abuse of staff trends",
                "consequence": "Wage claims (potentially substantial), regulator action, class actions, reputational damage, staff attrition.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "People — combined with regulatory and reputational",
                "owner_suggested": "CHRO",
            },
            "INDU": {
                "title": "Safety culture, conduct, or workplace misconduct issues",
                "description": "Macho culture, hierarchy, or substance issues in industrial settings create risk of misconduct, harassment, and safety culture failure.",
                "causes_people": "Long-tenured workforce; cultural change resistance; substance use in some sectors",
                "causes_process": "Investigations inconsistent at site level; weak supervision",
                "causes_systems": "Reporting and case management systems limited at remote sites",
                "causes_external": "Industry-wide culture review programs; community expectations of mining / construction",
                "consequence": "Staff harm, possible safety incident, regulator action, contract loss (where customers require compliance), reputational impact.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "People — combined with safety and operational",
                "owner_suggested": "CHRO / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Workplace culture, conduct, or harassment issues",
                "description": "Mission-driven culture under pressure can mask conduct issues, including harassment, bullying, or boundary violations with vulnerable beneficiaries.",
                "causes_people": "Long-tenured staff; volunteer involvement; hierarchical environments",
                "causes_process": "Investigations inconsistent; safeguarding processes immature",
                "causes_systems": "HR and safeguarding case systems limited",
                "causes_external": "Sector-wide safeguarding reform; royal commission outcomes; sector reviews",
                "consequence": "Staff or beneficiary harm, regulator and police action, funder withdrawal, reputational destruction.",
                "inh_likelihood": 3, "inh_impact": 5,
                "impact_rationale": "Reputational — combined with severe people and regulatory impact",
                "owner_suggested": "CHRO / CEO",
            },
        },
    },

    # ════════════════════════════════════════════════════════════════
    # DOMAIN: TECHNOLOGY & CYBER (4 themes)
    # ════════════════════════════════════════════════════════════════
    {
        "id": "R-015",
        "domain": "Technology and Cyber",
        "theme": "Cyber attack / security breach",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Cyber attack targeting client confidential information and trust accounts",
                "description": "Phishing, business email compromise, ransomware, or targeted attacks aim to steal client confidential information or divert trust funds.",
                "causes_people": "Partners and PAs handling sensitive matters under time pressure; awareness inconsistent",
                "causes_process": "Multi-factor authentication gaps; payment verification informal",
                "causes_systems": "Email security baseline; legacy practice management systems",
                "causes_external": "Targeted phishing; supply chain compromise (e.g. e-discovery vendors); state-actor interest in M&A intel",
                "consequence": "Client confidential information breach, trust account loss, professional indemnity claim, regulator action (privacy, law society), reputational devastation.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe financial and reputational impact",
                "owner_suggested": "Head of IT / CISO / Managing Partner",
            },
            "FINS": {
                "title": "Cyber attack targeting customer accounts, trading systems, or core banking",
                "description": "Sophisticated attacks targeting customer credentials, internal banking systems, or trading infrastructure threaten direct financial loss and systemic risk.",
                "causes_people": "Insider threat; sophisticated social engineering of senior staff",
                "causes_process": "Patching cycles slow; identity and access management weak in legacy systems",
                "causes_systems": "Mainframe and legacy systems with security gaps; complex IT estate",
                "causes_external": "Nation-state actors; organised cybercrime; supply chain attacks (e.g. SolarWinds-style)",
                "consequence": "Customer financial loss, regulator action (APRA / RBNZ / FCA), class actions, reputational impact, possible licence condition action.",
                "inh_likelihood": 5, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe financial and customer impact",
                "owner_suggested": "CISO / Chief Risk Officer",
            },
            "TECH": {
                "title": "Cyber attack targeting customer data, source code, or production systems",
                "description": "Attacks on production infrastructure, customer data, or source code repositories threaten customer trust, IP, and business continuity.",
                "causes_people": "Engineer credentials phished; insider threat; rapid hiring with limited vetting",
                "causes_process": "Code review and access reviews inconsistent; secret management immature",
                "causes_systems": "Cloud misconfiguration; supply chain vulnerabilities; CI/CD pipeline weaknesses",
                "causes_external": "Sophisticated actors targeting tech IP; supply chain attacks (e.g. compromised dependencies)",
                "consequence": "Customer data breach, IP loss, customer churn, contractual penalties, valuation impact, regulator action.",
                "inh_likelihood": 5, "inh_impact": 5,
                "impact_rationale": "Customer — combined with regulatory and financial impact",
                "owner_suggested": "CISO / VP Engineering",
            },
            "HCAR": {
                "title": "Cyber attack on patient records, clinical systems, or medical devices",
                "description": "Ransomware, data theft, or attacks on connected medical devices threaten patient care continuity and patient privacy.",
                "causes_people": "Clinicians under pressure clicking phishing emails; widespread shared credentials",
                "causes_process": "Patching cycles slow on clinical systems; medical device security weak",
                "causes_systems": "Legacy clinical systems; connected medical devices with limited security",
                "causes_external": "Healthcare-targeted ransomware; nation-state interest in health data",
                "consequence": "Patient harm from system unavailability, data breach affecting hundreds of thousands, regulator action, very large remediation costs.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "People — combined with severe regulatory and customer impact",
                "owner_suggested": "CISO / Chief Information Officer",
            },
            "RETL": {
                "title": "Cyber attack on customer payment data, e-commerce platform, or POS",
                "description": "Attacks on customer card data, e-commerce platforms, or POS infrastructure threaten trading, customer data, and PCI-DSS compliance.",
                "causes_people": "Casual store workforce with shared credentials; awareness inconsistent",
                "causes_process": "PCI-DSS compliance lapses; vulnerability management weak",
                "causes_systems": "Aging POS systems; e-commerce platform vulnerabilities; loyalty data exposed",
                "causes_external": "Magecart / e-skimming attacks; ransomware groups targeting retailers in peak season",
                "consequence": "Payment data breach, PCI-DSS fines, customer harm, e-commerce shutdown during peak, brand damage.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with customer and reputational impact",
                "owner_suggested": "CISO / Chief Information Officer",
            },
            "INDU": {
                "title": "Cyber attack on operational technology, ICS / SCADA, or corporate systems",
                "description": "Attacks on operational technology, industrial control systems, or corporate IT threaten safety, production, and intellectual property.",
                "causes_people": "OT operators not security-trained; convergence of IT/OT teams immature",
                "causes_process": "OT change management weak; air-gap assumptions outdated",
                "causes_systems": "Legacy ICS / SCADA with limited security; OT/IT convergence creating new attack paths",
                "causes_external": "Nation-state actors; ransomware groups targeting critical infrastructure; supply chain compromise",
                "consequence": "Production loss, safety incident, environmental incident, IP loss, ransomware payments, regulator action under critical infrastructure laws.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "People — combined with operational and regulatory impact",
                "owner_suggested": "CISO / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Cyber attack on beneficiary data, programmes, or core systems",
                "description": "Attacks on systems holding beneficiary or donor data, or on core operating systems, threaten privacy, trust, and service delivery.",
                "causes_people": "Limited cyber budget; awareness training infrequent",
                "causes_process": "Vulnerability management ad-hoc; backups not regularly tested",
                "causes_systems": "Legacy systems; minimal MFA; cloud configurations weak",
                "causes_external": "Ransomware groups targeting NFPs; supply chain compromise",
                "consequence": "Beneficiary data breach (highly sensitive in many cases), donor confidence loss, regulator action, programme disruption.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Reputational — combined with severe customer and regulatory impact",
                "owner_suggested": "CIO / CEO",
            },
        },
    },

    {
        "id": "R-016",
        "domain": "Technology and Cyber",
        "theme": "Data loss, corruption, or unauthorised disclosure",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Loss, corruption, or accidental disclosure of client data",
                "description": "Backup failure, system corruption, accidental disclosure (wrong recipient), or data theft results in loss of client confidential information.",
                "causes_people": "Misaddressed emails; lost devices; staff handling sensitive data without training",
                "causes_process": "Email and document workflows error-prone; data classification weak",
                "causes_systems": "Backup verification weak; data loss prevention tooling limited",
                "causes_external": "Vendor-side breach; client device compromise affecting shared workspaces",
                "consequence": "Client confidential information disclosure, professional indemnity claim, regulator action, partner accountability.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with reputational impact",
                "owner_suggested": "Chief Information Officer / Privacy Officer",
            },
            "FINS": {
                "title": "Customer data loss, corruption, or unauthorised disclosure",
                "description": "Operational error, system corruption, or insider activity leads to loss or unauthorised disclosure of customer financial and identity data.",
                "causes_people": "Operational team error; insider activity; offshore vendor handling",
                "causes_process": "Data minimisation weak; classification and handling controls inconsistent",
                "causes_systems": "Data lineage poor; legacy systems with weak access controls",
                "causes_external": "Vendor breach; supply chain compromise",
                "consequence": "Privacy breach notifications affecting hundreds of thousands, regulator fines, class actions, customer remediation costs.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with severe financial and reputational impact",
                "owner_suggested": "CIO / Privacy Officer",
            },
            "TECH": {
                "title": "Customer data loss, corruption, or accidental disclosure",
                "description": "Backup failure, deployment error, configuration mistake, or insider error leads to customer data loss, corruption, or disclosure.",
                "causes_people": "Engineer error during deployment; access management gaps",
                "causes_process": "Data backup and recovery testing inconsistent; deployment safeguards immature",
                "causes_systems": "Cloud configuration errors; database backups not validated",
                "causes_external": "Supply chain (e.g. compromised library or SaaS dependency)",
                "consequence": "Customer trust loss, contractual breach, regulatory action, possible class action.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Customer — combined with regulatory impact",
                "owner_suggested": "CISO / VP Engineering",
            },
            "HCAR": {
                "title": "Patient data loss, corruption, or unauthorised disclosure",
                "description": "Loss, corruption, or disclosure of patient medical records (highly sensitive) through error, system failure, or insider activity.",
                "causes_people": "Clinicians sharing data informally; access controls broad; insider snooping",
                "causes_process": "Data handling protocols inconsistent; emailing of PHI common",
                "causes_systems": "Clinical systems with weak audit trails; medical device data not controlled",
                "causes_external": "Vendor-side breach; legal disclosures involving cross-border transfers",
                "consequence": "Patient privacy breach (highly sensitive — health, mental health, addiction etc.), regulator action, registrar action against clinicians, criminal charges in extreme cases.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "People — patient privacy and harm",
                "owner_suggested": "Privacy Officer / Chief Medical Officer",
            },
            "RETL": {
                "title": "Customer data, payment data, or loyalty data loss or disclosure",
                "description": "Loss or unauthorised disclosure of customer information, payment data, or loyalty program data through error, system failure, or insider activity.",
                "causes_people": "Marketing team handling customer data informally; offshore call centre data handling",
                "causes_process": "Data sharing with third parties not controlled; data minimisation weak",
                "causes_systems": "CRM and loyalty systems aggregating data; backup procedures weak",
                "causes_external": "Vendor breach (e.g. CRM, marketing automation provider)",
                "consequence": "Privacy breach affecting many customers, PCI-DSS implications, regulator fines, brand damage.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Regulatory — combined with reputational impact",
                "owner_suggested": "Privacy Officer / CIO",
            },
            "INDU": {
                "title": "Loss or disclosure of operational data, IP, or customer commercial data",
                "description": "Loss, corruption, or unauthorised disclosure of operational data, project IP, customer pricing, or commercial-in-confidence information.",
                "causes_people": "Engineers and project teams handling data on personal devices; offshore vendor access",
                "causes_process": "Data classification weak; cross-border data sharing policies limited",
                "causes_systems": "Engineering and project systems with broad access; backup procedures weak",
                "causes_external": "State-actor IP theft; competitor industrial espionage; vendor breach",
                "consequence": "Loss of competitive advantage, customer contract loss, possible regulator action under critical infrastructure laws.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Financial — IP and contract value impact",
                "owner_suggested": "CISO / CIO",
            },
            "PUBL": {
                "title": "Loss or disclosure of beneficiary, donor, or programme data",
                "description": "Loss or unauthorised disclosure of sensitive beneficiary information (often vulnerable populations) or donor records.",
                "causes_people": "Volunteers and casual staff with broad access; awareness training limited",
                "causes_process": "Safeguarding-driven data needs vs. minimisation tension; weak retention policies",
                "causes_systems": "Case management systems with weak controls; legacy donor databases",
                "causes_external": "Targeted attacks on NFP sector; vendor breaches",
                "consequence": "Harm to vulnerable individuals (potentially severe), regulator action, donor and funder withdrawal, reputational damage.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "People — beneficiary safety combined with reputational",
                "owner_suggested": "Privacy Officer / CEO",
            },
        },
    },

    {
        "id": "R-017",
        "domain": "Technology and Cyber",
        "theme": "System / platform outage or unavailability",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Outage of practice management, document, or productivity platforms",
                "description": "Cloud outage, configuration error, or major incident with practice management or productivity platforms prevents fee earners from working.",
                "causes_people": "Limited IT operations capability; over-reliance on key vendors",
                "causes_process": "Disaster recovery testing infrequent; alternative working arrangements limited",
                "causes_systems": "Single-cloud or single-vendor dependence; minimal local backup",
                "causes_external": "Cloud or SaaS vendor outage; ISP / connectivity disruption",
                "consequence": "Productivity loss, missed deadlines, client communication delays, reputational concern.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Customer — combined with financial impact",
                "owner_suggested": "Chief Information Officer",
            },
            "FINS": {
                "title": "Outage of customer-facing or core banking systems",
                "description": "Major outage of mobile / web banking, core banking, or trading systems prevents customers transacting, with regulatory implications.",
                "causes_people": "Change management discipline lapses; on-call coverage gaps",
                "causes_process": "Release management and change-control weak; resilience testing limited",
                "causes_systems": "Legacy mainframe; complex integration estate; partial cloud migration",
                "causes_external": "Cloud / vendor outages; major payment-rail disruption",
                "consequence": "Customer access outage, regulator engagement (APRA / FCA / etc.), media attention, compensation costs, reputational damage.",
                "inh_likelihood": 4, "inh_impact": 5,
                "impact_rationale": "Regulatory — combined with customer and reputational impact",
                "owner_suggested": "CIO / Chief Operating Officer",
            },
            "TECH": {
                "title": "Production outage affecting customer-facing service",
                "description": "Production outage, performance degradation, or partial-failure scenarios affect customers, breaching SLAs and damaging trust.",
                "causes_people": "Engineering on-call gaps; key SRE personnel turnover",
                "causes_process": "Change management at scale immature; release safeguards limited",
                "causes_systems": "Single-region architecture; observability gaps; capacity headroom inadequate",
                "causes_external": "Cloud provider regional outages; DNS / CDN disruption; DDoS",
                "consequence": "SLA breach, customer credits, churn, NPS impact, growth-stage reputational damage.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Customer — service availability and contractual impact",
                "owner_suggested": "VP Engineering / Head of SRE",
            },
            "HCAR": {
                "title": "Outage of clinical systems or critical operational platforms",
                "description": "Outage of EMR / EHR, lab systems, imaging, or critical operational platforms forces reversion to manual processes, creating clinical risk.",
                "causes_people": "Clinical IT support capability limited",
                "causes_process": "Manual fallback procedures untested; communication during outage weak",
                "causes_systems": "Legacy clinical systems; integration weak between systems",
                "causes_external": "Cloud outage; vendor outage; ransomware-driven outage",
                "consequence": "Clinical risk from manual processes, care delays, regulator notification, reputational impact.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "People — patient safety risk",
                "owner_suggested": "CIO / Chief Medical Officer",
            },
            "RETL": {
                "title": "Outage of POS, e-commerce, or supply chain systems",
                "description": "Outage of customer-facing systems (POS, e-commerce, payments) or supply chain systems prevents trading, especially impactful at peak.",
                "causes_people": "IT operations under-resourced; release management discipline gaps",
                "causes_process": "Release management not factoring trading peaks; resilience testing limited",
                "causes_systems": "Aging in-store technology; e-commerce platform single-region",
                "causes_external": "Cloud outage; payment provider outage; carrier outage during peak",
                "consequence": "Trading interruption, lost sales (often unrecoverable at peak), customer dissatisfaction, brand damage.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Customer — combined with direct financial loss",
                "owner_suggested": "CIO / Chief Operating Officer",
            },
            "INDU": {
                "title": "Outage of operational technology, ERP, or production systems",
                "description": "Outage of OT, ERP, MES, or other production-critical systems halts production, project execution, or logistics.",
                "causes_people": "OT and IT teams not aligned; key SCADA engineers turnover",
                "causes_process": "Change management on OT weak; backup procedures untested",
                "causes_systems": "Legacy ICS / SCADA; weak segregation of OT/IT networks",
                "causes_external": "Vendor outages; power / connectivity outages; cyber-driven outage",
                "consequence": "Production halt, contract penalties, asset damage in some scenarios, customer loss.",
                "inh_likelihood": 3, "inh_impact": 4,
                "impact_rationale": "Financial — production loss",
                "owner_suggested": "CIO / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Outage of case management, payment, or programme systems",
                "description": "Outage of core systems for case management, payments to beneficiaries, or programme delivery disrupts services.",
                "causes_people": "IT support resource limited",
                "causes_process": "Disaster recovery procedures not regularly tested",
                "causes_systems": "Legacy systems; vendor support timeframes lengthy",
                "causes_external": "Vendor outages; ransomware events affecting NFP-sector providers",
                "consequence": "Beneficiary harm from service disruption (especially time-critical payments), reputational impact, regulator concern.",
                "inh_likelihood": 3, "inh_impact": 3,
                "impact_rationale": "Social — service delivery to vulnerable beneficiaries",
                "owner_suggested": "CIO / Chief Operating Officer",
            },
        },
    },

    {
        "id": "R-018",
        "domain": "Technology and Cyber",
        "theme": "Technology obsolescence / unmanaged technical debt",
        "treatment": "Reduce",
        "industries": {
            "PROF": {
                "title": "Aging practice management and productivity systems",
                "description": "Practice management, document management, or productivity systems become outdated, unsupported, or unable to keep pace with client expectations.",
                "causes_people": "Reluctance among partners to invest in technology; CIO budget constrained",
                "causes_process": "Technology refresh program reactive; capital allocation favours fee-earner roles",
                "causes_systems": "Legacy practice management; on-premise file servers; integration challenges",
                "causes_external": "Client expectations of modern collaboration; competitor firms offering better digital experience",
                "consequence": "Productivity loss, talent attraction issues, client dissatisfaction, security risks from unsupported software.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Financial — productivity and competitive position",
                "owner_suggested": "Chief Information Officer / Managing Partner",
            },
            "FINS": {
                "title": "Legacy technology, core banking debt, and integration complexity",
                "description": "Legacy core banking, claims, or trading systems combined with a complex integration estate constrain agility, raise cost, and create risk.",
                "causes_people": "Specialist legacy skills retiring; talent reluctant to work on legacy",
                "causes_process": "Capital allocation biased to revenue-generating projects over modernisation",
                "causes_systems": "Mainframe and on-prem systems with high cost and risk; integration spaghetti",
                "causes_external": "Regulator pressure on resilience; cloud-native challenger expectations",
                "consequence": "Slow product launches, cost base inflation, regulator concern, possible major outages, loss of customer trust.",
                "inh_likelihood": 5, "inh_impact": 4,
                "impact_rationale": "Operational — combined with financial and regulatory impact",
                "owner_suggested": "CIO / CTO",
            },
            "TECH": {
                "title": "Technical debt, monolithic architecture, or aging tech stack",
                "description": "Accumulated technical debt, monolithic architecture, or aging tech stack constrain product velocity, scaling, and reliability.",
                "causes_people": "Founding-era engineers leaving; pressure on roadmap over refactoring",
                "causes_process": "Technical debt not measured or budgeted",
                "causes_systems": "Monolithic codebase; aging dependencies; unmaintained internal tools",
                "causes_external": "Frameworks deprecated; AI-native architectures resetting expectations",
                "consequence": "Roadmap slowdown, hiring difficulty, reliability issues, security exposure, eventual rewrite cost.",
                "inh_likelihood": 5, "inh_impact": 3,
                "impact_rationale": "Financial — combined with strategic and operational impact",
                "owner_suggested": "VP Engineering / CTO",
            },
            "HCAR": {
                "title": "Legacy clinical systems and unmanaged technical debt",
                "description": "Clinical and administrative systems become outdated, lacking interoperability, security, and the data foundations needed for modern care delivery.",
                "causes_people": "Clinical IT capability limited; vendor lock-in",
                "causes_process": "Capital prioritised for clinical equipment over IT; modernisation business cases hard",
                "causes_systems": "Legacy clinical systems; weak interoperability; manual integration",
                "causes_external": "National e-health standards evolving; AI-driven clinical tooling expectations",
                "consequence": "Inability to adopt new care models, security exposure, productivity drag, accreditation risk.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Operational — combined with regulatory pressure",
                "owner_suggested": "CIO / Chief Medical Officer",
            },
            "RETL": {
                "title": "Aging POS, e-commerce, and supply chain technology",
                "description": "POS, supply chain, and digital channel technology becomes outdated, limiting omnichannel execution and operational flexibility.",
                "causes_people": "Capital allocation favours marketing spend over technology",
                "causes_process": "Technology refresh slow; dependent on legacy retail packages",
                "causes_systems": "Aging in-store technology; supply chain systems on-prem; integration weak",
                "causes_external": "Pure-play competitors with modern stack; consumer expectations of seamless omnichannel",
                "consequence": "Inability to respond to customer expectations, sales loss, security exposure, integration cost growing.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Customer — combined with competitive position",
                "owner_suggested": "CIO / Chief Commercial Officer",
            },
            "INDU": {
                "title": "Legacy OT, ICS, and asset technology with significant technical debt",
                "description": "Legacy operational technology, control systems, and asset technology constrain efficiency, reliability, and security, with rising support cost.",
                "causes_people": "Specialist OT engineering skills aging out; vendor lock-in",
                "causes_process": "OT refresh cycles long; safety and certification adding complexity",
                "causes_systems": "Legacy SCADA / DCS; unsupported software in production environment",
                "causes_external": "Critical infrastructure regulation tightening; vendor support windows ending",
                "consequence": "Security exposure, reliability risk, regulatory action, increasing cost to maintain.",
                "inh_likelihood": 4, "inh_impact": 4,
                "impact_rationale": "Operational — combined with regulatory and security impact",
                "owner_suggested": "CIO / Chief Operating Officer",
            },
            "PUBL": {
                "title": "Aging operational and case-management systems",
                "description": "Legacy systems for case management, payments, and reporting create operational drag, security risk, and limit ability to demonstrate outcomes.",
                "causes_people": "IT capability limited; capital constrained",
                "causes_process": "Modernisation business cases hard to fund within mission spend",
                "causes_systems": "Legacy custom-built or donated systems; weak integration",
                "causes_external": "Funder expectations of digital service delivery; cyber-security expectations rising",
                "consequence": "Operational drag, security exposure, inability to demonstrate impact, funding consequences.",
                "inh_likelihood": 4, "inh_impact": 3,
                "impact_rationale": "Operational — combined with funding consequences",
                "owner_suggested": "CIO / CEO",
            },
        },
    },
]
